#!/usr/bin/env python3
"""
Script automático para traducir entradas obvias del PO file español->inglés
"""
import re

# Diccionario de traducciones directas comunes
TRANSLATIONS = {
    "Usuario": "User",
    "Usuarios": "Users",
    "Cliente": "Client",
    "Clientes": "Clients",
    "Proyecto": "Project",
    "Proyectos": "Projects",
    "Tarea": "Task",
    "Tareas": "Tasks",
    "Nombre": "Name",
    "Descripción": "Description",
    "Fecha": "Date",
    "Estado": "Status",
    "Crear": "Create",
    "Editar": "Edit",
    "Eliminar": "Delete",
    "Guardar": "Save",
    "Cancelar": "Cancel",
    "Volver": "Back",
    "Ver": "View",
    "Activo": "Active",
    "Inactivo": "Inactive",
    "Sí": "Yes",
    "No": "No",
    "Buscar": "Search",
    "Filtrar": "Filter",
    "Todos": "All",
    "Nuevo": "New",
    "Nueva": "New",
    "Total": "Total",
    "Detalles": "Details",
    "Información": "Information",
    "Notas": "Notes",
    "Comentarios": "Comments",
    "Archivo": "File",
    "Archivos": "Files",
    "Foto": "Photo",
    "Fotos": "Photos",
    "Cargar": "Upload",
    "Descargar": "Download",
    "Imprimir": "Print",
    "Exportar": "Export",
    "Importar": "Import",
    "Agregar": "Add",
    "Quitar": "Remove",
    "Seleccionar": "Select",
    "Confirmar": "Confirm",
    "Cerrar": "Close",
    "Abrir": "Open",
    "Enviar": "Send",
    "Recibir": "Receive",
    "Completar": "Complete",
    "Pendiente": "Pending",
    "En progreso": "In progress",
    "Completado": "Completed",
    "Activos": "Active",
    "Dashboard": "Dashboard",
    "Panel": "Panel",
    "Gestión": "Management",
    "Administración": "Administration",
    "Configuración": "Configuration",
    "Ajustes": "Settings",
    "Perfil": "Profile",
    "Contraseña": "Password",
    "Email": "Email",
    "Teléfono": "Phone",
    "Dirección": "Address",
    "Ciudad": "City",
    "País": "Country",
    "Código": "Code",
    "Categoría": "Category",
    "Tipo": "Type",
    "Monto": "Amount",
    "Cantidad": "Quantity",
    "Precio": "Price",
    "Costo": "Cost",
    "Ingreso": "Income",
    "Ingresos": "Income",
    "Gasto": "Expense",
    "Gastos": "Expenses",
    "Factura": "Invoice",
    "Recibo": "Receipt",
    "Pago": "Payment",
    "Presupuesto": "Budget",
    "Reporte": "Report",
    "Reportes": "Reports",
    "Documento": "Document",
    "Documentos": "Documents",
    "Mensaje": "Message",
    "Mensajes": "Messages",
    "Notificación": "Notification",
    "Notificaciones": "Notifications",
    "Alerta": "Alert",
    "Alertas": "Alerts",
    "Error": "Error",
    "Advertencia": "Warning",
    "Éxito": "Success",
    "Fallo": "Failed",
    "Cargando": "Loading",
    "Procesando": "Processing",
    "Completado": "Completed",
    "Inicio": "Home",
    "Salir": "Logout",
    "Ayuda": "Help",
    "Acerca de": "About",
    "Contacto": "Contact",
    "Soporte": "Support",
    "Términos": "Terms",
    "Privacidad": "Privacy",
    "Legal": "Legal",
    # Frases compuestas adicionales
    "Información del Sistema": "System Information",
    "Información del Grupo": "Group Information",
    "Información Básica": "Basic Information",
    "Información Personal": "Personal Information",
    "Información de Contacto": "Contact Information",
    "Información Adicional": "Additional Information",
    "Información Importante": "Important Information",
    "Información del Cliente": "Client Information",
    "Accesos Rápidos": "Quick Access",
    "Crear Nuevo": "Create New",
    "Nuevo Cliente": "New Client",
    "Nuevo Proyecto": "New Project",
    "Nueva Tarea": "New Task",
    "Usuarios Activos": "Active Users",
    "Proyectos Activos": "Active Projects",
    "Tareas Pendientes": "Pending Tasks",
    "Sin resultados": "No results",
    "Sin registros": "No records",
    "Sin datos": "No data",
    "Cargando...": "Loading...",
    "Procesando...": "Processing...",
    "Por favor espere": "Please wait",
    "Volver al inicio": "Back to home",
    "Volver atrás": "Go back",
    "Ver más": "View more",
    "Ver todos": "View all",
    "Ver detalles": "View details",
    "Mostrar más": "Show more",
    "Mostrar menos": "Show less",
    "Seleccione una opción": "Select an option",
    "Seleccione un proyecto": "Select a project",
    "Seleccione un cliente": "Select a client",
    "Campo requerido": "Required field",
    "Campo obligatorio": "Required field",
    "Campos obligatorios": "Required fields",
    "Ingrese un valor": "Enter a value",
    "Ingrese su nombre": "Enter your name",
    "Ingrese su email": "Enter your email",
    "Acción exitosa": "Successful action",
    "Operación exitosa": "Successful operation",
    "Error al procesar": "Error processing",
    "Error al guardar": "Error saving",
    "Guardado exitoso": "Successfully saved",
    "Actualizado exitoso": "Successfully updated",
    "Eliminado exitoso": "Successfully deleted",
    "Creado exitoso": "Successfully created",
    "¿Está seguro?": "Are you sure?",
    "¿Continuar?": "Continue?",
    "¿Desea continuar?": "Do you want to continue?",
    "Esta acción no se puede deshacer": "This action cannot be undone",
    "Acciones": "Actions",
    "Opciones": "Options",
    "Herramientas": "Tools",
    "Menú": "Menu",
    "Más opciones": "More options",
    "Sin opciones": "No options",
    "Última actualización": "Last update",
    "Última modificación": "Last modified",
    "Creado por": "Created by",
    "Modificado por": "Modified by",
    "Fecha de creación": "Creation date",
    "Fecha de modificación": "Modification date",
    "Hora": "Time",
    "Duración": "Duration",
    "Desde": "From",
    "Hasta": "To",
    "Rango": "Range",
    "Período": "Period",
    "Semana": "Week",
    "Mes": "Month",
    "Año": "Year",
    "Hoy": "Today",
    "Ayer": "Yesterday",
    "Mañana": "Tomorrow",
    "Anterior": "Previous",
    "Siguiente": "Next",
    "Primero": "First",
    "Último": "Last",
    "Total de resultados": "Total results",
    "Resultados por página": "Results per page",
    "Página": "Page",
    "de": "of",
    "Mostrando": "Showing",
    "Formato": "Format",
    "Tamaño": "Size",
    "Peso": "Weight",
    "Largo": "Length",
    "Ancho": "Width",
    "Alto": "Height",
    "Color": "Color",
    "Material": "Material",
    "Modelo": "Model",
    "Marca": "Brand",
    "Serie": "Series",
    "Número": "Number",
    "Referencia": "Reference",
    "Observaciones": "Observations",
    "Comentario": "Comment",
    "Nota": "Note",
    "Aviso": "Notice",
    "Sugerencia": "Suggestion",
    "Recomendación": "Recommendation",
    "Instrucciones": "Instructions",
    "Pasos": "Steps",
    "Proceso": "Process",
    "Procedimiento": "Procedure",
    "Método": "Method",
    "Técnica": "Technique",
    "Sistema": "System",
    "Plataforma": "Platform",
    "Aplicación": "Application",
    "Programa": "Program",
    "Software": "Software",
    "Hardware": "Hardware",
    "Dispositivo": "Device",
    "Equipo": "Equipment",
    "Herramienta": "Tool",
    "Recurso": "Resource",
    "Servicio": "Service",
    "Función": "Function",
    "Característica": "Feature",
    "Propiedad": "Property",
    "Atributo": "Attribute",
    "Valor": "Value",
    "Resultado": "Result",
    "Salida": "Output",
    "Entrada": "Input",
    "Parámetro": "Parameter",
    "Variable": "Variable",
    "Constante": "Constant",
    "Dato": "Data",
    "Registro": "Record",
    "Elemento": "Element",
    "Item": "Item",
    "Objeto": "Object",
    "Lista": "List",
    "Tabla": "Table",
    "Gráfico": "Chart",
    "Diagrama": "Diagram",
    "Imagen": "Image",
    "Video": "Video",
    "Audio": "Audio",
    "Texto": "Text",
    "Contenido": "Content",
    "Título": "Title",
    "Subtítulo": "Subtitle",
    "Encabezado": "Header",
    "Pie de página": "Footer",
    "Resumen": "Summary",
    "Detalle": "Detail",
    "Vista": "View",
    "Modo": "Mode",
    "Estilo": "Style",
    "Tema": "Theme",
    "Diseño": "Design",
    "Plantilla": "Template",
    "Formato": "Format",
    # Términos específicos de construcción y pintura
    "Materiales": "Materials",
    "Herramientas": "Tools",
    "Equipos": "Equipment",
    "Trabajador": "Worker",
    "Trabajadores": "Workers",
    "Empleado": "Employee",
    "Empleados": "Employees",
    "Contratista": "Contractor",
    "Subcontratista": "Subcontractor",
    "Proveedor": "Supplier",
    "Proveedores": "Suppliers",
    "Obra": "Construction Site",
    "Sitio": "Site",
    "Ubicación": "Location",
    "Dirección de obra": "Site Address",
    "Inicio de obra": "Start Date",
    "Fin de obra": "End Date",
    "Avance": "Progress",
    "Porcentaje": "Percentage",
    "Completado": "Completed",
    "En curso": "In Progress",
    "Atrasado": "Delayed",
    "A tiempo": "On Time",
    "Terminado": "Finished",
    "Programado": "Scheduled",
    "Realizado": "Completed",
    "Estimado": "Estimated",
    "Real": "Actual",
    "Planificado": "Planned",
    "Ejecutado": "Executed",
    "Nómina": "Payroll",
    "Salario": "Salary",
    "Sueldo": "Wage",
    "Horas": "Hours",
    "Horas trabajadas": "Hours Worked",
    "Horas extras": "Overtime",
    "Turno": "Shift",
    "Asistencia": "Attendance",
    "Falta": "Absence",
    "Permiso": "Leave",
    "Vacaciones": "Vacation",
    # Términos de formularios y validación
    "Requerido": "Required",
    "Obligatorio": "Required",
    "Opcional": "Optional",
    "Válido": "Valid",
    "Inválido": "Invalid",
    "Correcto": "Correct",
    "Incorrecto": "Incorrect",
    "Formato inválido": "Invalid format",
    "Valor inválido": "Invalid value",
    "Fuera de rango": "Out of range",
    "Demasiado corto": "Too short",
    "Demasiado largo": "Too long",
    "Ya existe": "Already exists",
    "No encontrado": "Not found",
    "No disponible": "Not available",
    "No permitido": "Not allowed",
    "Acceso denegado": "Access denied",
    "Sin permisos": "No permissions",
    "Permiso denegado": "Permission denied",
    # Términos de UI y navegación
    "Inicio de sesión": "Login",
    "Cerrar sesión": "Logout",
    "Registrarse": "Register",
    "Iniciar sesión": "Sign In",
    "Olvidé mi contraseña": "Forgot Password",
    "Recuperar contraseña": "Reset Password",
    "Cambiar contraseña": "Change Password",
    "Mi cuenta": "My Account",
    "Mi perfil": "My Profile",
    "Mis proyectos": "My Projects",
    "Mis tareas": "My Tasks",
    "Mis notificaciones": "My Notifications",
    "Panel de control": "Dashboard",
    "Panel principal": "Main Panel",
    "Panel administrativo": "Admin Panel",
    "Escritorio": "Desktop",
    "Móvil": "Mobile",
    "Tablet": "Tablet",
    "Versión": "Version",
    "Actualizar": "Update",
    "Refrescar": "Refresh",
    "Recargar": "Reload",
    "Restaurar": "Restore",
    "Resetear": "Reset",
    "Limpiar": "Clear",
    "Borrar": "Delete",
    "Remover": "Remove",
    "Duplicar": "Duplicate",
    "Copiar": "Copy",
    "Pegar": "Paste",
    "Cortar": "Cut",
    "Deshacer": "Undo",
    "Rehacer": "Redo",
    # Términos de estado y condiciones
    "Aprobado": "Approved",
    "Rechazado": "Rejected",
    "En revisión": "Under Review",
    "Borrador": "Draft",
    "Publicado": "Published",
    "Archivado": "Archived",
    "Bloqueado": "Blocked",
    "Desbloqueado": "Unlocked",
    "Habilitado": "Enabled",
    "Deshabilitado": "Disabled",
    "Visible": "Visible",
    "Oculto": "Hidden",
    "Público": "Public",
    "Privado": "Private",
    "Compartido": "Shared",
    "Individual": "Individual",
    # Términos de tiempo y fechas
    "Fecha de inicio": "Start Date",
    "Fecha de fin": "End Date",
    "Fecha límite": "Deadline",
    "Fecha de entrega": "Delivery Date",
    "Fecha de vencimiento": "Due Date",
    "Fecha de pago": "Payment Date",
    "Fecha de registro": "Registration Date",
    "Fecha y hora": "Date and Time",
    "Hora de inicio": "Start Time",
    "Hora de fin": "End Time",
    "Tiempo estimado": "Estimated Time",
    "Tiempo real": "Actual Time",
    "Tiempo transcurrido": "Elapsed Time",
    "Tiempo restante": "Remaining Time",
    # Términos financieros
    "Subtotal": "Subtotal",
    "Impuestos": "Taxes",
    "Descuento": "Discount",
    "Descuentos": "Discounts",
    "Total final": "Final Total",
    "Gran total": "Grand Total",
    "Saldo": "Balance",
    "Saldo pendiente": "Pending Balance",
    "Pagado": "Paid",
    "Por pagar": "To Pay",
    "Cobrado": "Collected",
    "Por cobrar": "Receivable",
    "Anticipo": "Advance",
    "Crédito": "Credit",
    "Débito": "Debit",
    "Transferencia": "Transfer",
    "Efectivo": "Cash",
    "Tarjeta": "Card",
    "Cheque": "Check",
    "Banco": "Bank",
    "Cuenta bancaria": "Bank Account",
    "Número de cuenta": "Account Number",
    # Términos de documentos y reportes
    "Orden de compra": "Purchase Order",
    "Orden de trabajo": "Work Order",
    "Cotización": "Quote",
    "Estimación": "Estimate",
    "Propuesta": "Proposal",
    "Contrato": "Contract",
    "Acuerdo": "Agreement",
    "Certificado": "Certificate",
    "Comprobante": "Voucher",
    "Boleta": "Receipt",
    "Nota de crédito": "Credit Note",
    "Nota de débito": "Debit Note",
    "Remisión": "Delivery Note",
    "Guía": "Guide",
    "Manual": "Manual",
    "Instructivo": "Instructions",
    "Especificaciones": "Specifications",
    "Requisitos": "Requirements",
    # Términos de comunicación
    "Enviar mensaje": "Send Message",
    "Responder": "Reply",
    "Reenviar": "Forward",
    "Asunto": "Subject",
    "Destinatario": "Recipient",
    "Remitente": "Sender",
    "CC": "CC",
    "CCO": "BCC",
    "Adjunto": "Attachment",
    "Adjuntos": "Attachments",
    "Archivo adjunto": "Attached File",
    # Términos de búsqueda y filtrado
    "Buscar por": "Search by",
    "Filtrar por": "Filter by",
    "Ordenar por": "Sort by",
    "Agrupar por": "Group by",
    "Ascendente": "Ascending",
    "Descendente": "Descending",
    "Alfabético": "Alphabetical",
    "Numérico": "Numerical",
    "Cronológico": "Chronological",
    "Personalizado": "Custom",
    # Términos de confirmación y acciones
    "Aceptar": "Accept",
    "Rechazar": "Reject",
    "Aprobar": "Approve",
    "Denegar": "Deny",
    "Autorizar": "Authorize",
    "Verificar": "Verify",
    "Validar": "Validate",
    "Revisar": "Review",
    "Inspeccionar": "Inspect",
    "Auditar": "Audit",
    "Registrar": "Register",
    "Actualizar datos": "Update Data",
    "Modificar datos": "Modify Data",
    "Cambiar datos": "Change Data",
    "Eliminar datos": "Delete Data",
    "Restaurar datos": "Restore Data",
    # Términos de ayuda y soporte
    "Guía de usuario": "User Guide",
    "Manual de usuario": "User Manual",
    "Preguntas frecuentes": "FAQ",
    "Centro de ayuda": "Help Center",
    "Soporte técnico": "Technical Support",
    "Contactar soporte": "Contact Support",
    "Reportar problema": "Report Issue",
    "Reportar error": "Report Bug",
    "Sugerir mejora": "Suggest Improvement",
    "Enviar feedback": "Send Feedback",
    # Términos adicionales comunes
    "Todos los proyectos": "All Projects",
    "Todos los clientes": "All Clients",
    "Todos los usuarios": "All Users",
    "Todos los estados": "All Statuses",
    "Todas las categorías": "All Categories",
    "Sin categoría": "No Category",
    "Sin proyecto": "No Project",
    "Sin cliente": "No Client",
    "Sin asignar": "Unassigned",
    "No asignado": "Not Assigned",
    "Por asignar": "To Assign",
    "Asignar a": "Assign to",
    "Asignado a": "Assigned to",
    # Términos de prioridad
    "Baja": "Low",
    "Media": "Medium",
    "Alta": "High",
    "Urgente": "Urgent",
    "Crítico": "Critical",
    "Normal": "Normal",
    # Términos de tiempo y actividad
    "Tiempo": "Time",
    "ago": "ago",
    "Actividad reciente": "Recent Activity",
    "No hay actividad reciente": "No recent activity",
    # Términos de grupos y permisos
    "Grupo": "Group",
    "Grupos": "Groups",
    "usuarios": "users",
    "permisos": "permissions",
    "Nombre del Grupo": "Group Name",
    "Actualizar Nombre": "Update Name",
    "No hay usuarios en este grupo": "No users in this group",
    "Gestión de Permisos": "Permission Management",
    "Selecciona los permisos que tendrá este grupo": "Select the permissions this group will have",
    "Crear Grupo": "Create Group",
    "Crear Nuevo Grupo": "Create New Group",
    "Define un grupo para organizar usuarios con permisos similares": "Define a group to organize users with similar permissions",
    # Términos de auditoría y logs
    "Auditoría y Logs": "Audit and Logs",
    "Monitorea la actividad del sistema y cambios realizados": "Monitor system activity and changes made",
    "Monitorea la actividad del sistema y cambios realizados.": "Monitor system activity and changes made.",
    "Ver logs completos": "View complete logs",
    # Términos de checklist
    "Checklist": "Checklist",
    "Verify that all steps have been completed before submitting": "Verify that all steps have been completed before submitting",
    "Mark as Complete": "Mark as Complete",
    # Términos de ejemplos y placeholders
    "Ej": "E.g.",
    "Ej:": "E.g.:",
    "Ejemplo": "Example",
    "Ejemplos": "Examples",
    "Usa un nombre descriptivo que identifique el rol del grupo": "Use a descriptive name that identifies the group role",
    # Términos de facturas
    "Nombre Factura/Proyecto": "Invoice/Project Name",
    "Facturado": "Invoiced",
    "Sin facturar": "Not Invoiced",
    "Factura pendiente": "Pending Invoice",
    # Términos adicionales de UI
    "Ver más detalles": "View more details",
    "Ocultar detalles": "Hide details",
    "Expandir": "Expand",
    "Contraer": "Collapse",
    "Minimizar": "Minimize",
    "Maximizar": "Maximize",
    "Pantalla completa": "Full Screen",
    "Salir de pantalla completa": "Exit Full Screen",
    # Términos de navegación
    "Ir a": "Go to",
    "Regresar": "Return",
    "Continuar": "Continue",
    "Omitir": "Skip",
    "Finalizar": "Finish",
    "Terminar": "End",
    # Términos de validación adicionales
    "Verificado": "Verified",
    "Sin verificar": "Unverified",
    "Confirmado": "Confirmed",
    "Sin confirmar": "Unconfirmed",
    "Revisado": "Reviewed",
    "Sin revisar": "Not Reviewed",
    # Términos de grupos y roles específicos
    "Sugerencias de grupos comunes": "Common group suggestions",
    "Acceso completo al sistema": "Full system access",
    "Gestión de proyectos, tareas y time tracking": "Project, task, and time tracking management",
    "Visualización de sus proyectos y facturas": "View their projects and invoices",
    "Acceso limitado a proyectos específicos": "Limited access to specific projects",
    "Siguiente paso": "Next step",
    "Gestión de Grupos": "Group Management",
    "Administra grupos de usuarios y sus permisos": "Manage user groups and their permissions",
    "Nuevo Grupo": "New Group",
    "Usuarios en este grupo": "Users in this group",
    "Permisos asignados": "Assigned permissions",
    "Editar permisos": "Edit permissions",
    "Usuarios:": "Users:",
    "Sin usuarios asignados": "No assigned users",
    "Grupos Sugeridos": "Suggested Groups",
    "Administradores": "Administrators",
    "Acceso completo a todas las funciones del sistema": "Full access to all system functions",
    "Acceso a proyectos, tareas, time entries y touch-ups": "Access to projects, tasks, time entries and touch-ups",
    "Ver sus proyectos, facturas y documentos": "View their projects, invoices and documents",
    # Términos de acciones específicas
    "Modificar datos del ingreso": "Modify income data",
    "Crear Ingreso": "Create Income",
    "Editar Gasto": "Edit Expense",
    "Editar Ingreso": "Edit Income",
    "Edición no disponible aún": "Editing not yet available",
    # Términos de búsqueda específicos
    "Buscar por nombre, cliente, descripción...": "Search by name, client, description...",
    "Buscar por nombre...": "Search by name...",
    "Buscar proyectos...": "Search projects...",
    "Buscar clientes...": "Search clients...",
    # Términos de paginación y resultados
    "Paginación": "Pagination",
    "No se encontraron resultados que coincidan con tu búsqueda": "No results found matching your search",
    "Comienza creando tu primer registro": "Start by creating your first record",
    "Crear Primer Proyecto": "Create First Project",
    "Crear Primer Gasto": "Create First Expense",
    "Crear Primer Ingreso": "Create First Income",
    # Términos de formularios de proyectos
    "Nombre del Proyecto": "Project Name",
    "Fecha de Inicio": "Start Date",
    "Fecha de Fin": "End Date",
    "Detalles de Pintura": "Paint Details",
    "Colores de Pintura": "Paint Colors",
    # Términos de notas y actividad
    "Actividad reciente:": "Recent activity:",
    "Optional - Not shown to client": "Optional - Not shown to client",
    "Add any notes about this activity (in Spanish, for internal use only)": "Add any notes about this activity (in Spanish, for internal use only)",
    # Términos de roles comunes
    "Ej: Administradores, Empleados, Clientes...": "E.g.: Administrators, Employees, Clients...",
    "Administrador": "Administrator",
    "Supervisor": "Supervisor",
    "Coordinador": "Coordinator",
    "Jefe": "Manager",
    "Gerente": "Manager",
    "Director": "Director",
    "Operador": "Operator",
    "Técnico": "Technician",
    "Asistente": "Assistant",
    "Ayudante": "Helper",
    "Obrero": "Worker",
    "Maestro": "Master",
    "Oficial": "Officer",
    "Aprendiz": "Apprentice",
    # Términos de pintura y construcción específicos
    "Códigos de Pintura": "Paint Codes",
    "Tintes o Acabados": "Tints or Finishes",
    "Número de Habitaciones/Áreas": "Number of Rooms/Areas",
    "Número de Defectos": "Number of Defects",
    "Presupuesto Total": "Total Budget",
    "Presupuesto Materiales": "Materials Budget",
    "Presupuesto Otros": "Other Budget",
    "Notas de Reflexión": "Reflection Notes",
    "Actualizar Proyecto": "Update Project",
    "Colores Aprobados del Proyecto": "Approved Project Colors",
    "Selección de Color": "Color Selection",
    # Términos de usuarios y roles
    "Nombre de usuario": "Username",
    "Apellido": "Last Name",
    "Rol": "Role",
    "Project Manager": "Project Manager",
    "Designer": "Designer",
    "Usuario activo": "Active user",
    "Staff (acceso admin)": "Staff (admin access)",
    "Superusuario (todos los permisos)": "Superuser (all permissions)",
    "Cambiar Contraseña": "Change Password",
    "Nueva contraseña": "New password",
    "Desactivar usuario": "Deactivate user",
    "Activar usuario": "Activate user",
    "¿Estás seguro de eliminar este usuario?": "Are you sure you want to delete this user?",
    "Eliminar usuario": "Delete user",
    "Proyectos asignados": "Assigned projects",
    "Acciones recientes": "Recent actions",
    "No tiene proyectos asignados": "Has no assigned projects",
    "Grupos y Permisos": "Groups and Permissions",
    "No pertenece a ningún grupo": "Does not belong to any group",
    "Actividad Reciente": "Recent Activity",
    "Crear Usuario": "Create User",
    "Crear Nuevo Usuario": "Create New User",
    "Único en el sistema, sin espacios": "Unique in the system, no spaces",
    "Mínimo 8 caracteres": "Minimum 8 characters",
    "usuarios en el sistema": "users in the system",
    "Nuevo Usuario": "New User",
    "Staff": "Staff",
    "Inactivos": "Inactive",
    "Nombre, email, username...": "Name, email, username...",
    "Superusuarios": "Superusers",
    "Contratistas": "Contractors",
    "Fecha Registro": "Registration Date",
    "Superuser": "Superuser",
    "No se encontraron usuarios": "No users found",
    # Términos de Change Orders
    "¿Estás seguro de eliminar este Change Order?": "Are you sure you want to delete this Change Order?",
    "Editar Change Order": "Edit Change Order",
    "Actualice los campos necesarios del change order": "Update the necessary change order fields",
    "Complete la información del change order": "Complete the change order information",
    "-- Seleccionar color aprobado --": "-- Select approved color --",
    # Términos de confirmación y seguridad
    "¿Estás seguro?": "Are you sure?",
    "¿Estás seguro de que deseas continuar?": "Are you sure you want to continue?",
    "Esta acción es irreversible": "This action is irreversible",
    "No se puede deshacer": "Cannot be undone",
    "Confirma esta acción": "Confirm this action",
    # Términos de campos de formulario
    "Campo de texto": "Text field",
    "Campo numérico": "Numeric field",
    "Campo de fecha": "Date field",
    "Campo de hora": "Time field",
    "Seleccione una fecha": "Select a date",
    "Seleccione una hora": "Select a time",
    "Formato de fecha": "Date format",
    "Formato incorrecto": "Incorrect format",
    # Términos de acceso y permisos específicos
    "Información sobre Acceso a Proyectos": "Information about Project Access",
    "El cliente podrá ver el dashboard del proyecto y su progreso": "The client will be able to view the project dashboard and progress",
    "Tendrá permiso para crear solicitudes de cambio (Client Requests)": "Will have permission to create change requests (Client Requests)",
    "Podrá ver y comentar en tareas asignadas": "Will be able to view and comment on assigned tasks",
    "Recibirá notificaciones sobre actualizaciones del proyecto": "Will receive notifications about project updates",
    "Volver al Perfil del Cliente": "Return to Client Profile",
    "Confirmar Eliminación": "Confirm Deletion",
    "Desactivar o Eliminar Cliente": "Deactivate or Delete Client",
    "¡Atención!": "Warning!",
    "Estás a punto de desactivar o eliminar al cliente": "You are about to deactivate or delete the client",
    "Opciones:": "Options:",
    "Desactivar Usuario": "Deactivate User",
    "El usuario no podrá iniciar sesión pero se mantienen todos sus datos": "The user will not be able to log in but all their data will be maintained",
    "Desactivar": "Deactivate",
    "Eliminar Permanentemente": "Delete Permanently",
    "¿Estás seguro? Esta acción es PERMANENTE y NO se puede deshacer.": "Are you sure? This action is PERMANENT and CANNOT be undone.",
    "Resetear Contraseña": "Reset Password",
    "Desactivar/Eliminar": "Deactivate/Delete",
    # Términos de información de usuario
    "Email:": "Email:",
    "Usuario:": "User:",
    "Registrado:": "Registered:",
    "Último acceso:": "Last access:",
    "Nunca": "Never",
    "Estado:": "Status:",
    "Proyectos Asignados": "Assigned Projects",
    "Asignar Nuevo": "Assign New",
    "Permisos": "Permissions",
    "Asignado": "Assigned",
    "Comentar": "Comment",
    "Crear tareas": "Create tasks",
    "¿Remover acceso a este proyecto?": "Remove access to this project?",
    "Este cliente no tiene proyectos asignados": "This client has no assigned projects",
    "Asignar Primer Proyecto": "Assign First Project",
    "Tareas Recientes": "Recent Tasks",
    "Sin tareas recientes": "No recent tasks",
    # Términos de creación y edición de clientes
    "Crear Nuevo Cliente": "Create New Client",
    "Editar Cliente": "Edit Client",
    "Se usará como nombre de usuario": "Will be used as username",
    "El cliente recibirá un correo con sus credenciales de acceso": "The client will receive an email with their access credentials",
    "Los usuarios inactivos no pueden iniciar sesión": "Inactive users cannot log in",
    "Crear Cliente": "Create Client",
    "Se generará automáticamente una contraseña temporal segura": "A secure temporary password will be automatically generated",
    "Recuerda asignar proyectos al cliente después de crearlo": "Remember to assign projects to the client after creating it",
    "Nombre, email, usuario...": "Name, email, user...",
    "Primera": "First",
    "Última": "Last",
    "No hay clientes registrados": "No clients registered",
    "Comienza creando tu primer cliente": "Start by creating your first client",
    "Crear Primer Cliente": "Create First Client",
    "Estás a punto de establecer una nueva contraseña para": "You are about to set a new password for",
    # Términos adicionales de UI
    "Ver perfil": "View profile",
    "Ver detalles completos": "View full details",
    "Información completa": "Full information",
    "Información resumida": "Summary information",
    "Datos personales": "Personal data",
    "Datos del sistema": "System data",
    "Configuración de usuario": "User settings",
    "Preferencias": "Preferences",
    # Términos de planificación diaria y SOPs
    "Plan Info": "Plan Info",
    "Created by:": "Created by:",
    "Created:": "Created:",
    "Deadline:": "Deadline:",
    "Approved by:": "Approved by:",
    "Approved:": "Approved:",
    "Activity Template (SOP)": "Activity Template (SOP)",
    "(optional)": "(optional)",
    "Select SOP template": "Select SOP template",
    "Link to Schedule Item": "Link to Schedule Item",
    "Not linked to schedule": "Not linked to schedule",
    "Activity Title": "Activity Title",
    "Estimated Hours": "Estimated Hours",
    "Assign Employees": "Assign Employees",
    "Hold Ctrl/Cmd to select multiple employees": "Hold Ctrl/Cmd to select multiple employees",
    "Daily Planning Dashboard": "Daily Planning Dashboard",
    "Overdue Plans!": "Overdue Plans!",
    "These plans are past their 5pm deadline:": "These plans are past their 5pm deadline:",
    "Complete Now": "Complete Now",
    "Create New Daily Plan": "Create New Daily Plan",
    "Select Project": "Select Project",
    "Choose Project": "Choose Project",
    "Plan Date": "Plan Date",
    "Create Plan": "Create Plan",
    "Today's Plans": "Today's Plans",
    "Skipped": "Skipped",
    "activities": "activities",
    "Edit Plan": "Edit Plan",
    "Project": "Project",
    "Status": "Status",
    "Created By": "Created By",
    "No plans for today yet.": "No plans for today yet.",
    "Tap the + button to create one": "Tap the + button to create one",
    "Recent Plans": "Recent Plans",
    "View": "View",
    "Date": "Date",
    "View/Edit": "View/Edit",
    "No recent plans.": "No recent plans.",
    "SOP Library": "SOP Library",
    "Employee View": "Employee View",
    "Create Daily Plan": "Create Daily Plan",
    # Términos de reportes y daños
    "Eliminar Reporte": "Delete Report",
    "¿Estás seguro de eliminar este reporte?": "Are you sure you want to delete this report?",
    "Severidad": "Severity",
    "Editar Reporte": "Edit Report",
    "Nuevo Reporte": "New Report",
    "Costo Estimado": "Estimated Cost",
    "Plano": "Floor Plan",
    "Pin": "Pin",
    "Touch-up Relacionado": "Related Touch-up",
    # Términos adicionales de estado
    "En espera": "Waiting",
    "Esperando": "Waiting",
    "Pausado": "Paused",
    "Detenido": "Stopped",
    "Reanudado": "Resumed",
    "Iniciado": "Started",
    "No iniciado": "Not started",
    "Sin iniciar": "Not started",
    "Por iniciar": "To start",
    # Términos de dashboard y reportes
    "Paid": "Paid",
    "Review Payroll": "Review Payroll",
    "Time Recorded": "Time Recorded",
    "This Week": "This Week",
    "Income vs Expenses": "Income vs Expenses",
    "Last 30 days": "Last 30 days",
    "Alerts Distribution": "Alerts Distribution",
    "COs": "COs",
    "Planning": "Planning",
    "Select a project first": "Select a project first",
    "Minutes": "Minutes",
    "Profit": "Profit",
    "Active Projects": "Active Projects",
    "Completed Projects": "Completed Projects",
    "My Projects": "My Projects",
    "Progress": "Progress",
    "Recent Gallery": "Recent Gallery",
    "View all photos": "View all photos",
    "No photos available yet": "No photos available yet",
    "Total Invoiced": "Total Invoiced",
    "Balance Due": "Balance Due",
    "No invoices yet": "No invoices yet",
    "Next Event": "Next Event",
    "No upcoming events scheduled": "No upcoming events scheduled",
    "My Requests": "My Requests",
    "No requests yet": "No requests yet",
    "New Request": "New Request",
    "Details": "Details",
    "Gallery": "Gallery",
    "Requests": "Requests",
    "No projects assigned": "No projects assigned",
    "Contact your Project Manager for more information": "Contact your Project Manager for more information",
    "Consolidated view of projects, color samples, and plans": "Consolidated view of projects, color samples, and plans",
    "Client": "Client",
    "Recent Color Samples": "Recent Color Samples",
    "No color samples available": "No color samples available",
    "Recent Floor Plans": "Recent Floor Plans",
    "No floor plans available": "No floor plans available",
    "Activity": "Activity",
    "Start": "Start",
    "End": "End",
    "No upcoming schedule": "No upcoming schedule",
    "Hello": "Hello",
    "Not Linked to Employee": "Not Linked to Employee",
    "Please ask your admin to assign you to an employee profile": "Please ask your admin to assign you to an employee profile",
    "Working on": "Working on",
    "Clock in": "Clock in",
    "Clock Out": "Clock Out",
    "Clock In": "Clock In",
    "Notes": "Notes",
    # Términos de galería y multimedia
    "Galería": "Gallery",
    "Album": "Album",
    "Álbum": "Album",
    "Álbumes": "Albums",
    "Fotografía": "Photography",
    "Imagen": "Image",
    "Imágenes": "Images",
    "Multimedia": "Multimedia",
    "Subir foto": "Upload photo",
    "Subir imagen": "Upload image",
    "Eliminar foto": "Delete photo",
    "Ver foto": "View photo",
    "Descargar foto": "Download photo",
    # Términos de tiempo y reloj
    "Reloj": "Clock",
    "Entrada": "Entry",
    "Salida": "Exit",
    "Registro de tiempo": "Time record",
    "Marcaje": "Timestamp",
    "Hora de entrada": "Clock in time",
    "Hora de salida": "Clock out time",
    # Términos de evaluación de desempeño
    "Attitude & Professionalism": "Attitude & Professionalism",
    "Rate the employee's attitude, reliability, and work ethic": "Rate the employee's attitude, reliability, and work ethic",
    "Teamwork & Communication": "Teamwork & Communication",
    "Rate collaboration skills and communication with team": "Rate collaboration skills and communication with team",
    "Bonus Amount": "Bonus Amount",
    "Bonus Justification / Notes": "Bonus Justification / Notes",
    "Save Performance Review": "Save Performance Review",
    "How Overall Score is Calculated": "How Overall Score is Calculated",
    "Quality Rating": "Quality Rating",
    "Attitude Rating": "Attitude Rating",
    "Attendance": "Attendance",
    "Poor": "Poor",
    "Fair": "Fair",
    "Good": "Good",
    "Very Good": "Very Good",
    "Excellent": "Excellent",
    "Employee Performance Reviews": "Employee Performance Reviews",
    "Annual performance metrics for bonus evaluation": "Annual performance metrics for bonus evaluation",
    "Review Year": "Review Year",
    "Overall Score": "Overall Score",
    "Hours Worked": "Hours Worked",
    "Quality": "Quality",
    "Attitude": "Attitude",
    "Teamwork": "Teamwork",
    "Bonus": "Bonus",
    "Edit Performance Review": "Edit Performance Review",
    "No Performance Data Yet": "No Performance Data Yet",
    "Performance metrics will appear as employees work throughout the year": "Performance metrics will appear as employees work throughout the year",
    "Team Summary": "Team Summary",
    "Employees Reviewed": "Employees Reviewed",
    "With Ratings": "With Ratings",
    "Avg Bonus": "Avg Bonus",
    "Bonuses Paid": "Bonuses Paid",
    # Términos de gastos y finanzas
    "¿Seguro que deseas eliminar este gasto?": "Are you sure you want to delete this expense?",
    "Edit Expense": "Edit Expense",
    "Additional notes or details": "Additional notes or details",
    "Current file": "Current file",
    "View receipt": "View receipt",
    "e.g., Office supplies, Equipment rental": "e.g., Office supplies, Equipment rental",
    "Save Expense": "Save Expense",
    "Executive overview of business financial health": "Executive overview of business financial health",
    "YTD Revenue": "YTD Revenue",
    "From paid invoices": "From paid invoices",
    "YTD Expenses": "YTD Expenses",
    "All expenses this year": "All expenses this year",
    "Profit Margin": "Profit Margin",
    "Target: 25%%": "Target: 25%%",
    "Outstanding AR": "Outstanding AR",
    "Unpaid invoices": "Unpaid invoices",
    "Cash Flow This Month": "Cash Flow This Month",
    # Términos adicionales de calificación
    "Calificación": "Rating",
    "Puntaje": "Score",
    "Puntuación": "Score",
    "Evaluación": "Evaluation",
    "Rendimiento": "Performance",
    "Desempeño": "Performance",
    "Productividad": "Productivity",
    "Eficiencia": "Efficiency",
    "Efectividad": "Effectiveness",
    "Calidad de trabajo": "Work quality",
    "Trabajo en equipo": "Teamwork",
    "Comunicación": "Communication",
    "Liderazgo": "Leadership",
    "Iniciativa": "Initiative",
    "Creatividad": "Creativity",
    "Responsabilidad": "Responsibility",
    "Puntualidad": "Punctuality",
    "Asistencia": "Attendance",
    "Actitud": "Attitude",
    "Compromiso": "Commitment",
    "Dedicación": "Dedication",
    "Motivación": "Motivation",
    "Mejora": "Improvement",
    "Fortalezas": "Strengths",
    "Debilidades": "Weaknesses",
    "Oportunidades": "Opportunities",
    "Amenazas": "Threats",
    # Términos de colores y proyectos
    "Seleccione un color aprobado para este proyecto": "Select an approved color for this project",
    "Este proyecto no tiene colores aprobados.": "This project has no approved colors.",
    "Puede usar el selector de color manual a continuación.": "You can use the manual color picker below.",
    "Color (Hex)": "Color (Hex)",
    "Clic para seleccionar color": "Click to select color",
    "Color (Hex) - Manual": "Color (Hex) - Manual",
    "Color:": "Color:",
    "Delete Color Sample": "Delete Color Sample",
    "Are you sure you want to delete this color sample?": "Are you sure you want to delete this color sample?",
    "Projects": "Projects",
    "View Project": "View Project",
    "Invoices": "Invoices",
    "Project Overview": "Project Overview",
    "Project summary will appear here": "Project summary will appear here",
    "Budget per Project": "Budget per Project",
    "Project Event Calendar": "Project Event Calendar",
    "Projects with Alerts": "Projects with Alerts",
    "Tasks Pending Today": "Tasks Pending Today",
    "Colors": "Colors",
    "No active projects": "No active projects",
    "Tasks Completed": "Tasks Completed",
    "Projects Over Budget": "Projects Over Budget",
    "Profit by Project (Top 10 Active)": "Profit by Project (Top 10 Active)",
    "Export Invoices": "Export Invoices",
    "e.g., Payment for services, Project deposit": "e.g., Payment for services, Project deposit",
    "Invoice Aging Report": "Invoice Aging Report",
    "Outstanding invoices by age": "Outstanding invoices by age",
    "invoices": "invoices",
    "No invoices in this bucket": "No invoices in this bucket",
    "Smart Invoice Builder": "Smart Invoice Builder",
    # Términos adicionales de construcción
    "Muestra": "Sample",
    "Muestras": "Samples",
    "Muestra de color": "Color sample",
    "Muestras de color": "Color samples",
    "Selector de color": "Color picker",
    "Paleta de colores": "Color palette",
    "Gama de colores": "Color range",
    "Tono": "Tone",
    "Tonalidad": "Shade",
    "Matiz": "Hue",
    "Saturación": "Saturation",
    "Brillo": "Brightness",
    "Transparencia": "Transparency",
    "Opacidad": "Opacity",
    # Términos de empleados y productividad
    "All employees": "All employees",
    "Assigned to COs": "Assigned to COs",
    "Target: 80%%": "Target: 80%%",
    "Productivity Trend": "Productivity Trend",
    "Top 10 Performers": "Top 10 Performers",
    "Highest productivity rates": "Highest productivity rates",
    "No data available": "No data available",
    "Need Support": "Need Support",
    "Employees with lower productivity": "Employees with lower productivity",
    "Needs training": "Needs training",
    "All employees performing well!": "All employees performing well!",
    "Performance Reviews": "Performance Reviews",
    "Export Time Data": "Export Time Data",
    # Términos de eliminación y confirmación de proyectos
    "Confirmar Eliminación de Proyecto": "Confirm Project Deletion",
    "¡ADVERTENCIA!": "WARNING!",
    "Estás a punto de eliminar PERMANENTEMENTE el proyecto": "You are about to PERMANENTLY delete the project",
    "Información del Proyecto": "Project Information",
    "Nombre:": "Name:",
    "Cliente:": "Client:",
    "Dirección:": "Address:",
    "Fecha de inicio:": "Start date:",
    "Datos Asociados que se Eliminarán": "Associated Data to be Deleted",
    "Time Entries": "Time Entries",
    "No se puede eliminar este proyecto": "This project cannot be deleted",
    "Alternativas Recomendadas": "Recommended Alternatives",
    "Archiva el proyecto para sacarlo de las vistas principales": "Archive the project to remove it from main views",
    "Exporta los datos del proyecto antes de considerar su eliminación": "Export project data before considering deletion",
    "Esta acción NO se puede deshacer": "This action CANNOT be undone",
    "Se eliminarán todas las tareas asociadas": "All associated tasks will be deleted",
    "Se perderán todos los archivos y documentos del proyecto": "All project files and documents will be lost",
    "Los accesos de clientes a este proyecto serán revocados": "Client access to this project will be revoked",
    "SÍ, ELIMINAR PROYECTO PERMANENTEMENTE": "YES, DELETE PROJECT PERMANENTLY",
    "Marcar como Completado": "Mark as Completed",
    "Crear Nuevo Proyecto": "Create New Project",
    "Dejar en blanco para proyectos activos": "Leave blank for active projects",
    "Especificaciones Técnicas": "Technical Specifications",
    "New Project": "New Project",
    "Project Name": "Project Name",
    "No projects yet": "No projects yet",
    "Create your first project to get started": "Create your first project to get started",
    "Create Project": "Create Project",
    "Contact your administrator to create projects": "Contact your administrator to create projects",
    # Términos de eventos
    "Crear evento": "Create event",
    "Fin": "End",
    "Sin eventos programados": "No scheduled events",
    # Términos de RFI (Request for Information)
    "Delete RFI": "Delete RFI",
    "Are you sure you want to delete this RFI? This action cannot be undone.": "Are you sure you want to delete this RFI? This action cannot be undone.",
    "Number": "Number",
    "Question": "Question",
    "Edit RFI": "Edit RFI",
    "RFI": "RFI",
    "RFIs": "RFIs",
    # Términos de SOPs y procedimientos
    "Checklist Steps": "Checklist Steps",
    "Add step...": "Add step...",
    "Add material...": "Add material...",
    "Tools": "Tools",
    "Add tool...": "Add tool...",
    "Common Errors": "Common Errors",
    "Reference Photos / Files": "Reference Photos / Files",
    "Existing files:": "Existing files:",
    "Upload photos, PDFs, or documents (multiple files allowed)": "Upload photos, PDFs, or documents (multiple files allowed)",
    "Video or Resource Link": "Video or Resource Link",
    "Active": "Active",
    "Save SOP": "Save SOP",
    "Browse Standard Operating Procedures and Activity Templates": "Browse Standard Operating Procedures and Activity Templates",
    "Create New SOP": "Create New SOP",
    "All Categories": "All Categories",
    "Search": "Search",
    "Search by name, description, or tips...": "Search by name, description, or tips...",
    "Steps": "Steps",
    "Show/Hide Steps": "Show/Hide Steps",
    "Created by": "Created by",
    "Show/Hide Tools": "Show/Hide Tools",
    "Common Errors:": "Common Errors:",
    "Watch Video Tutorial": "Watch Video Tutorial",
    "Reference Files": "Reference Files",
    "No SOPs found": "No SOPs found",
    "Try adjusting your search filters": "Try adjusting your search filters",
    "Back to Planning Dashboard": "Back to Planning Dashboard",
    # Términos de tareas
    "Eliminar Tarea": "Delete Task",
    "¿Estás seguro de que deseas eliminar la tarea?": "Are you sure you want to delete the task?",
    "Sí, eliminar": "Yes, delete",
    "Sin descripción": "No description",
    "Creado": "Created",
    "Actualizado": "Updated",
    "Prioridad": "Priority",
    "Tiempo trabajado": "Time worked",
    "Registra el tiempo que trabajas en esta tarea": "Track the time you work on this task",
    "Detener": "Stop",
    "Seguimiento activo desde": "Active tracking since",
    "Sin seguimiento activo": "No active tracking",
    "Seguimiento activo": "Active tracking",
    "Error al iniciar seguimiento": "Error starting tracking",
    "Error al detener seguimiento": "Error stopping tracking",
    "Edit Task": "Edit Task",
    "Enter task title": "Enter task title",
    "Enter task description": "Enter task description",
    "Select assignee": "Select assignee",
    "Current image": "Current image",
    "Options": "Options",
    "Save Task": "Save Task",
    "Tareas del Proyecto": "Project Tasks",
    # Términos adicionales de seguimiento
    "Seguimiento": "Tracking",
    "Rastreo": "Tracking",
    "Monitoreo": "Monitoring",
    "Cronómetro": "Timer",
    "Temporizador": "Timer",
    "Contador": "Counter",
    "Medidor": "Meter",
    # Términos de Change Orders y fotos
    "Editar Change Order #%(co_id)s": "Edit Change Order #%(co_id)s",
    "Escriba un código hex manualmente (ej: #FF5733)": "Enter a hex code manually (e.g., #FF5733)",
    "Código de Referencia o Material": "Reference Code or Material",
    "Cómo subir fotos:": "How to upload photos:",
    "Haga clic en el área azul para seleccionar fotos": "Click on the blue area to select photos",
    "Verá miniaturas de las fotos seleccionadas": "You will see thumbnails of the selected photos",
    "Opcional: Agregue descripciones en los campos de texto": "Optional: Add descriptions in the text fields",
    "Fotos Existentes:": "Existing Photos:",
    "Haga clic para subir fotos": "Click to upload photos",
    "fotos": "photos",
    "Crear Change Order": "Create Change Order",
    "Algún archivo supera el límite de 10MB y fue omitido.": "Some file exceeds the 10MB limit and was skipped.",
    "foto": "photo",
    "Descripción...": "Description...",
    "¿Eliminar esta foto?": "Delete this photo?",
    "Escriba el texto:": "Enter text:",
    "¿Eliminar todas las anotaciones?": "Delete all annotations?",
    "Anotaciones guardadas exitosamente": "Annotations saved successfully",
    "Error al guardar anotaciones": "Error saving annotations",
    "Anotaciones guardadas. Se aplicarán al enviar el formulario.": "Annotations saved. They will be applied when submitting the form.",
    "¿Eliminar esta foto permanentemente?": "Delete this photo permanently?",
    "Foto eliminada exitosamente": "Photo deleted successfully",
    "Error al eliminar foto": "Error deleting photo",
    "O escriba un código hex manualmente (ej: #FF5733)": "Or enter a hex code manually (e.g., #FF5733)",
    "0 fotos": "0 photos",
    "Dibujar": "Draw",
    "Limpiar Todo": "Clear All",
    "Rojo": "Red",
    "Azul": "Blue",
    "Verde": "Green",
    "Amarillo": "Yellow",
    "Negro": "Black",
    "Blanco": "White",
    # Términos de asignación de clientes
    "Selecciona los proyectos a los que este cliente tendrá acceso": "Select the projects this client will have access to",
    "Proyectos Disponibles": "Available Projects",
    "Cliente del Proyecto": "Project Client",
    "Acción": "Action",
    "Asignar": "Assign",
    "No hay proyectos disponibles": "No projects available",
    "Este cliente ya tiene acceso a todos los proyectos existentes": "This client already has access to all existing projects",
    "Importante:": "Important:",
    "La contraseña actual del usuario será reemplazada": "The user's current password will be replaced",
    "Se enviará un email al cliente con la nueva contraseña": "An email will be sent to the client with the new password",
    "El usuario podrá cambiar su contraseña después de iniciar sesión": "The user will be able to change their password after logging in",
    "Consejos de Seguridad": "Security Tips",
    "Usa contraseñas largas y únicas para cada usuario": "Use long and unique passwords for each user",
    "Combina letras mayúsculas, minúsculas, números y símbolos": "Combine uppercase, lowercase, numbers and symbols",
    # Términos de colores
    "Rojo": "Red",
    "Azul": "Blue",
    "Verde": "Green",
    "Amarillo": "Yellow",
    "Naranja": "Orange",
    "Morado": "Purple",
    "Rosa": "Pink",
    "Marrón": "Brown",
    "Gris": "Gray",
    "Blanco": "White",
    "Negro": "Black",
    "Dorado": "Gold",
    "Plateado": "Silver",
    "Turquesa": "Turquoise",
    "Violeta": "Violet",
    "Beige": "Beige",
    "Crema": "Cream",
    # Términos de dashboard y métricas
    "Payments": "Payments",
    "Upcoming Events": "Upcoming Events",
    "days": "days",
    "Upcoming events will appear here": "Upcoming events will appear here",
    "Net Profit": "Net Profit",
    "Income vs Expense": "Income vs Expense",
    "Expense": "Expense",
    "Labor": "Labor",
    "Materials": "Materials",
    "Other": "Other",
    "Today": "Today",
    "Month": "Month",
    "Week": "Week",
    "Day": "Day",
    "List": "List",
    "Abrir Panel": "Open Panel",
    "Acciones Rápidas": "Quick Actions",
    "Nuevo Gasto": "New Expense",
    "Nuevo Ingreso": "New Income",
    "Unassigned Time": "Unassigned Time",
    "sin asignar": "unassigned",
    "Assign now": "Assign now",
    "Assign": "Assign",
    "Client Requests": "Client Requests",
    "Pending approval": "Pending approval",
    "Review": "Review",
    "Awaiting approval": "Awaiting approval",
    "Approve": "Approve",
    "View payments": "View payments",
    "Total Income": "Total Income",
    "Total Expenses": "Total Expenses",
    "Pending Approvals": "Pending Approvals",
    "Convert": "Convert",
    "No pending approvals": "No pending approvals",
    "Payroll & Time": "Payroll & Time",
    "Latest Payroll Period": "Latest Payroll Period",
    "optional": "optional",
    "My Assigned Touch-Ups": "My Assigned Touch-Ups",
    "What to Do Today": "What to Do Today",
    "Complete": "Complete",
    "Morning Plan": "Morning Plan",
    "Notifications": "Notifications",
    "Recent Entries": "Recent Entries",
    "Hours": "Hours",
    "No recent records": "No recent records",
    "Open Issues": "Open Issues",
    "Open RFIs": "Open RFIs",
    "Damages": "Damages",
    "Plans": "Plans",
    "Active Issues": "Active Issues",
    # Términos de periodos de tiempo
    "Diario": "Daily",
    "Semanal": "Weekly",
    "Mensual": "Monthly",
    "Anual": "Annual",
    "Trimestral": "Quarterly",
    "Bimestral": "Bimonthly",
    "Quincenal": "Biweekly",
    "Periodo": "Period",
    "Ciclo": "Cycle",
    # Términos de stock e inventario
    "Alertas de Stock Bajo": "Low Stock Alerts",
    "Artículo": "Item",
    "Stock Actual": "Current Stock",
    "SIN STOCK": "OUT OF STOCK",
    "BAJO": "LOW",
    "¡Excelente! No hay artículos con stock bajo en este momento.": "Excellent! There are no low stock items at this time.",
    # Términos de facturación y reportes
    "Total Outstanding": "Total Outstanding",
    "Across all aging buckets": "Across all aging buckets",
    "Export Report": "Export Report",
    "Current (0-30 days)": "Current (0-30 days)",
    "31-60 days": "31-60 days",
    "61-90 days": "61-90 days",
    "Over 90 days": "Over 90 days",
    "Back": "Back",
    "Base Contract": "Base Contract",
    "Estimate": "Estimate",
    "Estimate v": "Estimate v",
    "Markups": "Markups",
    "Progressive Billing": "Progressive Billing",
    "Code": "Code",
    "Direct Cost": "Direct Cost",
    "Billed": "Billed",
    "Remaining": "Remaining",
    "%% New": "%% New",
    "Completely billed": "Completely billed",
    "No approved estimate for this project": "No approved estimate for this project",
    "hrs": "hrs",
    "hr": "hr",
    "Contrato Base": "Base Contract",
    "T&M General": "T&M General",
    "T&M (COs)": "T&M (COs)",
    "TOTAL": "TOTAL",
    # Términos de issues y alertas
    "Delete Issue": "Delete Issue",
    "Title": "Title",
    "Severity": "Severity",
    "Yes, delete": "Yes, delete",
    "Edit Issue": "Edit Issue",
    "Save Issue": "Save Issue",
    "Crear alerta/daño": "Create alert/damage",
    # Términos de login
    "Welcome Back": "Welcome Back",
    "Sign in to continue to Kibray": "Sign in to continue to Kibray",
    "Please correct the errors below": "Please correct the errors below",
    "Username": "Username",
    "Password": "Password",
    "Sign In": "Sign In",
    "Language": "Language",
    "English": "English",
    "Español": "Español",
    "Signing in...": "Signing in...",
    "Employee performance and efficiency metrics": "Employee performance and efficiency metrics",
    # Términos adicionales de inventario
    "Inventario": "Inventory",
    "Existencias": "Stock",
    "Disponible": "Available",
    "Agotado": "Out of stock",
    "Reservado": "Reserved",
    "En tránsito": "In transit",
    "Almacén": "Warehouse",
    "Bodega": "Storage",
    "Depósito": "Deposit",
    # Términos finales de SOPs, tareas y formularios
    "Create SOP": "Create SOP",
    "Name": "Name",
    "Tips": "Tips",
    "Crear nueva tarea": "Create new task",
    "No hay tareas todavía.": "No tasks yet.",
    "Mis Tareas": "My Tasks",
    "ID": "ID",
    "Touch‑ups": "Touch‑ups",
    "Aún no tienes tareas asignadas": "You don't have any assigned tasks yet",
    "Cuando tu PM te asigne tareas aparecerán aquí.": "When your PM assigns you tasks they will appear here.",
    "Delete Time Entry": "Delete Time Entry",
    "Employee": "Employee",
    "Edit Time Entry": "Edit Time Entry",
    "Additional details about work performed": "Additional details about work performed",
    "Save": "Save",
    "Save and Add Another": "Save and Add Another",
    "Save & Add": "Save & Add",
    # Mensajes de validación y errores
    "No tienes permisos para acceder a esta sección.": "You don't have permission to access this section.",
    "Usuario actualizado correctamente.": "User updated successfully.",
    "Contraseña cambiada correctamente.": "Password changed successfully.",
    "activado": "activated",
    "desactivado": "deactivated",
    "Usuario {status}.": "User {status}.",
    "Ya existe un usuario con ese nombre.": "A user with that name already exists.",
    "Debes proporcionar una contraseña.": "You must provide a password.",
    "Usuario creado correctamente.": "User created successfully.",
    "No puedes eliminarte a ti mismo.": "You cannot delete yourself.",
    "No puedes eliminar un superusuario.": "You cannot delete a superuser.",
    "Usuario '{username}' eliminado.": "User '{username}' deleted.",
    "Permisos actualizados.": "Permissions updated.",
    "Grupo actualizado.": "Group updated.",
    "Ya existe un grupo con ese nombre.": "A group with that name already exists.",
    "Grupo creado correctamente.": "Group created successfully.",
    "Modelo no encontrado.": "Model not found.",
    "El proyecto es obligatorio.": "Project is required.",
    "El nombre del proyecto/factura es obligatorio.": "Project/invoice name is required.",
    "El monto debe ser positivo.": "Amount must be positive.",
    "La fecha es obligatoria.": "Date is required.",
    "La categoría es obligatoria.": "Category is required.",
    "Monto inválido.": "Invalid amount.",
    "Gasto eliminado": "Expense deleted",
    "El método de pago es obligatorio.": "Payment method is required.",
    "Método de pago inválido.": "Invalid payment method.",
    "Ingreso eliminado": "Income deleted",
    # Términos adicionales de validación
    "Campo obligatorio": "Required field",
    "Valor inválido": "Invalid value",
    "Seleccione una opción válida": "Select a valid option",
    "Este campo no puede estar vacío": "This field cannot be empty",
    "Formato no válido": "Invalid format",
    "Entrada no válida": "Invalid entry",
    # Navegación y acciones rápidas
    "Delete": "Delete",
    "Logout": "Logout",
    "Login": "Login",
    "Edit": "Edit",
    "No photos yet": "No photos yet",
    "Team": "Team",
    "Income": "Income",
    "Expenses": "Expenses",
    "Daily Logs": "Daily Logs",
    "Crear nuevo log": "Create new log",
    "Progreso:": "Progress:",
    "Retrasos:": "Delays:",
    "Sin daily logs": "No daily logs",
    "Edit Daily Plan": "Edit Daily Plan",
    "Daily Planning": "Daily Planning",
    "Status:": "Status:",
    "Draft": "Draft",
    "Submitted": "Submitted",
    "Approved": "Approved",
    "This plan is overdue! Deadline was:": "This plan is overdue! Deadline was:",
    "Check materials for all activities": "Check materials for all activities",
    "Activities": "Activities",
    "Add Activity": "Add Activity",
    "Assigned:": "Assigned:",
    "No one assigned yet": "No one assigned yet",
    "Materials:": "Materials:",
    "Shortage": "Shortage",
    "OK": "OK",
    "Shortage!": "Shortage!",
    "complete": "complete",
    "Delete this activity?": "Delete this activity?",
    "No activities added yet. Click 'Add Activity' to start.": "No activities added yet. Click 'Add Activity' to start.",
    "Actions": "Actions",
    "Submit Plan": "Submit Plan",
    "Add at least one activity before submitting": "Add at least one activity before submitting",
    "Quick Links": "Quick Links",
    "Browse SOPs": "Browse SOPs",
    "Change Order Relacionado": "Related Change Order",
    "Welcome": "Welcome",
    "Quick Actions": "Quick Actions",
    "Payroll": "Payroll",
    "Add Event": "Add Event",
    "Add Expense": "Add Expense",
    "Add Income": "Add Income",
    "Register Hours": "Register Hours",
    # Frases largas de instrucciones
    "Para hacer match con madera, metal u otro material (ej: \\": "To match wood, metal or other material (eg: \\",
    "Opcional: Haga clic en \\": "Optional: Click on \\",
    "seleccionadas - Haga clic en \\": "selected - Click on \\",
    "Evita contraseñas fáciles de adivinar como fechas o nombres": "Avoid easy-to-guess passwords like dates or names",
    "Recomienda al cliente usar un gestor de contraseñas": "Recommend the client use a password manager",
    # Dashboard y métricas diarias
    "No active issues": "No active issues",
    "Hours Today": "Hours Today",
    "My Daily Plan": "My Daily Plan",
    "Good Morning": "Good Morning",
    "Your work plan for": "Your work plan for",
    "SOP": "SOP",
    "Steps to follow:": "Steps to follow:",
    "Tips:": "Tips:",
    "Estimated time:": "Estimated time:",
    "hours": "hours",
    "Team assigned": "Team assigned",
    "Materials needed": "Materials needed",
    "Warning: Material shortage detected. Contact your supervisor.": "Warning: Material shortage detected. Contact your supervisor.",
    "Activity completed!": "Activity completed!",
    "No activities assigned for today": "No activities assigned for today",
    "Enjoy your day off or check with your supervisor!": "Enjoy your day off or check with your supervisor!",
    # Performance Review
    "Performance Review": "Performance Review",
    "Overall Performance Score": "Overall Performance Score",
    "Exceptional Performance": "Exceptional Performance",
    "Strong Performance": "Strong Performance",
    "Satisfactory Performance": "Satisfactory Performance",
    "Needs Improvement": "Needs Improvement",
    "Calculated Metrics": "Calculated Metrics",
    "Total Hours Worked": "Total Hours Worked",
    "Billable Hours": "Billable Hours",
    "Productivity Rate": "Productivity Rate",
    "Days Worked": "Days Worked",
    "Days Late": "Days Late",
    "Defects Created": "Defects Created",
    "Manual Ratings": "Manual Ratings",
    "Quality of Work": "Quality of Work",
    "Rate the overall quality and attention to detail": "Rate the overall quality and attention to detail",
    # Finanzas y reportes
    "Income minus expenses": "Income minus expenses",
    "Budget": "Budget",
    "Actual": "Actual",
    "Variance": "Variance",
    "%%": "%%",
    "Revenue Trend (Last 12 Months)": "Revenue Trend (Last 12 Months)",
    "Expenses Breakdown": "Expenses Breakdown",
    "Aging Report": "Aging Report",
    "Export Expenses": "Export Expenses",
    "Planos": "Plans",
    "Eliminar Plano": "Delete Plan",
    "¿Estás seguro de eliminar este plano?": "Are you sure you want to delete this plan?",
    "Nivel": "Level",
    "Eliminar Ingreso": "Delete Income",
    "¿Seguro que deseas eliminar este ingreso?": "Are you sure you want to delete this income?",
    # Más acciones y formularios
    "Edit Income": "Edit Income",
    "View file": "View file",
    "Save Income": "Save Income",
    "Start Date": "Start Date",
    "End Date": "End Date",
    "Reset": "Reset",
    "Save RFI": "Save RFI",
    "Delete Risk": "Delete Risk",
    "Probability": "Probability",
    "Impact": "Impact",
    "Risk Score": "Risk Score",
    "Edit Risk": "Edit Risk",
    "Save Risk": "Save Risk",
    "¿Está seguro de que desea eliminar la categoría": "Are you sure you want to delete the category",
    "Edit Event": "Edit Event",
    "Enter event title": "Enter event title",
    "Save Event": "Save Event",
    # Generador de Cronograma/Schedule
    "Generador de Cronograma": "Schedule Generator",
    "Cronograma del Proyecto": "Project Schedule",
    "Vista de timeline con categorías, ítems y duración visual.": "Timeline view with categories, items and visual duration.",
    "Ítem": "Item",
    "Estimado aprobado": "Approved estimate",
    "¿Generar cronograma automáticamente?": "Generate schedule automatically?",
    "Generar": "Generate",
    "No hay categorías ni ítems todavía.": "No categories or items yet.",
    "Usa 'Generar' para comenzar desde el estimado aprobado.": "Use 'Generate' to start from the approved estimate.",
    "Nuevo Ítem": "New Item",
    "%% Progreso": "%% Progress",
    "Orden": "Order",
    "Cost Code": "Cost Code",
    "Budget Line": "Budget Line",
    "Estimate Line": "Estimate Line",
    "Cronograma Jerárquico": "Hierarchical Schedule",
    "Estimado aprobado disponible": "Approved estimate available",
    "Puedes generar categorías e ítems automáticamente desde este estimado.": "You can generate categories and items automatically from this estimate.",
    "Generar desde Estimado": "Generate from Estimate",
    "Usa el botón 'Generar desde Estimado' arriba para comenzar.": "Use the 'Generate from Estimate' button above to start.",
    "ítems": "items",
    "Progreso": "Progress",
    "¿Recalcular progreso desde tareas vinculadas?": "Recalculate progress from linked tasks?",
    "No hay ítems en esta categoría.": "No items in this category.",
    "Ítems sin categoría": "Uncategorized items",
    "O crea una nueva categoría abajo": "Or create a new category below",
    "Nueva categoría (opcional)": "New category (optional)",
    "Si completas este campo se ignorará la selección de arriba.": "If you complete this field the selection above will be ignored.",
    "Inicio plan.": "Plan. start",
    "Fin plan.": "Plan. end",
    "%% Completado (manual)": "%% Complete (manual)",
    "Eliminar Ítem": "Delete Item",
    "¿Está seguro de que desea eliminar el ítem": "Are you sure you want to delete the item",
    "Editar Ítem": "Edit Item",
    "Editar Ítem del Cronograma": "Edit Schedule Item",
    "Edit SOP": "Edit SOP",
}

def translate_simple(text):
    """Traducir texto simple usando el diccionario"""
    return TRANSLATIONS.get(text, None)

def process_po_file(filepath):
    """Procesar archivo PO y agregar traducciones automáticas"""
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    modified = []
    i = 0
    translations_added = 0
    
    while i < len(lines):
        line = lines[i]
        modified.append(line)
        
        # Buscar msgid seguido de msgstr vacío
        if line.startswith('msgid "') and not line.startswith('msgid ""'):
            # Extraer el texto del msgid
            msgid_match = re.match(r'msgid "(.*)"', line)
            if msgid_match:
                msgid_text = msgid_match.group(1)
                
                # Ver si la siguiente línea es msgstr vacío
                if i + 1 < len(lines):
                    next_line = lines[i + 1]
                    if next_line.strip() == 'msgstr ""':
                        # Intentar traducir
                        translation = translate_simple(msgid_text)
                        if translation:
                            modified[-1] = line  # mantener msgid
                            modified.append(f'msgstr "{translation}"\n')
                            translations_added += 1
                            i += 2  # saltar el msgstr vacío original
                            continue
        
        i += 1
    
    # Escribir archivo modificado
    with open(filepath, 'w', encoding='utf-8') as f:
        f.writelines(modified)
    
    return translations_added

if __name__ == '__main__':
    en_file = 'locale/en/LC_MESSAGES/django.po'
    count = process_po_file(en_file)
    print(f"✓ Agregadas {count} traducciones automáticas a {en_file}")

