# Generated by Django 5.2.4 on 2025-07-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Nombre del proyecto o factura')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad recibida')),
                ('date_received', models.DateField(verbose_name='Fecha de ingreso')),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('ZELLE', 'Zelle'), ('OTRO', 'Otro')], max_length=50, verbose_name='Método de pago')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas (opcional)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='incomes/', verbose_name='Archivo adjunto (PDF o imagen)')),
            ],
        ),
    ]
