# Generated by Django 5.2.4 on 2025-07-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('MATERIALES', 'Materiales'), ('COMIDA', 'Comida'), ('SEGURO', 'Seguro'), ('ALMACÉN', 'Storage'), ('MANO_OBRA', 'Mano de obra'), ('OTRO', 'Otro')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/')),
            ],
        ),
    ]
