# Generated by Django 5.2.4 on 2025-07-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('paint_colors', models.TextField(blank=True, help_text='Ejemplo: SW 7008 Alabaster, SW 6258 Tricorn Black')),
                ('paint_codes', models.TextField(blank=True, help_text='Códigos de pintura si son diferentes de los colores comunes')),
                ('stains_or_finishes', models.TextField(blank=True, help_text='Ejemplo: Milesi Butternut 072 - 2 coats')),
                ('number_of_rooms_or_areas', models.IntegerField(blank=True, null=True)),
                ('number_of_paint_defects', models.IntegerField(blank=True, help_text='Número de manchas o imperfecciones detectadas', null=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reflection_notes', models.TextField(blank=True, help_text='Notas sobre aprendizajes, errores o mejoras para próximos proyectos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
