# Generated by Django 5.2.4 on 2025-07-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(),
        ),
    ]
