# Generated by Django 5.2.4 on 2025-07-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_timeentry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Time')),
                ('end_datetime', models.DateTimeField(verbose_name='End Time')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='Status')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progress (%)')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks / Delay reason')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='schedule_photos/', verbose_name='Photo / Attachment')),
                ('is_private', models.BooleanField(default=False, verbose_name='Private (only admin)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
            ],
        ),
    ]
