# Generated by Django 5.2.4 on 2025-07-19 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AddField(
            model_name='schedule',
            name='advance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='delay_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='stage',
            field=models.CharField(blank=True, choices=[('Site cleaning', 'Site cleaning'), ('Preparation', 'Preparation'), ('Covering', 'Covering'), ('Staining', 'Staining'), ('Sealer', 'Sealer'), ('Lacquer', 'Lacquer'), ('Caulking', 'Caulking'), ('Painting', 'Painting'), ('Plastic removal', 'Plastic removal'), ('Cleaning', 'Cleaning'), ('Touch up', 'Touch up')], max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='schedule_photos/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
