# Generated by Django 5.2.4 on 2025-07-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_expense_project_income_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-date']},
        ),
    ]
