# Generated by Django 5.2.4 on 2025-07-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_schedule_options_alter_timeentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_labor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto para mano de obra', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_materials',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto para materiales', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_other',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto para otros gastos (seguros, almacenamiento, etc.)', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto total asignado al proyecto', max_digits=10),
        ),
    ]
