# Generated by Django 5.2.4 on 2025-07-29 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_budget_labor_project_budget_materials_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date_received',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='income',
            name='attachment',
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='expenses/invoices/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expenses/receipts/'),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría (opcional)'),
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (opcional)'),
        ),
        migrations.AddField(
            model_name='income',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='incomes/', verbose_name='Factura o comprobante'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MATERIALES', 'Materiales'), ('COMIDA', 'Comida'), ('SEGURO', 'Seguro'), ('ALMACÉN', 'Storage'), ('MANO_OBRA', 'Mano de obra'), ('OFICINA', 'Oficina'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, help_text='Cheque o referencia de pago', max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.payroll')),
            ],
        ),
    ]
