# Generated by Django 5.2.4 on 2025-07-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_date_received_income_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
