# Generated by Django 5.2.4 on 2025-07-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_timeentry_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Cheque o referencia de pago individual', max_length=100),
        ),
    ]
