# Generated by Django 5.2.4 on 2025-07-30 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='touch_ups',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
