# Generated by Django 5.2.4 on 2025-07-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_timeentry_touch_ups_alter_timeentry_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('billed', 'Facturado'), ('paid', 'Pagado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='change_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.changeorder'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='change_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core.changeorder'),
        ),
    ]
