# Generated by Django 5.2.4 on 2025-08-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_invoice_invoiceline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='touch_ups',
        ),
    ]
