# Generated by Django 5.2.4 on 2025-08-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_costcode_changeorder_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='planned_finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='planned_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='weight_override',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional weight (0-1). If empty, weight is baseline/total.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='cost_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.costcode'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='cost_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core.costcode'),
        ),
        migrations.CreateModel(
            name='BudgetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty_completed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percent_complete', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_points', to='core.budgetline')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('budget_line', 'date')},
            },
        ),
    ]
