# Generated by Django 5.2.4 on 2025-09-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_budgetline_planned_finish_budgetline_planned_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
