# Generated by Django 5.2.4 on 2025-09-03 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_timeentry_end_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_when', models.CharField(choices=[('now', 'Ahora (emergencia)'), ('tomorrow', 'Mañana'), ('next_week', 'Siguiente semana'), ('date', 'Fecha específica')], default='now', max_length=20)),
                ('needed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Enviada'), ('ordered', 'Ordenada'), ('fulfilled', 'Entregada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to='core.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('paint', 'Pintura'), ('primer', 'Primer'), ('stain', 'Stain'), ('lacquer', 'Laca/Clear'), ('thinner', 'Thinner/Solvente'), ('tape', 'Tape'), ('plastic', 'Plástico'), ('masking_paper', 'Papel enmascarar'), ('floor_paper', 'Papel para piso'), ('drop_cloth', 'Tela/manta protección'), ('brush', 'Brocha'), ('roller_cover', 'Rodillo (cover)'), ('roller_frame', 'Rodillo (frame)'), ('tray', 'Charola'), ('tray_liner', 'Liner'), ('sandpaper', 'Lija'), ('blades', 'Cuchillas'), ('scraper', 'Raspador'), ('mix', 'Mezcladores/baldes'), ('caulk', 'Caulk/Sellador'), ('adhesive', 'Adhesivo'), ('bonding', 'Bonding agent'), ('respirator', 'Respirador'), ('mask', 'Mascarilla'), ('coverall', 'Overol'), ('gloves', 'Guantes'), ('rags', 'Trapos'), ('colorant', 'Colorante/Tinte'), ('other', 'Otro')], max_length=20)),
                ('brand', models.CharField(choices=[('sherwin_williams', 'Sherwin‑Williams'), ('benjamin_moore', 'Benjamin Moore'), ('3m', '3M'), ('wurth', 'Würth'), ('milesi', 'Milesi'), ('chemcraft', 'Chemcraft'), ('purdy', 'Purdy'), ('wooster', 'Wooster'), ('titebond', 'Titebond'), ('other', 'Otra')], default='sherwin_williams', max_length=30)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('color_name', models.CharField(blank=True, max_length=200)),
                ('color_code', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('gloss', models.CharField(blank=True, max_length=100)),
                ('formula', models.TextField(blank=True)),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='materials/requests/')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('gal', 'Galón'), ('liter', 'Litro'), ('qt', 'Quart'), ('pt', 'Pint'), ('roll', 'Rollo'), ('sheet', 'Hoja'), ('box', 'Caja'), ('tube', 'Tubo'), ('pair', 'Par'), ('pack', 'Paquete'), ('sq_ft', 'ft²'), ('sq_m', 'm²'), ('unit', 'Unidad')], default='gal', max_length=10)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.materialrequest')),
            ],
        ),
    ]
