# Generated by Django 5.2.4 on 2025-10-01 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_materialrequest_materialrequestitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('paint', 'Pintura'), ('primer', 'Primer'), ('stain', 'Stain'), ('lacquer', 'Laca/Clear'), ('thinner', 'Thinner/Solvente'), ('tape', 'Tape'), ('plastic', 'Plástico'), ('masking_paper', 'Papel enmascarar'), ('floor_paper', 'Papel para piso'), ('drop_cloth', 'Tela/manta protección'), ('brush', 'Brocha'), ('roller_cover', 'Rodillo (cover)'), ('roller_frame', 'Rodillo (frame)'), ('tray', 'Charola'), ('tray_liner', 'Liner'), ('sandpaper', 'Lija'), ('blades', 'Cuchillas'), ('scraper', 'Raspador'), ('mix', 'Mezcladores/baldes'), ('caulk', 'Caulk/Sellador'), ('adhesive', 'Adhesivo'), ('bonding', 'Bonding agent'), ('respirator', 'Respirador'), ('mask', 'Mascarilla'), ('coverall', 'Overol'), ('gloves', 'Guantes'), ('rags', 'Trapos'), ('colorant', 'Colorante/Tinte'), ('other', 'Otro')], max_length=20)),
                ('brand_text', models.CharField(max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('color_name', models.CharField(blank=True, max_length=200)),
                ('color_code', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('gloss', models.CharField(blank=True, max_length=100)),
                ('formula', models.TextField(blank=True)),
                ('default_unit', models.CharField(blank=True, max_length=50)),
                ('reference_image', models.FileField(blank=True, null=True, upload_to='materials/catalog/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_catalog', to='core.project')),
            ],
            options={
                'verbose_name': 'Catálogo de material',
                'verbose_name_plural': 'Catálogo de materiales',
                'indexes': [models.Index(fields=['project', 'category', 'brand_text', 'product_name'], name='core_materi_project_db214a_idx')],
            },
        ),
    ]
