# Generated by Django 5.2.4 on 2025-10-03 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_materialcatalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=120)),
                ('wall_ref', models.CharField(blank=True, help_text='Pared o ubicación', max_length=120)),
                ('image', models.ImageField(upload_to='site_photos/')),
                ('approved_color_id', models.IntegerField(blank=True, db_index=True, help_text='ID de color aprobado (opcional)', null=True)),
                ('color_text', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('finish', models.CharField(blank=True, max_length=120)),
                ('gloss', models.CharField(blank=True, max_length=120)),
                ('special_finish', models.BooleanField(default=False)),
                ('coats', models.PositiveSmallIntegerField(default=1)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_photos', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
