# Generated by Django 5.2.4 on 2025-10-06 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sitephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('MATERIAL', 'Material'), ('PINTURA', 'Pintura'), ('ESCALERA', 'Escaleras'), ('LIJADORA', 'Lijadoras / Power'), ('SPRAY', 'Sprayadoras / Tips'), ('HERRAMIENTA', 'Herramientas'), ('OTRO', 'Otro')], max_length=20)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('is_equipment', models.BooleanField(default=False)),
                ('track_serial', models.BooleanField(default=False)),
                ('default_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_storage', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locations', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIVE', 'Entrada compra'), ('ISSUE', 'Salida a uso / consumo'), ('TRANSFER', 'Traslado'), ('RETURN', 'Regreso a storage'), ('ADJUST', 'Ajuste manual'), ('CONSUME', 'Consumo registrado')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_out', to='core.inventorylocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventoryitem')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_in', to='core.inventorylocation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('threshold_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventoryitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.inventorylocation')),
            ],
            options={
                'unique_together': {('item', 'location')},
            },
        ),
    ]
