# Generated by Django 5.2.4 on 2025-11-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_inventoryitem_inventorylocation_inventorymovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='core.expense'),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventoryitem'),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='item_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='item_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received_partial', 'Received Partial'), ('received', 'Received'), ('consumed', 'Consumed'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='qty_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='qty_ordered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='qty_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='qty_requested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='qty_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
