# Generated by Django 5.2.4 on 2025-11-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_inventorymovement_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='no_threshold',
            field=models.BooleanField(default=False),
        ),
    ]
