# Generated by Django 5.2.4 on 2025-11-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_inventoryitem_no_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Enviada'), ('ordered', 'Ordenada'), ('fulfilled', 'Entregada'), ('cancelled', 'Cancelada'), ('purchased_lead', 'Compra directa (líder)')], default='pending', max_length=20),
        ),
    ]
