# Generated by Django 5.2.4 on 2025-11-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_materialrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', help_text='Preferred UI language', max_length=5),
        ),
    ]
