# Generated by Django 5.2.4 on 2025-11-08 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_profile_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Activity Name')),
                ('category', models.CharField(choices=[('PREP', 'Preparation'), ('COVER', 'Covering'), ('SAND', 'Sanding'), ('STAIN', 'Staining'), ('SEAL', 'Sealing'), ('PAINT', 'Painting'), ('CAULK', 'Caulking'), ('CLEANUP', 'Cleanup'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Overall description of the activity')),
                ('time_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete', max_digits=5, null=True)),
                ('steps', models.JSONField(default=list, help_text="Checklist steps as JSON array. Example: ['Step 1', 'Step 2']")),
                ('materials_list', models.JSONField(default=list, help_text='Required materials as JSON array')),
                ('tools_list', models.JSONField(default=list, help_text='Required tools as JSON array')),
                ('tips', models.TextField(blank=True, help_text='Best practices and tips')),
                ('common_errors', models.TextField(blank=True, help_text='Common mistakes to avoid')),
                ('reference_photos', models.JSONField(default=list, help_text='URLs or paths to reference photos')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or training video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Hide inactive templates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Template (SOP)',
                'verbose_name_plural': 'Activity Templates (SOPs)',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(help_text='The work day this plan is for', verbose_name='Date for this plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved by Admin'), ('SKIPPED', 'No Planning Needed')], default='DRAFT', max_length=20)),
                ('completion_deadline', models.DateTimeField(help_text='Deadline to submit plan (usually 5pm day before)')),
                ('no_planning_reason', models.TextField(blank=True, help_text='Reason why no planning is needed (e.g., no projects scheduled)')),
                ('admin_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='core.project')),
            ],
            options={
                'verbose_name': 'Daily Plan',
                'verbose_name_plural': 'Daily Plans',
                'ordering': ['-plan_date'],
            },
        ),
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order in the daily plan')),
                ('is_group_activity', models.BooleanField(default=True, help_text='True if all employees work together, False if divided into sub-tasks')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('materials_needed', models.JSONField(default=list, help_text='List of materials needed with quantities')),
                ('materials_checked', models.BooleanField(default=False, help_text='True if material availability has been verified')),
                ('material_shortage', models.BooleanField(default=False, help_text='True if materials are insufficient')),
                ('status', models.CharField(choices=[('PENDING', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='0-100% completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_template', models.ForeignKey(blank=True, help_text='SOP template for this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activitytemplate')),
                ('assigned_employees', models.ManyToManyField(help_text='Employees assigned to this activity', related_name='assigned_activities', to='core.employee')),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.dailyplan')),
                ('schedule_item', models.ForeignKey(blank=True, help_text='Link to parent schedule item if this is a sub-task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schedule')),
            ],
            options={
                'verbose_name': 'Planned Activity',
                'verbose_name_plural': 'Planned Activities',
                'ordering': ['daily_plan', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_datetime', models.DateTimeField(auto_now_add=True)),
                ('completion_photos', models.JSONField(default=list, help_text='Array of photo URLs/paths showing completed work')),
                ('employee_notes', models.TextField(blank=True, help_text='Internal notes from employee (Spanish, not shown to client)')),
                ('progress_percentage', models.IntegerField(default=100, help_text='Completion percentage at time of marking done')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_activities', to='core.employee')),
                ('verified_by', models.ForeignKey(blank=True, help_text='PM or Admin who verified this completion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_completions', to=settings.AUTH_USER_MODEL)),
                ('planned_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='core.plannedactivity')),
            ],
            options={
                'verbose_name': 'Activity Completion',
                'verbose_name_plural': 'Activity Completions',
                'ordering': ['-completion_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['plan_date', 'status'], name='core_dailyp_plan_da_8360e6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['project', 'plan_date'], name='core_dailyp_project_14de70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('project', 'plan_date')},
        ),
    ]
