# Generated by Django 5.2.4 on 2025-11-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_sopreferencefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sopreferencefile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'SOP Reference File', 'verbose_name_plural': 'SOP Reference Files'},
        ),
        migrations.AlterField(
            model_name='sopreferencefile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
