# Generated by Django 5.2.4 on 2025-11-09 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_invoice_amount_paid_invoice_approved_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollentry',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['week_start', 'employee__last_name']},
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='paid',
            new_name='reviewed',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='check_number',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='pay_date',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='adjusted_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa ajustada para esta semana (override)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('check', 'Cheque'), ('transfer', 'Transferencia'), ('cash', 'Efectivo')], default='check', max_length=20)),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.payrollrecord')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('paid', 'Pagado')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.payrollperiod'),
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='PayrollEntry',
        ),
    ]
