# Generated by Django 5.2.4 on 2025-11-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_payrollentry_payroll_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetprogress',
            unique_together=set(),
        ),
    ]
