# Generated by Django 5.2.4 on 2025-11-09 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_clientrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('decision', 'Decisión'), ('call', 'Llamada'), ('email', 'Correo'), ('meeting', 'Reunión'), ('approval', 'Aprobación'), ('change', 'Cambio/Modificación'), ('issue', 'Problema'), ('milestone', 'Hito'), ('note', 'Nota')], default='note', max_length=20)),
                ('title', models.CharField(help_text='Resumen breve del evento', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detalles completos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField(help_text='Fecha/hora del evento real (puede ser diferente de created_at)')),
                ('participants', models.TextField(blank=True, help_text='Nombres de participantes en llamada/reunión')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='minutes/%Y/%m/')),
                ('visible_to_client', models.BooleanField(default=True, help_text='¿El cliente puede ver esta minuta?')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Minute',
                'verbose_name_plural': 'Project Minutes',
                'ordering': ['-event_date'],
            },
        ),
    ]
