# Generated by Django 5.2.4 on 2025-11-09 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_comment_options_alter_task_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='code',
            field=models.CharField(blank=True, help_text='KP + siglas del cliente + secuencia (desde 1000)', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='takeoff_link',
            field=models.URLField(blank=True, help_text='Link a Dropbox/Drive con el takeoff o soporte'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, help_text='Referencia amigable; si hay Estimate aprobado: usa su código + secuencia', max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='ClientProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('external_pm', 'External PM'), ('viewer', 'Viewer')], default='client', max_length=20)),
                ('can_comment', models.BooleanField(default=True)),
                ('can_create_tasks', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Project Access',
                'verbose_name_plural': 'Client Project Accesses',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
