# Generated by Django 5.2.4 on 2025-11-09 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_estimate_code_estimate_takeoff_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='SW xxxx, Milesi xxx, etc.', max_length=60)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('finish', models.CharField(blank=True, max_length=120)),
                ('gloss', models.CharField(blank=True, max_length=50)),
                ('version', models.PositiveIntegerField(default=1, help_text='Incrementa cuando se sube una variante')),
                ('status', models.CharField(choices=[('proposed', 'Propuesto'), ('review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('archived', 'Archivado')], default='proposed', max_length=20)),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='color_samples/')),
                ('reference_photo', models.ImageField(blank=True, null=True, upload_to='color_samples/ref/')),
                ('notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Marcadores y comentarios sobre la imagen (JSON)')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_samples_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_samples_created', to=settings.AUTH_USER_MODEL)),
                ('parent_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='core.colorsample')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_samples', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='core_colors_project_f05be7_idx'), models.Index(fields=['project', 'brand', 'code'], name='core_colors_project_adb7ce_idx')],
            },
        ),
    ]
