# Generated by Django 5.2.4 on 2025-11-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_task_is_touchup_alter_planpin_pin_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpin',
            name='is_multipoint',
            field=models.BooleanField(default=False, help_text='Pin con trayectoria multipunto'),
        ),
        migrations.AddField(
            model_name='planpin',
            name='path_points',
            field=models.JSONField(blank=True, default=list, help_text='Lista de puntos conectados: [{x:0.1,y:0.2,label:"A"}]'),
        ),
    ]
