# Generated by Django 5.2.4 on 2025-11-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_multipoint_pins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_created', 'Tarea creada'), ('task_assigned', 'Tarea asignada'), ('task_completed', 'Tarea completada'), ('color_review', 'Color en revisión'), ('color_approved', 'Color aprobado'), ('color_rejected', 'Color rechazado'), ('damage_reported', 'Daño reportado'), ('chat_message', 'Mensaje en chat'), ('comment_added', 'Comentario agregado'), ('estimate_approved', 'Estimación aprobada')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('link_url', models.CharField(blank=True, help_text='URL para redirigir al hacer clic', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
