# Generated by Django 5.2.4 on 2025-11-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpin',
            name='pin_color',
            field=models.CharField(default='#0d6efd', help_text='Color hex para el pin', max_length=7),
        ),
    ]
