# Generated by Django 5.2.4 on 2025-11-09 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_pin_dynamic_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_billed', models.DecimalField(decimal_places=2, help_text='Percentage of this estimate line being billed (0.00-100.00)', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount = estimate_line.total * (percentage_billed/100)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_billings', to='core.estimateline')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_billings', to='core.invoiceline')),
            ],
            options={
                'verbose_name': 'Invoice Line Estimate Billing',
                'verbose_name_plural': 'Invoice Line Estimate Billings',
                'ordering': ['-created_at'],
            },
        ),
    ]
