# Generated by Django 5.2.4 on 2025-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_schedulecategory_scheduleitem_task_schedule_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecategory',
            name='is_phase',
            field=models.BooleanField(default=False, help_text='Marcar si esta categoría representa una fase agregada del cronograma'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='is_milestone',
            field=models.BooleanField(default=False, help_text='Si es un hito se mostrará como diamante en el Gantt'),
        ),
    ]
