# Generated by comprehensive code analysis and optimization
# This migration adds database indexes to frequently filtered/joined fields
# to dramatically improve query performance across the application.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_schedulecategory_is_phase_scheduleitem_is_milestone'),
    ]

    operations = [
        # TimeEntry indexes - heavily filtered by date and project
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        
        # Invoice indexes - frequently filtered by status
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'),
                    ('APPROVED', 'Approved'), ('PARTIAL', 'Partial Payment'),
                    ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')
                ],
                db_index=True,
                default='DRAFT',
                max_length=20
            ),
        ),
        
        # ChangeOrder indexes - frequently filtered by status
        migrations.AlterField(
            model_name='changeorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'), ('approved', 'Approved'),
                    ('rejected', 'Rejected'), ('sent', 'Sent'),
                    ('billed', 'Billed'), ('paid', 'Paid')
                ],
                db_index=True,
                default='pending',
                max_length=20
            ),
        ),
        
        # BudgetProgress indexes - filtered by date for EV calculations
        migrations.AlterField(
            model_name='budgetprogress',
            name='date',
            field=models.DateField(db_index=True),
        ),
        
        # MaterialRequest indexes - frequently filtered by status
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'), ('submitted', 'Submitted'),
                    ('ordered', 'Ordered'), ('purchased_lead', 'Purchased by Lead'),
                    ('cancelled', 'Cancelled')
                ],
                db_index=True,
                default='pending',
                max_length=20
            ),
        ),
        
        # Task indexes - filtered by status and touchup flag
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'),
                    ('Completada', 'Completada')
                ],
                db_index=True,
                default='Pendiente',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_touchup',
            field=models.BooleanField(db_index=True, default=False),
        ),
        
        # DailyPlan indexes - frequently queried by date
        migrations.AlterField(
            model_name='dailyplan',
            name='plan_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')
                ],
                db_index=True,
                default='DRAFT',
                max_length=20
            ),
        ),
        
        # Employee indexes - filtered by active status
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        
        # Add composite indexes for common query patterns
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['project', 'date'], name='timeentry_proj_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['employee', 'date'], name='timeentry_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['change_order'], name='timeentry_co_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['project', 'status'], name='invoice_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetprogress',
            index=models.Index(fields=['budget_line', 'date'], name='budgetprog_line_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='task_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='task_assigned_status_idx'),
        ),
    ]
