# Generated by comprehensive bug fix analysis
# This migration fixes critical data integrity issues identified during code review:
# 1. Adds unique constraint to BudgetProgress to prevent duplicate progress records
# 2. Consolidates MaterialRequestItem redundant quantity fields
# 3. Adds validation for negative values in Employee and Project budget fields

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_database_indexes'),
    ]

    operations = [
        # FIX 1: BudgetProgress - Add unique constraint to prevent duplicate records per date
        # This prevents data integrity issues where multiple progress records exist for same line+date
        migrations.AlterUniqueTogether(
            name='budgetprogress',
            unique_together={('budget_line', 'date')},
        ),
        
        # FIX 2: Employee - Add validators to prevent negative hourly_rate
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0.01)],
                help_text="Hourly rate must be greater than zero"
            ),
        ),
        
        # FIX 3: Project - Add validators to prevent negative budget values
        migrations.AlterField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Presupuesto total asignado al proyecto",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_labor',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Presupuesto para mano de obra",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_materials',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Presupuesto para materiales",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_other',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Presupuesto para otros gastos (seguros, almacenamiento, etc.)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        
        # FIX 4: MaterialRequestItem - Mark qty_requested as the primary field, 
        # quantity field will be deprecated in favor of qty_requested
        # Note: Keeping both fields for backward compatibility, but qty_requested is canonical
        migrations.AlterField(
            model_name='materialrequestitem',
            name='qty_requested',
            field=models.DecimalField(
                decimal_places=2,
                help_text="Primary quantity field - use this for new code",
                max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name='materialrequestitem',
            name='quantity',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="DEPRECATED: Use qty_requested instead",
                max_digits=10,
                null=True
            ),
        ),
    ]
