# Generated by Django 4.2.26 on 2025-11-13 15:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0054_fix_data_integrity_bugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this snapshot')),
                ('planned_value', models.DecimalField(decimal_places=2, help_text='PV - Budgeted cost of work scheduled', max_digits=12)),
                ('earned_value', models.DecimalField(decimal_places=2, help_text='EV - Budgeted cost of work performed', max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, help_text='AC - Actual cost of work performed', max_digits=12)),
                ('spi', models.DecimalField(decimal_places=3, help_text='Schedule Performance Index (EV/PV)', max_digits=5)),
                ('cpi', models.DecimalField(decimal_places=3, help_text='Cost Performance Index (EV/AC)', max_digits=5)),
                ('schedule_variance', models.DecimalField(decimal_places=2, help_text='SV = EV - PV', max_digits=12)),
                ('cost_variance', models.DecimalField(decimal_places=2, help_text='CV = EV - AC', max_digits=12)),
                ('estimate_at_completion', models.DecimalField(decimal_places=2, help_text='EAC - Forecasted final cost', max_digits=12)),
                ('estimate_to_complete', models.DecimalField(decimal_places=2, help_text='ETC - Remaining cost', max_digits=12)),
                ('variance_at_completion', models.DecimalField(decimal_places=2, help_text='VAC = BAC - EAC', max_digits=12)),
                ('percent_complete', models.DecimalField(decimal_places=2, help_text='% of project complete', max_digits=5)),
                ('percent_spent', models.DecimalField(decimal_places=2, help_text='% of budget spent', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'EV Snapshot',
                'verbose_name_plural': 'EV Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseOCRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_items', models.JSONField(blank=True, default=list, help_text='Extracted line items from receipt')),
                ('ocr_confidence', models.DecimalField(decimal_places=2, help_text='OCR confidence % (0-100)', max_digits=5)),
                ('raw_text', models.TextField(blank=True, help_text='Full raw OCR text')),
                ('suggested_category', models.CharField(blank=True, max_length=100)),
                ('ai_suggestion_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expense OCR Data',
                'verbose_name_plural': 'Expense OCR Data',
            },
        ),
        migrations.CreateModel(
            name='GPSCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('check_in_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_in_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_in_accuracy', models.DecimalField(decimal_places=2, help_text='GPS accuracy in meters', max_digits=5)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('within_geofence', models.BooleanField(default=True, help_text='Was check-in within project geofence?')),
                ('distance_from_project', models.DecimalField(decimal_places=2, help_text='Distance in meters', max_digits=8)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('auto_break_detected', models.BooleanField(default=False)),
                ('auto_break_minutes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'GPS Check-In',
                'verbose_name_plural': 'GPS Check-Ins',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_type', models.CharField(choices=[('CODE128', 'Code 128'), ('CODE39', 'Code 39'), ('EAN13', 'EAN-13'), ('UPC', 'UPC'), ('QR', 'QR Code')], default='CODE128', max_length=20)),
                ('barcode_value', models.CharField(max_length=100, unique=True)),
                ('barcode_image', models.ImageField(blank=True, upload_to='inventory/barcodes/')),
                ('enable_auto_reorder', models.BooleanField(default=False)),
                ('reorder_point', models.DecimalField(decimal_places=2, help_text='Trigger reorder when stock below this', max_digits=10)),
                ('reorder_quantity', models.DecimalField(decimal_places=2, help_text='How much to reorder', max_digits=10)),
                ('preferred_vendor', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventory Barcode',
                'verbose_name_plural': 'Inventory Barcodes',
            },
        ),
        migrations.CreateModel(
            name='InvoiceAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('next_recurrence_date', models.DateField(blank=True, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, help_text='When to stop auto-generating', null=True)),
                ('auto_send_on_creation', models.BooleanField(default=False)),
                ('auto_remind_before_due', models.IntegerField(default=3, help_text='Days before due date to send reminder')),
                ('auto_remind_after_due', models.BooleanField(default=True, help_text='Send reminders for overdue invoices')),
                ('reminder_frequency_days', models.IntegerField(default=7, help_text='How often to remind after due')),
                ('apply_late_fees', models.BooleanField(default=False)),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='% per month', max_digits=5)),
                ('late_fee_grace_days', models.IntegerField(default=5, help_text='Days after due before applying fee')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('payment_link', models.URLField(blank=True, help_text='Direct payment link for client')),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Invoice Automation',
                'verbose_name_plural': 'Invoice Automations',
            },
        ),
        migrations.CreateModel(
            name='QualityDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_by_ai', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], max_length=20)),
                ('category', models.CharField(help_text='e.g., Paint finish, Trim alignment, etc.', max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='Room/area where defect was found', max_length=200)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence % (0-100)', max_digits=5, null=True)),
                ('ai_pattern_match', models.CharField(blank=True, help_text='Pattern matched by AI', max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quality/defects/%Y/%m/')),
                ('resolution_photo', models.ImageField(blank=True, null=True, upload_to='quality/resolutions/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quality Defect',
                'verbose_name_plural': 'Quality Defects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('initial', 'Initial Inspection'), ('progress', 'Progress Inspection'), ('final', 'Final Inspection'), ('warranty', 'Warranty Inspection'), ('defect_followup', 'Defect Follow-up')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional Pass')], default='scheduled', max_length=20)),
                ('overall_score', models.IntegerField(blank=True, help_text='0-100 quality score', null=True)),
                ('ai_defect_count', models.IntegerField(default=0, help_text='Defects detected by AI')),
                ('manual_defect_count', models.IntegerField(default=0, help_text='Defects found manually')),
                ('notes', models.TextField(blank=True)),
                ('checklist_data', models.JSONField(blank=True, default=dict, help_text='Inspection checklist results')),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('warranty_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quality Inspection',
                'verbose_name_plural': 'Quality Inspections',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('start_date', models.DateField(help_text='When to start generating tasks')),
                ('end_date', models.DateField(blank=True, help_text='When to stop (null = no end)', null=True)),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Checklist items for auto-generated tasks')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_generated', models.DateField(blank=True, help_text='Last date a task was generated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurring Task',
                'verbose_name_plural': 'Recurring Tasks',
            },
        ),
        migrations.RemoveIndex(
            model_name='budgetprogress',
            name='budgetprog_line_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_proj_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_proj_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_assigned_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeentry_proj_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeentry_emp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='timeentry',
            name='timeentry_co_idx',
        ),
        migrations.AlterUniqueTogether(
            name='budgetprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budgetprogress',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('billed', 'Facturado'), ('paid', 'Pagado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='plan_date',
            field=models.DateField(help_text='The work day this plan is for', verbose_name='Date for this plan'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved by Admin'), ('SKIPPED', 'No Planning Needed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('VIEWED', 'Vista por Cliente'), ('APPROVED', 'Aprobada'), ('PARTIAL', 'Pago Parcial'), ('PAID', 'Pagada Completa'), ('OVERDUE', 'Vencida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Enviada'), ('ordered', 'Ordenada'), ('fulfilled', 'Entregada'), ('cancelled', 'Cancelada'), ('purchased_lead', 'Compra directa (líder)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialrequestitem',
            name='qty_requested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialrequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_labor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto para mano de obra', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_materials',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto para materiales', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_other',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto para otros gastos (seguros, almacenamiento, etc.)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto total asignado al proyecto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_touchup',
            field=models.BooleanField(default=False, help_text='Marcar si esta tarea es un touch-up'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='cost_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcode'),
        ),
        migrations.AddField(
            model_name='recurringtask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to='core.project'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='core.project'),
        ),
        migrations.AddField(
            model_name='qualitydefect',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='core.qualityinspection'),
        ),
        migrations.AddField(
            model_name='qualitydefect',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceautomation',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='inventorybarcode',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='core.inventoryitem'),
        ),
        migrations.AddField(
            model_name='gpscheckin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_checkins', to='core.employee'),
        ),
        migrations.AddField(
            model_name='gpscheckin',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_checkins', to='core.project'),
        ),
        migrations.AddField(
            model_name='gpscheckin',
            name='time_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_checkin', to='core.timeentry'),
        ),
        migrations.AddField(
            model_name='expenseocrdata',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_data', to='core.expense'),
        ),
        migrations.AddField(
            model_name='expenseocrdata',
            name='suggested_cost_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcode'),
        ),
        migrations.AddField(
            model_name='expenseocrdata',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_snapshots', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='evsnapshot',
            index=models.Index(fields=['project', '-date'], name='core_evsnap_project_498bf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evsnapshot',
            unique_together={('project', 'date')},
        ),
    ]
