# Generated by Django 4.2.26 on 2025-11-13 19:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0055_evsnapshot_expenseocrdata_gpscheckin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('specialty', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('flooring', 'Flooring'), ('drywall', 'Drywall'), ('carpentry', 'Carpentry'), ('roofing', 'Roofing'), ('landscaping', 'Landscaping'), ('other', 'Other')], max_length=50)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.0'), help_text='0-5 stars', max_digits=3)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('insurance_expires', models.DateField(blank=True, null=True)),
                ('w9_on_file', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subcontractor',
                'verbose_name_plural': 'Subcontractors',
                'ordering': ['company_name'],
            },
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='badge_awarded',
            field=models.CharField(blank=True, help_text='Badge name if special achievement', max_length=50),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='completion_points',
            field=models.IntegerField(default=10, help_text='Points awarded for completing this SOP'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Skill level required', max_length=20),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='required_tools',
            field=models.JSONField(default=list, help_text='Specific tools needed (for checklist)'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='safety_warnings',
            field=models.TextField(blank=True, help_text='Important safety information'),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='ai_defects_detected',
            field=models.JSONField(blank=True, default=list, help_text='AI-detected defects in this photo'),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='paired_with',
            field=models.ForeignKey(blank=True, help_text='Link before/after photos together', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sitephoto'),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='photo_type',
            field=models.CharField(choices=[('before', 'Before'), ('progress', 'Progress'), ('after', 'After'), ('defect', 'Defect'), ('reference', 'Reference')], default='progress', help_text='Type of photo for better organization', max_length=20),
        ),
        migrations.CreateModel(
            name='SubcontractorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_work', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_assignments', to='core.project')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subcontractor')),
            ],
            options={
                'verbose_name': 'Subcontractor Assignment',
                'verbose_name_plural': 'Subcontractor Assignments',
            },
        ),
        migrations.CreateModel(
            name='PunchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text="e.g., 'Living Room - North Wall'", max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('paint', 'Paint'), ('trim', 'Trim'), ('cleanup', 'Cleanup'), ('repair', 'Repair'), ('touch_up', 'Touch Up'), ('other', 'Other')], default='paint', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='punchlist/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_punchlist_items', to='core.employee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_punchlist_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punchlist_items', to='core.project')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_punchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punch List Item',
                'verbose_name_plural': 'Punch List Items',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100)),
                ('skill_category', models.CharField(choices=[('painting', 'Painting'), ('drywall', 'Drywall'), ('carpentry', 'Carpentry'), ('safety', 'Safety'), ('equipment', 'Equipment Operation'), ('leadership', 'Leadership'), ('customer_service', 'Customer Service')], max_length=50)),
                ('date_earned', models.DateField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.employee')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Certification',
                'verbose_name_plural': 'Employee Certifications',
                'ordering': ['-date_earned'],
            },
        ),
        migrations.CreateModel(
            name='SOPCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Quiz score if applicable', null=True)),
                ('passed', models.BooleanField(default=True)),
                ('points_awarded', models.IntegerField(default=10)),
                ('badge_awarded', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_completions', to='core.employee')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.activitytemplate')),
            ],
            options={
                'verbose_name': 'SOP Completion',
                'verbose_name_plural': 'SOP Completions',
                'unique_together': {('employee', 'sop')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1, help_text='1-5 (Beginner to Expert)')),
                ('assessments_passed', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('last_assessment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='core.employee')),
            ],
            options={
                'verbose_name': 'Employee Skill Level',
                'verbose_name_plural': 'Employee Skill Levels',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, help_text='Leave blank for annual metrics', null=True)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('productivity_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% billable hours', max_digits=5)),
                ('defects_created', models.IntegerField(default=0, help_text='Touch-ups/rework assigned to this employee')),
                ('tasks_completed', models.IntegerField(default=0)),
                ('tasks_on_time', models.IntegerField(default=0)),
                ('days_worked', models.IntegerField(default=0)),
                ('days_late', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('quality_rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('attitude_rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('teamwork_rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_notes', models.TextField(blank=True)),
                ('bonus_paid', models.BooleanField(default=False)),
                ('bonus_paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='core.employee')),
            ],
            options={
                'verbose_name': 'Employee Performance Metric',
                'verbose_name_plural': 'Employee Performance Metrics',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
