# Generated by Django 4.2.26 on 2025-11-14 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_subcontractor_activitytemplate_badge_awarded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintLeftover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Marca de pintura (ej: Sherwin Williams)', max_length=100)),
                ('color_name', models.CharField(help_text='Nombre del color (ej: SW 7008 Alabaster)', max_length=200)),
                ('color_code', models.CharField(blank=True, help_text='Código del color', max_length=100)),
                ('finish', models.CharField(choices=[('flat', 'Flat'), ('matte', 'Matte'), ('eggshell', 'Eggshell'), ('satin', 'Satin'), ('semi_gloss', 'Semi-Gloss'), ('gloss', 'Gloss')], default='flat', max_length=50)),
                ('quantity_gallons', models.DecimalField(decimal_places=2, help_text='Cantidad en galones', max_digits=6)),
                ('container_type', models.CharField(choices=[('gallon', '1 Galón'), ('quart', 'Cuarto'), ('pint', 'Pinta'), ('other', 'Otro')], default='gallon', max_length=50)),
                ('num_containers', models.IntegerField(default=1, help_text='Número de contenedores')),
                ('location_notes', models.CharField(blank=True, help_text='Notas de ubicación específica', max_length=255)),
                ('condition', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('fair', 'Regular'), ('poor', 'Mala - No usar')], default='good', max_length=50)),
                ('date_stored', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftovers', to='core.colorsample')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_leftovers_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Ubicación donde se almacena', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventorylocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_leftovers', to='core.project')),
            ],
            options={
                'verbose_name': 'Paint Leftover',
                'verbose_name_plural': 'Paint Leftovers',
                'ordering': ['-date_stored'],
            },
        ),
    ]
