# Generated by Django 4.2.26 on 2025-11-14 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0057_paintleftover'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('daily_logs', 'Daily Logs Photos'), ('documents', 'Documents'), ('datasheets', 'Datasheets'), ('cos_signed', 'COs Firmados'), ('invoices', 'Invoices'), ('contracts', 'Contracts'), ('permits', 'Permits'), ('drawings', 'Drawings'), ('photos', 'Project Photos'), ('reports', 'Reports'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-folder', help_text='Bootstrap icon class (e.g., bi-folder, bi-file-earmark)', max_length=50)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color (primary, success, danger, etc.)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_categories', to='core.project')),
            ],
            options={
                'verbose_name': 'File Category',
                'verbose_name_plural': 'File Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date'], 'permissions': [('view_dailylog_client', 'Can view daily log as client')]},
        ),
        migrations.AddField(
            model_name='dailylog',
            name='accomplishments',
            field=models.TextField(blank=True, help_text='Logros específicos del día'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, help_text='Tareas completadas o con progreso este día', related_name='daily_logs', to='core.task'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailylog',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Visible para cliente/owner'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='next_day_plan',
            field=models.TextField(blank=True, help_text='Plan para el siguiente día'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='schedule_item',
            field=models.ForeignKey(blank=True, help_text='Actividad principal del schedule (ej: Cubrir y Preparar)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='core.schedule'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='schedule_progress_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Progreso de la actividad principal (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='crew_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de personas trabajando'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='delays',
            field=models.TextField(blank=True, help_text='Retrasos o problemas encontrados'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='progress_notes',
            field=models.TextField(blank=True, help_text='Notas generales de progreso'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='safety_incidents',
            field=models.TextField(blank=True, help_text='Incidentes de seguridad'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='weather',
            field=models.CharField(blank=True, help_text='Condiciones climáticas del día', max_length=120),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('spreadsheet', 'Spreadsheet'), ('word', 'Word Document'), ('cad', 'CAD Drawing'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to clients')),
                ('version', models.CharField(blank=True, help_text='Document version (e.g., v1.0, Rev A)', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.filecategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project File',
                'verbose_name_plural': 'Project Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='daily_logs/photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='logs', to='core.dailylogphoto'),
        ),
    ]
