# Generated by Django 4.2.26 on 2025-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_filecategory_alter_dailylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ['level', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='floorplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='level',
            field=models.IntegerField(default=0, help_text='Nivel numérico: 0=Planta Baja, 1=Nivel 1, 2=Nivel 2, -1=Sótano, etc.'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='level_identifier',
            field=models.CharField(blank=True, help_text='Identificador adicional: "Level 0", "Ground Floor", "Basement", etc.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='floorplan',
            index=models.Index(fields=['project', 'level'], name='core_floorp_project_09cf19_idx'),
        ),
    ]
