# Generated by Django 5.2.4 on 2025-11-14 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_floorplan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchUpPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, help_text='Normalized X coordinate (0..1)', max_digits=6)),
                ('y', models.DecimalField(decimal_places=4, help_text='Normalized Y coordinate (0..1)', max_digits=6)),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('custom_color_name', models.CharField(blank=True, help_text='If not using approved color', max_length=100)),
                ('sheen', models.CharField(blank=True, help_text='Brillo: Matte, Satin, Semi-gloss, Gloss', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Additional details about the touch-up')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('archived', 'Archivado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pin_color', models.CharField(default='#dc3545', help_text='Red for touch-ups by default', max_length=7)),
                ('approved_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchup_pins', to='core.colorsample')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_touchups', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_touchups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_touchups', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchup_pins', to='core.floorplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TouchUpCompletionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='touchups/completion/')),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Canvas annotations if photo was edited')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('touchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_photos', to='core.touchuppin')),
            ],
        ),
        migrations.AddIndex(
            model_name='touchuppin',
            index=models.Index(fields=['status', 'assigned_to'], name='core_touchu_status_bd6463_idx'),
        ),
        migrations.AddIndex(
            model_name='touchuppin',
            index=models.Index(fields=['plan', 'status'], name='core_touchu_plan_id_b2b59c_idx'),
        ),
    ]
