# Generated by Django 4.2.26 on 2025-11-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_touchuppin_touchupcompletionphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='category',
            field=models.CharField(choices=[('structural', 'Estructural'), ('cosmetic', 'Cosmético'), ('safety', 'Seguridad'), ('electrical', 'Eléctrico'), ('plumbing', 'Plomería'), ('hvac', 'HVAC'), ('other', 'Otro')], default='other', help_text='Categoría del daño', max_length=20),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo estimado de reparación', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='linked_co',
            field=models.ForeignKey(blank=True, help_text='Change Order vinculado si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='core.changeorder'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='linked_touchup',
            field=models.ForeignKey(blank=True, help_text='Touch-up vinculado si aplica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports', to='core.touchuppin'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de resolución', null=True),
        ),
    ]
