# Generated by Django 4.2.26 on 2025-11-14 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0061_add_damage_report_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchuppin',
            name='approval_status',
            field=models.CharField(choices=[('pending_review', 'Pendiente de Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending_review', help_text='Estado de aprobación de la completion', max_length=20),
        ),
        migrations.AddField(
            model_name='touchuppin',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo del rechazo si aplica'),
        ),
        migrations.AddField(
            model_name='touchuppin',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touchuppin',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='PM/Admin que revisó el completion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_touchups', to=settings.AUTH_USER_MODEL),
        ),
    ]
