# Generated by Django 4.2.26 on 2025-11-15 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_touchup_approval_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='color',
            field=models.CharField(blank=True, help_text='Color hex (ej: #FF5733)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Código de referencia o color', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChangeOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='changeorders/photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('annotations', models.TextField(blank=True, help_text='JSON con anotaciones dibujadas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.changeorder')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
