# Generated by Django 4.2.26 on 2025-11-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_changeorder_color_changeorder_reference_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderphoto',
            name='original_image',
            field=models.ImageField(blank=True, help_text='Copia de la imagen original antes de anotaciones', null=True, upload_to='changeorders/photos/original/'),
        ),
        migrations.AddField(
            model_name='changeorderphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza al reemplazar la imagen anotada'),
        ),
    ]
