# Generated by Django 4.2.26 on 2025-11-24 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0064_changeorderphoto_original_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tasks/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1, help_text='Versión de la imagen si se reemplaza')),
                ('is_current', models.BooleanField(default=True, help_text='True si es la versión actual')),
            ],
            options={
                'verbose_name': 'Imagen de Tarea',
                'verbose_name_plural': 'Imágenes de Tareas',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notas opcionales sobre el cambio')),
            ],
            options={
                'verbose_name': 'Cambio de Estado de Tarea',
                'verbose_name_plural': 'Cambios de Estado de Tareas',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='actual_hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total real hours worked (from time tracking)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='estimated_hours_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of estimated hours from all activities', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='weather_data',
            field=models.JSONField(blank=True, help_text='Weather data: {temp, condition, humidity, wind, etc.} fetched from API', null=True),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='weather_fetched_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when weather was last fetched', null=True),
        ),
        migrations.AddField(
            model_name='plannedactivity',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours worked (from time tracking or manual entry)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plannedactivity',
            name='converted_task',
            field=models.ForeignKey(blank=True, help_text='Task created from this planned activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_activity', to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Tareas que deben completarse antes de esta', related_name='dependent_tasks', to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha límite opcional para completar la tarea', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', help_text='Prioridad de la tarea', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp cuando se inicia el tracking de tiempo', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_tracked_seconds',
            field=models.IntegerField(default=0, help_text='Tiempo total trabajado en segundos (para tareas no touch-up)'),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'No Planning Needed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto del touch-up (principal)', null=True, upload_to='tasks/'),
        ),
        migrations.AddIndex(
            model_name='plannedactivity',
            index=models.Index(fields=['daily_plan', 'status'], name='core_planne_daily_p_ee8964_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedactivity',
            index=models.Index(fields=['activity_template'], name='core_planne_activit_8ed5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='core_task_project_3c46c4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='core_task_assigne_5bfa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_touchup'], name='core_task_is_touc_2e5a04_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='core_task_due_dat_d0a0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'status'], name='core_task_priorit_40dfd3_idx'),
        ),
        migrations.AddField(
            model_name='taskstatuschange',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatuschange',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.task'),
        ),
        migrations.AddField(
            model_name='taskimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.task'),
        ),
        migrations.AddField(
            model_name='taskimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taskstatuschange',
            index=models.Index(fields=['task', '-changed_at'], name='core_taskst_task_id_6e33a2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskimage',
            index=models.Index(fields=['task', 'is_current'], name='core_taskim_task_id_92f383_idx'),
        ),
    ]
