# Generated by Django 4.2.26 on 2025-11-24 14:50

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0065_activity1_tasks_dailyplans_sops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='partial_receipt_notes',
            field=models.TextField(blank=True, help_text='Notas sobre recepciones parciales'),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='brand_text',
            field=models.CharField(blank=True, help_text='Nombre de marca en texto libre', max_length=100),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cantidad total recibida (acumulada)', max_digits=10),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario (último)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('submitted', 'Enviada'), ('ordered', 'Ordenada'), ('partially_received', 'Parcialmente recibida'), ('fulfilled', 'Entregada'), ('cancelled', 'Cancelada'), ('purchased_lead', 'Compra directa (líder)')], default='draft', max_length=25),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['project', 'status'], name='core_materi_project_f7564d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['status', 'created_at'], name='core_materi_status_123545_idx'),
        ),
    ]
