# Generated by Django 4.2.26 on 2025-11-24 15:07

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0066_activity2_materials_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Q15.8: Costo promedio calculado', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Q15.8: Último costo de compra', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Q15.5: Umbral personalizado por item', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Q14.2: SKU único global', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='valuation_method',
            field=models.CharField(choices=[('FIFO', 'First In First Out'), ('LIFO', 'Last In First Out'), ('AVG', 'Average Cost')], default='AVG', help_text='Q15.8: Método de valuación de inventario', max_length=10),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='applied',
            field=models.BooleanField(default=False, help_text='Indica si el movimiento ya fue aplicado al inventario'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reason',
            field=models.TextField(blank=True, help_text='Q15.11: Razón del movimiento (audit trail)'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='related_project',
            field=models.ForeignKey(blank=True, help_text='Q15.9: Proyecto relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='core.project'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='Q15.9: Tarea relacionada con este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='core.task'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario en el momento del movimiento', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Q15.11: Timestamp del movimiento'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(help_text='Q15.11: Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.inventoryitem'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category', 'active'], name='core_invent_categor_382730_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='core_invent_sku_5292b0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item', '-created_at'], name='core_invent_item_id_ee1338_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['from_location', '-created_at'], name='core_invent_from_lo_7cb4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['to_location', '-created_at'], name='core_invent_to_loca_3534db_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['related_project', '-created_at'], name='core_invent_related_00bc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='core_invent_movemen_6bf542_idx'),
        ),
    ]
