# Generated by Django 4.2.26 on 2025-11-25 15:58

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0070_activity5_payroll_enhancements'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='colorsample',
            name='colorsample_proj_room_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='colorsample',
            name='colorsample_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='damagereport',
            name='damage_proj_status_sev_idx',
        ),
        migrations.RemoveIndex(
            model_name='damagereport',
            name='damage_assignee_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='floorplan',
            name='floorplan_proj_current_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollperiod',
            name='payroll_period_status_week_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollrecord',
            name='payroll_week_emp_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollrecord',
            name='payroll_review_adjust_idx',
        ),
        migrations.RemoveIndex(
            model_name='planpin',
            name='planpin_plan_status_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='sitephoto',
            name='sitephoto_proj_type_vis_idx',
        ),
        migrations.RemoveIndex(
            model_name='sitephoto',
            name='sitephoto_ver_date_idx',
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='is_latest_version',
            field=models.BooleanField(default=True, help_text='Is this the most recent version?'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, help_text='Original template if this is a versioned copy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.activitytemplate'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Template version number'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='version_notes',
            field=models.TextField(blank=True, help_text='Changes in this version'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_custom_overtime',
            field=models.BooleanField(default=False, help_text='Si el empleado tiene un multiplicador de overtime personalizado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Multiplicador para cálculo de horas extra (por defecto 1.50)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MATERIALES', 'Materiales'), ('COMIDA', 'Comida'), ('SEGURO', 'Seguro'), ('ALMACÉN', 'Almacén / Storage'), ('MANO_OBRA', 'Mano de obra'), ('OFICINA', 'Oficina'), ('OTRO', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when period was approved', null=True),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('paid', 'Pagado')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Q16.9: Validation errors for this period'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='adjusted_at',
            field=models.DateTimeField(blank=True, help_text='When adjustment occurred', null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who adjusted record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='adjustment_reason',
            field=models.TextField(blank=True, help_text='Reason for manual adjustment'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='expense',
            field=models.OneToOneField(blank=True, help_text='Linked expense for labor cost', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_record', to='core.expense'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='manually_adjusted',
            field=models.BooleanField(default=False, help_text='True if manually adjusted'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='missing_days',
            field=models.JSONField(blank=True, default=list, help_text='Dates with no time entries'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Net pay after deductions & tax', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Overtime hours (>40)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='overtime_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overtime rate override', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='project_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Hours by project id'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Regular hours (<=40)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='tax_withheld',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tax withholding', max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Motivo de cancelación proporcionado por el cliente'),
        ),
        migrations.AddIndex(
            model_name='activitytemplate',
            index=models.Index(fields=['category', 'is_active'], name='core_activi_categor_d42f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitytemplate',
            index=models.Index(fields=['is_latest_version'], name='core_activi_is_late_a80290_idx'),
        ),
        migrations.AddIndex(
            model_name='activitytemplate',
            index=models.Index(fields=['name', 'category'], name='core_activi_name_0c95e0_idx'),
        ),
    ]
