# Generated by Django 4.2.26 on 2025-11-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_add_activitytemplate_versioning_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedactivity',
            name='schedule_item',
            field=models.ForeignKey(blank=True, help_text='Link to schedule item (phase/milestone) if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scheduleitem'),
        ),
    ]
