# Generated by Django 4.2.26 on 2025-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_tasktemplate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tasktemplate',
            new_name='core_taskte_default_bbad76_idx',
            old_name='core_taskte_default_3b1f5a_idx',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='auto_weather',
            field=models.BooleanField(default=True, help_text='Si se auto‑rellena el clima (Módulo 30)'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='incomplete_reason',
            field=models.TextField(blank=True, help_text='Motivo si el plan quedó incompleto'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Plan diario marcado como completo'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='planned_tasks',
            field=models.ManyToManyField(blank=True, help_text='Tareas creadas desde plantillas para este día', related_name='planned_in_logs', to='core.task'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='planned_templates',
            field=models.ManyToManyField(blank=True, help_text='Plantillas previstas para instanciar tareas del día', related_name='daily_logs', to='core.tasktemplate'),
        ),
    ]
