# Generated by Django 4.2.26 on 2025-11-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_rename_core_taskte_default_3b1f5a_idx_core_taskte_default_bbad76_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(default='open-meteo', max_length=50)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conditions_text', models.CharField(blank=True, max_length=120)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('provider_url', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='core.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('project', 'date', 'source')},
            },
        ),
    ]
