# Generated by Django 4.2.26 on 2025-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_weathersnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10),
        ),
    ]
