# Generated by Django 4.2.26 on 2025-11-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_tasktemplate_default_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Tarea asociada para agregar horas trabajadas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core.task'),
        ),
    ]
