# Generated by Django 5.2.4 on 2025-11-25 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_timeentry_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ['-usage_count', '-created_at'], 'verbose_name': 'Plantilla de Tarea', 'verbose_name_plural': 'Plantillas de Tareas'},
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='category',
            field=models.CharField(choices=[('preparation', 'Preparación'), ('painting', 'Pintura'), ('finishing', 'Acabados'), ('inspection', 'Inspección'), ('cleanup', 'Limpieza'), ('materials', 'Materiales'), ('client', 'Cliente'), ('admin', 'Administrativo'), ('other', 'Otro')], default='other', help_text='Categoría para organizar plantillas', max_length=50),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite for quick access'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Last time this template was instantiated', null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='sop_reference',
            field=models.URLField(blank=True, help_text='Link to Standard Operating Procedure document'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Times this template has been used (analytics)'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['category'], name='core_taskte_categor_63c7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['-usage_count'], name='core_taskte_usage_c_9c2a03_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['is_favorite', '-usage_count'], name='core_taskte_is_favo_f2c9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['is_active', 'category'], name='core_taskte_is_acti_8c8969_idx'),
        ),
    ]
