# Generated by Django 5.2.4 on 2025-11-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_two_factor_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='twofactorprofile',
            new_name='core_twofac_enabled_b0d1ba_idx',
            old_name='core_twofac_enabled_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='DEPRECATED: usar amount_paid y total_amount; se eliminará tras migración de reportes.'),
        ),
    ]
