# Generated by Django 5.2.4 on 2025-11-26 01:12

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def normalize_material_request_statuses(apps, schema_editor):
    """
    Normaliza estados legacy de MaterialRequest:
    - 'submitted' -> 'pending' (deprecated mapping)
    - Loguea cada conversión para auditoría
    
    Parte de STATUS_VOCABULARY_SPEC.md fase R2.
    """
    MaterialRequest = apps.get_model('core', 'MaterialRequest')
    
    # Mapping según STATUS_COMPAT_MAP
    mappings = {
        'submitted': 'pending',
    }
    
    converted = 0
    for old_status, new_status in mappings.items():
        count = MaterialRequest.objects.filter(status=old_status).count()
        if count > 0:
            logger.info(f"Converting {count} MaterialRequest from '{old_status}' to '{new_status}'")
            MaterialRequest.objects.filter(status=old_status).update(status=new_status)
            converted += count
    
    if converted > 0:
        logger.info(f"MaterialRequest status normalization complete: {converted} records updated")
    else:
        logger.info("MaterialRequest status normalization: no legacy statuses found")


def reverse_normalize(apps, schema_editor):
    """
    Rollback: revertir 'pending' a 'submitted' solo si se puede identificar.
    En práctica, irreversible sin metadata adicional. Logging warning.
    """
    logger.warning("MaterialRequest status normalization rollback: no se puede revertir automáticamente sin tracking adicional")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_rename_core_twofac_enabled_idx_core_twofac_enabled_b0d1ba_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_material_request_statuses, reverse_normalize),
    ]

