# Generated by Django 5.2.4 on 2025-11-26 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_sitephoto_damage_and_accuracy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequestattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, help_text='Razón del fallo: invalid_password, user_not_found, account_locked, etc.', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='core_logina_usernam_f4a0b6_idx'), models.Index(fields=['ip_address', 'timestamp'], name='core_logina_ip_addr_22e0ac_idx'), models.Index(fields=['success', 'timestamp'], name='core_logina_success_9b0548_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Cached username in case user is deleted', max_length=150)),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('view', 'Visualizar'), ('approve', 'Aprobar'), ('reject', 'Rechazar'), ('export', 'Exportar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('password_change', 'Cambio de Contraseña')], max_length=30)),
                ('entity_type', models.CharField(choices=[('project', 'Proyecto'), ('task', 'Tarea'), ('invoice', 'Factura'), ('estimate', 'Estimación'), ('payment', 'Pago'), ('expense', 'Gasto'), ('inventory', 'Inventario'), ('damage', 'Reporte de Daño'), ('color', 'Muestra de Color'), ('user', 'Usuario'), ('permission', 'Permiso'), ('document', 'Documento'), ('system', 'Sistema')], max_length=30)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_repr', models.CharField(blank=True, help_text='String representation of entity', max_length=255)),
                ('old_values', models.JSONField(blank=True, help_text='Estado anterior (para updates/deletes)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Estado nuevo (para creates/updates)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la acción')),
                ('success', models.BooleanField(default=True, help_text='Si la acción fue exitosa')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'), models.Index(fields=['action', 'entity_type'], name='core_auditl_action_250d2a_idx'), models.Index(fields=['ip_address', 'timestamp'], name='core_auditl_ip_addr_1259d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('project_manager', 'Project Manager'), ('contractor', 'Contratista'), ('client', 'Cliente'), ('viewer', 'Visualizador')], max_length=30)),
                ('entity_type', models.CharField(choices=[('project', 'Proyecto'), ('task', 'Tarea'), ('invoice', 'Factura'), ('estimate', 'Estimación'), ('payment', 'Pago'), ('expense', 'Gasto'), ('inventory', 'Inventario'), ('damage', 'Reporte de Daño'), ('color', 'Muestra de Color'), ('document', 'Documento')], max_length=30)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, help_text='Fecha de inicio de permisos temporales', null=True)),
                ('effective_until', models.DateField(blank=True, help_text='Fecha de expiración de permisos temporales', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_project', models.ForeignKey(blank=True, help_text='Si se especifica, permisos se limitan a este proyecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_matrix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'entity_type'], name='core_permis_user_id_393267_idx'), models.Index(fields=['role', 'entity_type'], name='core_permis_role_496b91_idx')],
                'unique_together': {('user', 'role', 'entity_type', 'scope_project')},
            },
        ),
    ]
