# Generated by Django 5.2.4 on 2025-11-26 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_clientrequestattachment_id_loginattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('task', 'Task'), ('damage', 'Damage Report'), ('color_sample', 'Color Sample'), ('floor_plan', 'Floor Plan'), ('material', 'Material'), ('change_order', 'Change Order')], default='user', help_text='Type of entity referenced (task, damage, etc.)', max_length=30)),
                ('entity_id', models.IntegerField(blank=True, help_text='ID of referenced entity (optional)', null=True)),
                ('entity_label', models.CharField(blank=True, help_text='Display text for entity link (e.g., "Task #45: Paint walls")', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentioned_user', models.ForeignKey(blank=True, help_text='User mentioned (@username)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_mentions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='core.chatmessage')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['mentioned_user', 'created_at'], name='core_chatme_mention_3db7ae_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_chatme_entity__d6bc94_idx')],
            },
        ),
    ]
