# Generated by Django 5.2.4 on 2025-11-27 05:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_custom_overtime',
            field=models.BooleanField(default=False, help_text='Q16.11: True if employee has custom overtime rate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Q16.11: Overtime rate multiplier (typically 1.5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
