# Generated by Django 5.2.8 on 2025-11-28 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_add_project_code_and_manager_assignments"),
        ("signatures", "0002_add_project_code_and_manager_assignments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalSignature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("color_sample", "Color Sample"), ("change_order", "Change Order")],
                        help_text="Type of entity being signed",
                        max_length=50,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField(help_text="ID of the signed entity")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("signature_data", models.TextField(help_text="Base64-encoded signature canvas data")),
                ("document_snapshot", models.JSONField(help_text="JSON snapshot of document state at signing time")),
                ("signed_hash", models.CharField(help_text="SHA256 hash of document snapshot", max_length=64)),
                ("user_agent", models.TextField(blank=True)),
                ("geolocation", models.JSONField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_signature",
                    models.OneToOneField(
                        help_text="Link to the base signature model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_signature",
                        to="signatures.signature",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        help_text="User who created the signature",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="changeorder",
            name="digital_signature",
            field=models.ForeignKey(
                blank=True,
                help_text="Cryptographic signature for approval",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_order_signatures",
                to="core.digitalsignature",
            ),
        ),
        migrations.AddField(
            model_name="colorsample",
            name="digital_signature",
            field=models.ForeignKey(
                blank=True,
                help_text="Cryptographic signature for approval",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="color_sample_signatures",
                to="core.digitalsignature",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalsignature",
            index=models.Index(fields=["entity_type", "entity_id"], name="core_digita_entity__5b6287_idx"),
        ),
        migrations.AddIndex(
            model_name="digitalsignature",
            index=models.Index(fields=["signer", "timestamp"], name="core_digita_signer__1a8d15_idx"),
        ),
    ]
