# Generated by Django 5.2.4 on 2025-11-30 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_add_project_code_and_manager_assignments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("project_lead", "Project Lead"),
                            ("project_manager", "Project Manager"),
                            ("observer", "Observer"),
                            ("accounting", "Accounting"),
                            ("executive", "Executive"),
                        ],
                        default="project_lead",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone_direct", models.CharField(blank=True, max_length=20)),
                ("phone_mobile", models.CharField(blank=True, max_length=20)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone"), ("sms", "SMS"), ("app", "App")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("can_approve_change_orders", models.BooleanField(default=True, help_text="Can approve change orders")),
                ("can_view_financials", models.BooleanField(default=True, help_text="Can view financial information")),
                ("can_create_tasks", models.BooleanField(default=True, help_text="Can create tasks")),
                ("can_approve_colors", models.BooleanField(default=False, help_text="Can approve color samples")),
                ("receive_daily_reports", models.BooleanField(default=True, help_text="Receive daily project reports")),
                (
                    "receive_invoice_notifications",
                    models.BooleanField(default=True, help_text="Receive invoice notifications"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Base user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Contact",
                "verbose_name_plural": "Client Contacts",
                "db_table": "client_contacts",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="observers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other client contacts with read access",
                related_name="observer_projects",
                to="core.clientcontact",
                verbose_name="Observers",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Main client contact for this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_projects",
                to="core.clientcontact",
                verbose_name="Project Lead (Client)",
            ),
        ),
        migrations.CreateModel(
            name="ClientOrganization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Organization name (e.g., 'New West Partners')", max_length=255)),
                ("legal_name", models.CharField(blank=True, help_text="Legal name for invoicing", max_length=255)),
                ("tax_id", models.CharField(blank=True, help_text="EIN/Tax ID", max_length=50)),
                ("billing_address", models.TextField(help_text="Billing address")),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=50)),
                ("billing_zip", models.CharField(blank=True, max_length=20)),
                ("billing_email", models.EmailField(help_text="Email for invoices", max_length=254)),
                ("billing_phone", models.CharField(blank=True, max_length=20)),
                (
                    "payment_terms_days",
                    models.IntegerField(default=30, help_text="Payment terms in days (Net 30, Net 60, etc.)"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, help_text="Company logo", null=True, upload_to="client_organizations/logos/"
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Company website")),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Main billing contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_contact_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Organization",
                "verbose_name_plural": "Client Organizations",
                "db_table": "client_organizations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="clientcontact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent organization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="core.clientorganization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="billing_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="If part of a corporate client, select here",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.clientorganization",
                verbose_name="Billing Organization",
            ),
        ),
        migrations.AddIndex(
            model_name="clientorganization",
            index=models.Index(fields=["name"], name="client_orga_name_31bd78_idx"),
        ),
        migrations.AddIndex(
            model_name="clientorganization",
            index=models.Index(fields=["is_active"], name="client_orga_is_acti_9bd9a1_idx"),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(fields=["organization", "is_active"], name="client_cont_organiz_6d17f3_idx"),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(fields=["role"], name="client_cont_role_a5e17c_idx"),
        ),
    ]
