# Generated by Django 5.2.4 on 2025-11-30 07:01

from django.db import migrations


def migrate_existing_clients(apps, schema_editor):
    """Convert existing client users to ClientContact.

    This migration:
    1. Finds all users with Profile.role='client'
    2. Creates ClientContact for each
    3. Uses ClientProjectAccess to assign project_lead where appropriate
    """
    User = apps.get_model("auth", "User")
    ClientContact = apps.get_model("core", "ClientContact")
    Profile = apps.get_model("core", "Profile")
    Project = apps.get_model("core", "Project")
    ClientProjectAccess = apps.get_model("core", "ClientProjectAccess")

    # Find all client users
    client_profiles = Profile.objects.filter(role="client")

    for profile in client_profiles:
        user = profile.user

        # Skip if ClientContact already exists
        if ClientContact.objects.filter(user=user).exists():
            continue

        # Create ClientContact
        contact = ClientContact.objects.create(
            user=user,
            organization=None,  # Will be set manually if needed
            role="project_lead",
            job_title="",
            department="",
            phone_direct="",
            phone_mobile="",
            preferred_contact_method="email",
            can_approve_change_orders=True,
            can_view_financials=True,
            can_create_tasks=True,
            can_approve_colors=False,
            receive_daily_reports=True,
            receive_invoice_notifications=True,
            is_active=True,
        )

        # Find projects where this user has ClientProjectAccess
        project_accesses = ClientProjectAccess.objects.filter(user=user)
        for access in project_accesses:
            project = access.project
            # Only set project_lead if not already set
            if not project.project_lead_id:
                project.project_lead = contact
                project.save(update_fields=["project_lead"])


def reverse_migration(apps, schema_editor):
    """Reverse the migration by removing auto-created ClientContacts."""
    ClientContact = apps.get_model("core", "ClientContact")
    Project = apps.get_model("core", "Project")

    # Clear project_lead references first
    Project.objects.filter(project_lead__isnull=False).update(project_lead=None)

    # Note: We don't delete ClientContact records as they may have been
    # modified since creation. Manual cleanup may be needed.


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_add_client_organization_and_contact"),
    ]

    operations = [
        migrations.RunPython(migrate_existing_clients, reverse_migration),
    ]
