# Generated by Django 5.2.8 on 2025-11-28 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_digitalsignature_changeorder_digital_signature_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "method",
                    models.CharField(
                        choices=[("flat", "Flat Percentage"), ("tiered", "Tiered Brackets")],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "flat_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="% flat e.g. 12.50", max_digits=5, null=True
                    ),
                ),
                (
                    "tiers",
                    models.JSONField(
                        blank=True, default=list, help_text="Tier list: [{'up_to': 1000, 'rate': 10.0}, ...]"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="locked",
            field=models.BooleanField(
                default=False, help_text="Gap B: When true, no further adjustments/payments allowed"
            ),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="recomputed_at",
            field=models.DateTimeField(blank=True, help_text="Gap B: Last time period was recomputed", null=True),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="split_expenses_by_project",
            field=models.BooleanField(default=False, help_text="Gap B: Generate per-project expenses on recompute"),
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="recalculated_at",
            field=models.DateTimeField(blank=True, help_text="Gap B: Last time this record was recomputed", null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="tax_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Gap B: Tax profile used to compute tax_withheld",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.taxprofile",
            ),
        ),
        migrations.CreateModel(
            name="PayrollRecordAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("changes", models.JSONField(help_text="Field diffs: {field: {old, new}}")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "payroll_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="core.payrollrecord"
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [models.Index(fields=["payroll_record"], name="core_payrol_payroll_69f156_idx")],
            },
        ),
    ]
