# Generated by Django 5.2.8 on 2025-11-29 00:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_add_human_readable_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeorder",
            name="labor_rate_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarifa por hora específica para este CO. Si está vacío, usa default_co_labor_rate del proyecto",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="changeorder",
            name="material_markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Porcentaje de markup en materiales (por defecto 15%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="default_co_labor_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Tarifa por hora por defecto para Change Orders en este proyecto",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="billable_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Tarifa cobrada (según CO o proyecto) al momento de esta entrada",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="cost_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Costo del empleado (hourly_rate) al momento de esta entrada",
                max_digits=6,
                null=True,
            ),
        ),
    ]
