# Generated by Django 5.2.8 on 2025-11-29 06:08

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_add_financial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="paid_by_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Empleado que pagó de su bolsillo y requiere reembolso",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses_paid",
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="reimbursement_date",
            field=models.DateField(blank=True, help_text="Fecha en que se reembolsó al empleado", null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="reimbursement_reference",
            field=models.CharField(
                blank=True, help_text="Número de cheque o referencia de transferencia", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="reimbursement_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente Reembolso"),
                    ("paid_in_payroll", "Pagado en Nómina"),
                    ("paid_direct", "Pagado Directamente"),
                    ("not_applicable", "No Aplica"),
                ],
                default="not_applicable",
                help_text="Estado del reembolso si fue pagado por empleado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("standard", "Por Items"), ("deposit", "Anticipo/Porcentaje"), ("final", "Cierre")],
                default="standard",
                help_text="Tipo de factura: Items, Anticipo o Cierre final",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_draft_for_review",
            field=models.BooleanField(
                default=False, help_text="True si es borrador de PM en entrenamiento que requiere revisión de Admin"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="retention_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Monto de retención contractual (oculto en forms por ahora)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="planpin",
            name="is_visible",
            field=models.BooleanField(default=True, help_text="False para ocultar pin completado (higiene de planos)"),
        ),
        migrations.AddField(
            model_name="planpin",
            name="owner_role",
            field=models.CharField(
                blank=True, help_text="Rol del creador para proteger pines del Designer", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_finishes",
            field=models.JSONField(
                blank=True,
                help_text="Registro de acabados aprobados por ubicación {room: {finish_type: {details}}}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_archived_for_pm",
            field=models.BooleanField(
                default=False,
                help_text="Si es True, el proyecto no aparece en dashboard de PM pero sigue activo para Admin",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="material_markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Porcentaje de markup para materiales en este proyecto (default 15%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="projectinventory",
            name="reserved_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Cantidad reservada para tareas futuras (no disponible para consumo)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="checklist",
            field=models.JSONField(
                blank=True, help_text="Checklist heredado de SOPs: [{item: 'texto', checked: false}, ...]", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_photo",
            field=models.ImageField(
                blank=True, help_text="Foto de cierre al completar tarea", null=True, upload_to="tasks/completion/"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="initial_photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Referencia a pin con foto inicial del área",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks_initial",
                to="core.planpin",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_client_responsibility",
            field=models.BooleanField(
                default=False,
                help_text="True si la responsabilidad es del cliente (ej: aprobar color, entregar llaves)",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_subtask",
            field=models.BooleanField(default=False, help_text="True si esta tarea es una subtarea de otra"),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Tarea padre si es subtarea",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="core.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress_percent",
            field=models.IntegerField(default=0, help_text="Porcentaje de progreso (0-100)"),
        ),
        migrations.AddField(
            model_name="task",
            name="schedule_weight",
            field=models.IntegerField(
                default=50,
                help_text="Peso en el scheduler (0-100). Mayor peso = mayor prioridad en algoritmo de planificación",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("MATERIALES", "Materiales"),
                    ("COMIDA", "Comida"),
                    ("SEGURO", "Seguro"),
                    ("ALMACÉN", "Almacén / Storage"),
                    ("MANO_OBRA", "Mano de obra"),
                    ("OFICINA", "Oficina"),
                    ("HERRAMIENTAS", "Herramientas"),
                    ("OTRO", "Otro"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="planpin",
            name="pin_type",
            field=models.CharField(
                choices=[
                    ("note", "Nota"),
                    ("task", "Tarea"),
                    ("touchup", "Touch-up"),
                    ("color", "Color"),
                    ("info", "Información"),
                    ("hazard", "Peligro"),
                    ("alert", "Alerta"),
                    ("damage", "Daño"),
                    ("leftover", "Sobrante de Material"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
