# Generated by Django 5.2.8 on 2025-11-29 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_final_architecture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rfi",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="rfi",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dailylogphoto",
            name="is_public",
            field=models.BooleanField(default=True, help_text="Visible para cliente en reportes sanitizados"),
        ),
        migrations.AlterField(
            model_name="chatchannel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("general_client", "Cliente - General"),
                    ("design", "Diseño"),
                    ("field_supervision", "Supervisión de Campo"),
                    ("internal_team", "Equipo Interno"),
                    ("direct", "Directo"),
                ],
                default="internal_team",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MeetingMinute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("attendees", models.TextField(blank=True, help_text="Lista de asistentes")),
                ("content", models.TextField(help_text="Contenido enriquecido / markdown")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="meeting_minutes", to="core.project"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.RemoveField(
            model_name="rfi",
            name="answered_at",
        ),
        migrations.RemoveField(
            model_name="rfi",
            name="created_at",
        ),
    ]
