# Generated by Django 5.2.8 on 2025-11-29 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_alter_rfi_options_alter_rfi_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rfi",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="rfi",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rfi",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="rfi",
            unique_together={("project", "number")},
        ),
    ]
