# Generated by Django 5.2.8 on 2025-11-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_alter_rfi_options_rfi_answered_at_rfi_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatchannel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("general_client", "Cliente - General"),
                    ("design", "Diseño"),
                    ("field_supervision", "Supervisión de Campo"),
                    ("internal_team", "Equipo Interno"),
                    ("direct", "Directo"),
                    ("group", "Grupo (Legacy)"),
                    ("general", "General (Legacy)"),
                ],
                default="internal_team",
                max_length=20,
            ),
        ),
    ]
