# Generated by Django 5.2.8 on 2025-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_project_is_archived_alter_expense_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rejections_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="is_visible_to_client",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("En Progreso", "En Progreso"),
                    ("En Revisión", "En Revisión"),
                    ("Completada", "Completada"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Pendiente",
                max_length=50,
            ),
        ),
    ]
