# Generated by Django 5.2.8 on 2025-11-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_time_and_materials_changeorder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proposalemaillog",
            options={
                "ordering": ["-sent_at"],
                "verbose_name": "Proposal Email Log",
                "verbose_name_plural": "Proposal Email Logs",
            },
        ),
    ]
