# Generated by Django 5.2.8 on 2025-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0104_alter_proposalemaillog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeorder",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                help_text="Customer signature image from canvas",
                null=True,
                upload_to="signatures/change_orders/",
            ),
        ),
        migrations.AddField(
            model_name="changeorder",
            name="signed_at",
            field=models.DateTimeField(blank=True, help_text="Timestamp when signature was captured", null=True),
        ),
        migrations.AddField(
            model_name="changeorder",
            name="signed_by",
            field=models.CharField(blank=True, help_text="Name of person who signed", max_length=255, null=True),
        ),
    ]
