# Generated by Django 5.2.8 on 2025-11-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_changeorder_audit_signature_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day this focus session is for')),
                ('energy_level', models.IntegerField(default=5, help_text='Self-reported energy level (1-10)')),
                ('notes', models.TextField(blank=True, help_text='General notes, reflections, or insights for the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Focus Session',
                'verbose_name_plural': 'Daily Focus Sessions',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FocusTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('is_high_impact', models.BooleanField(default=False, help_text='Is this part of the critical 20% that produces 80% of results?')),
                ('impact_reason', models.TextField(blank=True, help_text='Why is this task high impact? What results will it produce?')),
                ('is_frog', models.BooleanField(default=False, help_text='Is this THE most important/hardest task of the day?')),
                ('checklist', models.JSONField(blank=True, default=list, help_text="List of micro-actions/sub-steps. Format: [{'text': 'Step 1', 'done': false}, ...]")),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='When to start this task (time blocking)', null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='When to end this task (time blocking)', null=True)),
                ('calendar_token', models.UUIDField(blank=True, default=None, editable=False, help_text='Unique secure token for iCal feed access', null=True, unique=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_tasks', to='core.dailyfocussession')),
            ],
            options={
                'verbose_name': 'Focus Task',
                'verbose_name_plural': 'Focus Tasks',
                'ordering': ['order', '-is_frog', '-is_high_impact', 'created_at'],
            },
        ),
    ]
