# Generated by Django 4.2.26 on 2025-11-30 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_add_strategic_planner_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focustask',
            name='calendar_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique secure token for iCal feed access', unique=True),
        ),
        migrations.AlterField(
            model_name='poweraction',
            name='ical_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for iCal sync', unique=True),
        ),
    ]
