# Generated by Django 4.2.26 on 2025-11-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_migrate_existing_clients_to_contacts'),
        ('core', '0110_alter_focustask_calendar_token_and_more'),
    ]

    operations = [
    ]
