# Generated by Django 4.2.26 on 2025-12-01 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0113_alter_expense_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('category', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('task', 'Task'), ('chat', 'Chat')], default='info', max_length=20, verbose_name='Category')),
                ('url', models.CharField(blank=True, help_text='Link to relevant page', max_length=500, verbose_name='URL')),
                ('read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('delivered_via_websocket', models.BooleanField(default=False, verbose_name='Delivered via WebSocket')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(db_index=True, default=False, verbose_name='Is Online')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last WebSocket heartbeat received', null=True, verbose_name='Last Heartbeat')),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=20, verbose_name='Device Type')),
                ('connection_count', models.IntegerField(default=0, help_text='Number of active WebSocket connections', verbose_name='Active Connections')),
            ],
            options={
                'verbose_name': 'User Status',
                'verbose_name_plural': 'User Statuses',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Read By'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['channel', '-created_at'], name='core_chatme_channel_2e200e_idx'),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='userstatus',
            index=models.Index(fields=['is_online', '-last_seen'], name='core_userst_is_onli_9e1ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_f49873_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'read', '-created_at'], name='core_notifi_user_id_6b6753_idx'),
        ),
    ]
