# Generated by Django 5.2.8 on 2025-12-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_add_pricing_type_changeorder'),
        ('core', '0116_add_push_subscription_model'),
    ]

    operations = [
    ]
