# Generated by Django 5.2.8 on 2025-12-03 19:23

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_fix_employee_key_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='labor_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa por hora específica para este CO. Si está vacío, usa default_co_labor_rate del proyecto', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='material_markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje de markup en materiales (por defecto 15%)', max_digits=5),
        ),
        # FIXED: Add employee_key field properly since 0120 used raw SQL which doesn't update migration state
        # Use AddField with state_operations to ensure Django tracks it
        migrations.AddField(
            model_name='employee',
            name='employee_key',
            field=models.CharField(
                blank=True,
                editable=False,
                help_text='Código único del empleado (EMP-001, EMP-002...). Se genera automáticamente.',
                max_length=20,
                unique=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='default_co_labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Tarifa por hora por defecto para Change Orders en este proyecto', max_digits=6),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='billable_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Tarifa cobrada (según CO o proyecto) al momento de esta entrada', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='cost_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Costo del empleado (hourly_rate) al momento de esta entrada', max_digits=6, null=True),
        ),
    ]
