# Generated by Django 4.2.26 on 2025-12-06 22:47

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion
import uuid


def column_exists(table, column):
    """Check if a column exists in a table."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
        """, [table, column])
        return cursor.fetchone() is not None


def table_exists(table):
    """Check if a table exists."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT table_name FROM information_schema.tables
            WHERE table_name = %s
        """, [table])
        return cursor.fetchone() is not None


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0123_merge_20251203_1348'),
    ]

    operations = [
        # Only create DailyFocusSession if it doesn't exist
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "core_dailyfocussession" (
                "id" bigserial NOT NULL PRIMARY KEY,
                "date" date NOT NULL,
                "energy_level" integer NOT NULL DEFAULT 5,
                "notes" text NOT NULL DEFAULT '',
                "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
                "updated_at" timestamp with time zone NOT NULL DEFAULT NOW(),
                "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                UNIQUE ("user_id", "date")
            );
            CREATE INDEX IF NOT EXISTS "core_dailyfocussession_user_id_idx" ON "core_dailyfocussession" ("user_id");
            """,
            reverse_sql="DROP TABLE IF EXISTS core_dailyfocussession CASCADE;",
        ),
        # Only add employee_key if it doesn't exist
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'core_employee' AND column_name = 'employee_key'
                ) THEN
                    ALTER TABLE core_employee ADD COLUMN employee_key VARCHAR(20) UNIQUE;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE core_employee DROP COLUMN IF EXISTS employee_key;",
        ),
        # AlterField is safe - it will just update if needed
        migrations.AlterField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        # Only create FocusTask if it doesn't exist  
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "core_focustask" (
                "id" bigserial NOT NULL PRIMARY KEY,
                "title" varchar(255) NOT NULL,
                "description" text NOT NULL DEFAULT '',
                "is_high_impact" boolean NOT NULL DEFAULT false,
                "impact_reason" text NOT NULL DEFAULT '',
                "is_frog" boolean NOT NULL DEFAULT false,
                "checklist" jsonb NOT NULL DEFAULT '[]',
                "scheduled_start" timestamp with time zone,
                "scheduled_end" timestamp with time zone,
                "calendar_token" uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
                "is_completed" boolean NOT NULL DEFAULT false,
                "completed_at" timestamp with time zone,
                "order" integer NOT NULL DEFAULT 0,
                "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
                "updated_at" timestamp with time zone NOT NULL DEFAULT NOW(),
                "session_id" bigint NOT NULL REFERENCES "core_dailyfocussession" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            CREATE INDEX IF NOT EXISTS "core_focustask_session_id_idx" ON "core_focustask" ("session_id");
            CREATE INDEX IF NOT EXISTS "core_focustask_calendar_token_idx" ON "core_focustask" ("calendar_token");
            """,
            reverse_sql="DROP TABLE IF EXISTS core_focustask CASCADE;",
        ),
    ]
