# Generated by Django 4.2.26 on 2025-12-07 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0124_dailyfocussession_employee_employee_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day this focus session is for')),
                ('energy_level', models.IntegerField(default=5, help_text='Self-reported energy level (1-10)')),
                ('notes', models.TextField(blank=True, help_text='General notes, reflections, or insights for the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Focus Session',
                'verbose_name_plural': 'Daily Focus Sessions',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyRitualSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day this ritual is for')),
                ('physiology_check', models.BooleanField(default=False, help_text='Did you do the priming exercise? (Stand up, breathe, move)')),
                ('gratitude_entries', models.JSONField(blank=True, default=list, help_text="List of 3 things you're grateful for. Format: ['Item 1', 'Item 2', 'Item 3']")),
                ('daily_intention', models.TextField(blank=True, help_text='Your main focus/intention for today')),
                ('energy_level', models.IntegerField(default=5, help_text='Self-reported energy level (1-10)')),
                ('habits_checked', models.JSONField(blank=True, default=list, help_text='List of habit IDs checked/committed to today. Format: [1, 2, 3]')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the ritual was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ritual_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Ritual Session',
                'verbose_name_plural': 'Daily Ritual Sessions',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExecutiveHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Habit name (e.g., 'Morning Gym', 'Read 30 minutes')", max_length=255)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='How often should this be done?', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this habit currently being tracked?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Executive Habit',
                'verbose_name_plural': 'Executive Habits',
                'ordering': ['frequency', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LifeVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The goal/vision (e.g., 'Financial Freedom', 'Market Leadership')", max_length=255)),
                ('scope', models.CharField(choices=[('PERSONAL', 'Personal Life'), ('BUSINESS', 'Business/Career')], help_text='Is this a personal or business goal?', max_length=20)),
                ('deep_why', models.TextField(help_text='The EMOTIONAL anchor - WHY does this matter? What will it give you?')),
                ('deadline', models.DateField(blank=True, help_text='Target completion date (if applicable)', null=True)),
                ('progress_pct', models.IntegerField(default=0, help_text='Estimated progress (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_visions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Life Vision',
                'verbose_name_plural': 'Life Visions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_key',
            field=models.CharField(blank=True, editable=False, help_text='Código único del empleado (EMP-001, EMP-002...). Se genera automáticamente.', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='PowerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Strategic action title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('is_80_20', models.BooleanField(default=False, help_text='Is this a HIGH IMPACT action (top 20%)?')),
                ('impact_reason', models.TextField(blank=True, help_text='WHY is this high impact? What will it advance?')),
                ('is_frog', models.BooleanField(default=False, help_text='Is this THE #1 most important action today?')),
                ('micro_steps', models.JSONField(blank=True, default=list, help_text="Checklist of micro-actions. Format: [{'text': 'Step 1', 'done': false}, ...]")),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='When to start (time blocking)', null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='When to end (time blocking)', null=True)),
                ('ical_uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for iCal sync', unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft/Inbox'), ('SCHEDULED', 'Scheduled'), ('DONE', 'Completed')], default='DRAFT', help_text='Current status', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When completed', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_vision', models.ForeignKey(blank=True, help_text='Which Life Vision does this advance?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_actions', to='core.lifevision')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_actions', to='core.dailyritualsession')),
            ],
            options={
                'verbose_name': 'Power Action',
                'verbose_name_plural': 'Power Actions',
                'ordering': ['order', '-is_frog', '-is_80_20', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('is_high_impact', models.BooleanField(default=False, help_text='Is this part of the critical 20% that produces 80% of results?')),
                ('impact_reason', models.TextField(blank=True, help_text='Why is this task high impact? What results will it produce?')),
                ('is_frog', models.BooleanField(default=False, help_text='Is this THE most important/hardest task of the day?')),
                ('checklist', models.JSONField(blank=True, default=list, help_text="List of micro-actions/sub-steps. Format: [{'text': 'Step 1', 'done': false}, ...]")),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='When to start this task (time blocking)', null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='When to end this task (time blocking)', null=True)),
                ('calendar_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique secure token for iCal feed access', unique=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_tasks', to='core.dailyfocussession')),
            ],
            options={
                'verbose_name': 'Focus Task',
                'verbose_name_plural': 'Focus Tasks',
                'ordering': ['order', '-is_frog', '-is_high_impact', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Optional notes about completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.executivehabit')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit_completions', to='core.dailyritualsession')),
            ],
            options={
                'verbose_name': 'Habit Completion',
                'verbose_name_plural': 'Habit Completions',
                'ordering': ['-completed_date'],
                'unique_together': {('habit', 'completed_date')},
            },
        ),
    ]
