# Generated by Django 5.2.8 on 2025-12-07 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_dailyfocussession_dailyritualsession_executivehabit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view_mode', models.CharField(choices=[('compact', 'Compact'), ('detailed', 'Detailed'), ('calendar', 'Calendar')], default='detailed', max_length=20)),
                ('days_visible', models.IntegerField(default=7, help_text='Number of days to show in timeline')),
                ('auto_scroll_today', models.BooleanField(default=True, help_text="Auto-scroll to today's date")),
                ('show_ai_suggestions', models.BooleanField(default=True, help_text='Show AI suggestions panel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timeline View Preference',
                'verbose_name_plural': 'Timeline View Preferences',
                'db_table': 'timeline_views',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('material', 'Material Check'), ('employee', 'Employee Check'), ('schedule', 'Schedule Check'), ('safety', 'Safety Check'), ('full', 'Full Analysis')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('findings', models.JSONField(default=dict, help_text='Analysis results in JSON format')),
                ('auto_actions_taken', models.JSONField(default=list, help_text='List of automatic actions taken (activities created, etc.)')),
                ('user_feedback', models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('wrong', 'Wrong')], max_length=20, null=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='core.dailyplan')),
            ],
            options={
                'verbose_name': 'AI Analysis Log',
                'verbose_name_plural': 'AI Analysis Logs',
                'db_table': 'ai_analysis_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['daily_plan', '-timestamp'], name='ai_analysis_daily_p_6051b7_idx'), models.Index(fields=['analysis_type'], name='ai_analysis_analysi_460e13_idx')],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('missing_material', 'Missing Material'), ('employee_conflict', 'Employee Conflict'), ('task_dependency', 'Task Dependency'), ('time_issue', 'Time Issue'), ('safety_concern', 'Safety Concern'), ('optimization', 'Optimization'), ('missing_sop', 'Missing SOP'), ('weather_alert', 'Weather Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField(help_text='Recommended action to resolve')),
                ('auto_fixable', models.BooleanField(default=False, help_text='Can AI automatically fix this?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('auto_fixed', 'Auto Fixed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='core.dailyplan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Suggestion',
                'verbose_name_plural': 'AI Suggestions',
                'db_table': 'ai_suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['daily_plan', 'status'], name='ai_suggesti_daily_p_6a0f7f_idx'), models.Index(fields=['severity', 'status'], name='ai_suggesti_severit_755865_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_commands/%Y/%m/')),
                ('transcription', models.TextField(help_text='Speech-to-text result')),
                ('parsed_command', models.JSONField(default=dict, help_text='Parsed command structure')),
                ('execution_result', models.JSONField(default=dict, help_text='Result of command execution')),
                ('success', models.BooleanField(default=False, help_text='Was command executed successfully?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('daily_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_commands', to='core.dailyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Command',
                'verbose_name_plural': 'Voice Commands',
                'db_table': 'voice_commands',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='voice_comma_user_id_efc39b_idx'), models.Index(fields=['success'], name='voice_comma_success_7651b1_idx')],
            },
        ),
    ]
