# Generated by Django 5.2.8 on 2025-12-07 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_add_ai_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMBlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha bloqueada')),
                ('reason', models.CharField(choices=[('vacation', 'Vacaciones'), ('personal', 'Personal'), ('sick', 'Enfermedad'), ('training', 'Capacitación'), ('other', 'Otro')], default='vacation', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('is_full_day', models.BooleanField(default=True, help_text='Día completo o parcial')),
                ('start_time', models.TimeField(blank=True, help_text='Hora de inicio si es parcial', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Hora de fin si es parcial', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pm', models.ForeignKey(help_text='Project Manager que bloquea el día', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PM Blocked Day',
                'verbose_name_plural': 'PM Blocked Days',
                'db_table': 'pm_blocked_days',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['pm', 'date'], name='pm_blocked__pm_id_19f8da_idx'), models.Index(fields=['date'], name='pm_blocked__date_3c2f03_idx')],
                'unique_together': {('pm', 'date')},
            },
        ),
    ]
