# Generated by Django 4.2.26 on 2025-12-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_add_pm_blocked_day_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('employee', 'Employee'), ('project_manager', 'Project Manager'), ('client', 'Client'), ('designer', 'Designer'), ('superintendent', 'Superintendent')], max_length=20),
        ),
    ]
