# Generated by Django 4.2.26 on 2025-12-10 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0128_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicPlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range_start', models.DateField(help_text='First day being planned (e.g., Dec 16)', verbose_name='Start Date')),
                ('date_range_end', models.DateField(help_text='Last day being planned (e.g., Dec 20)', verbose_name='End Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REQUIRES_CHANGES', 'Requires Changes')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='General notes about this planning session', verbose_name='Planning Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('exported_to_daily_plan', models.BooleanField(default=False, help_text='Has this plan been exported to Daily Plan system?', verbose_name='Exported to Daily Plan')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='Export Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_strategic_plans', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('project', models.ForeignKey(help_text='Which project this planning is for', on_delete=django.db.models.deletion.CASCADE, related_name='strategic_planning_sessions', to='core.project', verbose_name='Project')),
                ('user', models.ForeignKey(help_text='PM or admin who created this planning session', on_delete=django.db.models.deletion.CASCADE, related_name='strategic_planning_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Strategic Planning Session',
                'verbose_name_plural': 'Strategic Planning Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategicDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(help_text='The specific day this plan is for', verbose_name='Target Date')),
                ('notes', models.TextField(blank=True, help_text="Specific notes about this day's work", verbose_name='Day Notes')),
                ('estimated_total_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated hours for all work on this day', max_digits=6, null=True, verbose_name='Estimated Total Hours')),
                ('linked_schedule_item', models.ForeignKey(blank=True, help_text='Optional: Link to existing calendar item (e.g., "Exterior Painting - 15 days")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_days', to='core.scheduleitem', verbose_name='Linked Schedule Item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.strategicplanningsession', verbose_name='Planning Session')),
            ],
            options={
                'verbose_name': 'Strategic Day',
                'verbose_name_plural': 'Strategic Days',
                'ordering': ['target_date'],
            },
        ),
        migrations.AddIndex(
            model_name='strategicplanningsession',
            index=models.Index(fields=['project', 'date_range_start'], name='core_strate_project_b61939_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicplanningsession',
            index=models.Index(fields=['status'], name='core_strate_status_bdf6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicplanningsession',
            index=models.Index(fields=['user', '-created_at'], name='core_strate_user_id_fa57a2_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicday',
            index=models.Index(fields=['session', 'target_date'], name='core_strate_session_006675_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategicday',
            unique_together={('session', 'target_date')},
        ),
    ]
