# Generated by Django 4.2.26 on 2025-12-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_strategicplanningsession_strategicday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What work needs to be done? (e.g., "Install kitchen cabinets")', max_length=255, verbose_name='Item Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of this work item', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the day (0, 1, 2...)', verbose_name='Order')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical - Must Complete'), ('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated hours for this item (sum of all tasks)', max_digits=6, null=True, verbose_name='Estimated Hours')),
                ('location_area', models.CharField(blank=True, help_text='Where will this work happen? (e.g., "Kitchen", "Living Room", "Exterior")', max_length=100, verbose_name='Location/Area')),
                ('exported_to_daily_plan', models.BooleanField(default=False, verbose_name='Exported to Daily Plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Which employees will work on this item?', related_name='strategic_items', to='core.employee', verbose_name='Assigned To')),
                ('linked_activity_template', models.ForeignKey(blank=True, help_text='Optional: Use existing activity template as reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_items', to='core.activitytemplate', verbose_name='Linked Activity Template')),
                ('strategic_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.strategicday', verbose_name='Strategic Day')),
            ],
            options={
                'verbose_name': 'Strategic Item',
                'verbose_name_plural': 'Strategic Items',
                'ordering': ['strategic_day', 'order', 'priority'],
                'indexes': [models.Index(fields=['strategic_day', 'order'], name='core_strate_strateg_515082_idx'), models.Index(fields=['priority'], name='core_strate_priorit_2460c7_idx'), models.Index(fields=['-created_at'], name='core_strate_created_b01a91_idx')],
            },
        ),
    ]
