# Generated by Django 4.2.26 on 2025-12-10 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_strategicitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Actionable task description (e.g., "Install upper cabinets")', max_length=255, verbose_name='Task Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order within the item', verbose_name='Order')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated time to complete this specific task', max_digits=5, verbose_name='Estimated Hours')),
                ('exported_to_daily_plan', models.BooleanField(default=False, verbose_name='Exported to Daily Plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Override item assignment for this specific task (optional)', related_name='strategic_tasks', to='core.employee', verbose_name='Assigned To (Override)')),
                ('linked_task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_tasks', to='core.tasktemplate', verbose_name='Linked Task Template')),
                ('strategic_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.strategicitem', verbose_name='Strategic Item')),
            ],
            options={
                'verbose_name': 'Strategic Task',
                'verbose_name_plural': 'Strategic Tasks',
                'ordering': ['strategic_item', 'order'],
                'indexes': [models.Index(fields=['strategic_item', 'order'], name='core_strate_strateg_f4fbd2_idx')],
            },
        ),
    ]
