# Generated by Django 4.2.26 on 2025-12-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_strategictask'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicSubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Micro-step description (e.g., "Locate studs")', max_length=255, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Checklist order', verbose_name='Order')),
                ('exported_to_daily_plan', models.BooleanField(default=False, verbose_name='Exported to Daily Plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('strategic_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.strategictask', verbose_name='Strategic Task')),
            ],
            options={
                'verbose_name': 'Strategic Subtask',
                'verbose_name_plural': 'Strategic Subtasks',
                'ordering': ['strategic_task', 'order'],
                'indexes': [models.Index(fields=['strategic_task', 'order'], name='core_strate_strateg_a045ff_idx')],
            },
        ),
    ]
