# Generated by Django 4.2.26 on 2025-12-10 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_strategicsubtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of material needed (e.g., "2x4 Lumber")', max_length=255, verbose_name='Material Name')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='How much is needed?', max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(help_text='Unit of measure (e.g., "Each", "Box", "Gallon")', max_length=50, verbose_name='Unit')),
                ('notes', models.TextField(blank=True, help_text='Specific details (brand, color, size)', verbose_name='Notes')),
                ('is_on_hand', models.BooleanField(default=False, help_text='Do we already have this material available?', verbose_name='Is On Hand?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('linked_catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_requirements', to='core.materialcatalog', verbose_name='Catalog Item')),
                ('linked_inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_requirements', to='core.inventoryitem', verbose_name='Inventory Item')),
                ('strategic_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='core.strategicitem', verbose_name='Strategic Item')),
            ],
            options={
                'verbose_name': 'Strategic Material Requirement',
                'verbose_name_plural': 'Strategic Material Requirements',
                'indexes': [models.Index(fields=['strategic_item'], name='core_strate_strateg_6be77c_idx'), models.Index(fields=['is_on_hand'], name='core_strate_is_on_h_73286c_idx')],
            },
        ),
    ]
