# Generated by Django 4.2.26 on 2025-12-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_strategicmaterialrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish to Start'), ('SS', 'Start to Start'), ('FF', 'Finish to Finish'), ('SF', 'Start to Finish')], default='FS', max_length=2, verbose_name='Dependency Type')),
                ('lag_days', models.IntegerField(default=0, help_text='Optional delay between items (e.g., 1 day for drying)', verbose_name='Lag (Days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(help_text='The item that must be completed first', on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='core.strategicitem', verbose_name='Predecessor Item')),
                ('successor', models.ForeignKey(help_text='The item that is waiting for the predecessor', on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='core.strategicitem', verbose_name='Successor Item')),
            ],
            options={
                'verbose_name': 'Strategic Dependency',
                'verbose_name_plural': 'Strategic Dependencies',
                'indexes': [models.Index(fields=['predecessor'], name='core_strate_predece_4bf2c9_idx'), models.Index(fields=['successor'], name='core_strate_success_9dc518_idx')],
                'unique_together': {('predecessor', 'successor')},
            },
        ),
    ]
