# Generated by Django 4.2.26 on 2025-12-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_strategicdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedactivity',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Scheduled end time', null=True),
        ),
        migrations.AddField(
            model_name='plannedactivity',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent activity for nesting (Item -> Task -> Subtask)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='core.plannedactivity'),
        ),
        migrations.AddField(
            model_name='plannedactivity',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Scheduled start time', null=True),
        ),
    ]
