# Generated by Django 4.2.26 on 2025-12-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_plannedactivity_end_time_plannedactivity_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicitem',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='How many days will this item take? Used for Gantt view.', verbose_name='Duration (Days)'),
        ),
    ]
