# Generated by Django 5.2.8 on 2025-12-14 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_strategicitem_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('task', 'Task'), ('milestone', 'Milestone'), ('weather_dependent', 'Weather Dependent'), ('maintenance', 'Maintenance')], default='task', max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('team', 'Team'), ('private', 'Private')], default='team', max_length=16)),
                ('ai_conflicts', models.JSONField(blank=True, default=list)),
                ('ai_recommendations', models.JSONField(blank=True, default=list)),
                ('ai_risk_level', models.CharField(blank=True, default='', max_length=16)),
                ('sync_status', models.CharField(blank=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='core.calendarevent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.project')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
