# Generated by ChatGPT on 2025-12-15
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0139_meetingminute_restore"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("MORNING", "Mañana"), ("AFTERNOON", "Tarde"), ("FULL_DAY", "Día completo")],
                        default="FULL_DAY",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_resource_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_assignments",
                        to="core.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_assignments",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee_id"],
                "unique_together": {("employee", "date", "shift")},
            },
        ),
    ]
