# Generated by ChatGPT on 2025-12-17
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0140_resourceassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulePhaseV2",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("color", models.CharField(default="#4F46E5", max_length=32)),
                ("order", models.IntegerField(default=0)),
                (
                    "allow_sunday",
                    models.BooleanField(
                        default=False, help_text="Permitir trabajo en domingo para esta fase (por defecto se bloquea)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gantt_phases",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_phases_v2",
                "ordering": ["project_id", "order", "id"],
                "unique_together": {("project", "name")},
                "indexes": [models.Index(fields=["project", "order"], name="core_phase_v2_project_order_idx")],
            },
        ),
        migrations.CreateModel(
            name="ScheduleItemV2",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "color",
                    models.CharField(default="#22D3EE", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("in_progress", "En progreso"),
                            ("blocked", "Bloqueado"),
                            ("done", "Completado"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0, help_text="0-100")),
                ("order", models.IntegerField(default=0)),
                (
                    "is_milestone",
                    models.BooleanField(
                        default=False, help_text="Si es hito, start=end y se muestra como diamante"
                    ),
                ),
                (
                    "allow_sunday_override",
                    models.BooleanField(
                        default=False,
                        help_text="Permitir trabajo en domingo solo para este item (override de la fase/proyecto)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gantt_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.schedulephasev2",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gantt_items",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_items_v2",
                "ordering": ["project_id", "phase_id", "order", "id"],
                "indexes": [
                    models.Index(fields=["project", "phase"], name="core_item_v2_project_phase_idx"),
                    models.Index(fields=["project", "start_date"], name="core_item_v2_project_start_idx"),
                    models.Index(fields=["project", "end_date"], name="core_item_v2_project_end_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduleTaskV2",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En progreso"),
                            ("blocked", "Bloqueada"),
                            ("done", "Completada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.scheduleitemv2",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_tasks_v2",
                "ordering": ["item_id", "order", "id"],
                "indexes": [models.Index(fields=["item", "order"], name="core_task_v2_item_order_idx")],
            },
        ),
        migrations.CreateModel(
            name="ScheduleDependencyV2",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dependency_type",
                    models.CharField(choices=[("FS", "Finish to Start")], default="FS", max_length=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_dependencies",
                        to="core.scheduleitemv2",
                    ),
                ),
                (
                    "target_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_dependencies",
                        to="core.scheduleitemv2",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_dependencies_v2",
                "ordering": ["source_item_id", "target_item_id"],
                "unique_together": {("source_item", "target_item")},
                "indexes": [
                    models.Index(
                        fields=["source_item", "target_item"], name="core_dep_v2_source_target_idx"
                    )
                ],
            },
        ),
    ]
