# Generated by Django 5.2.8 on 2025-12-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0141_gantt_v2_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scheduledependencyv2",
            new_name="schedule_de_source__4ecb54_idx",
            old_name="core_dep_v2_source_target_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduleitemv2",
            new_name="schedule_it_project_919b6d_idx",
            old_name="core_item_v2_project_phase_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduleitemv2",
            new_name="schedule_it_project_91f95c_idx",
            old_name="core_item_v2_project_start_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduleitemv2",
            new_name="schedule_it_project_d8376d_idx",
            old_name="core_item_v2_project_end_idx",
        ),
        migrations.RenameIndex(
            model_name="schedulephasev2",
            new_name="schedule_ph_project_553af2_idx",
            old_name="core_phase_v2_project_order_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduletaskv2",
            new_name="schedule_ta_item_id_a85c34_idx",
            old_name="core_task_v2_item_order_idx",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("En Progreso", "En Progreso"),
                    ("En Revisión", "En Revisión"),
                    ("Completada", "Completada"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Pendiente",
                max_length=50,
            ),
        ),
    ]
