# Generated by Django 5.2.8 on 2025-12-26 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0142_rename_core_dep_v2_source_target_idx_schedule_de_source__4ecb54_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="budget_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Línea de presupuesto/fase del proyecto (solo si NO es Change Order)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="core.budgetline",
            ),
        ),
    ]
