# Generated by Django 5.2.8 on 2025-12-26 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0143_add_budget_line_to_timeentry"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="filecategory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="filecategory",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="filecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.filecategory",
            ),
        ),
        migrations.AddField(
            model_name="filecategory",
            name="share_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="is_favorited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="share_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="share_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="filecategory",
            name="color",
            field=models.CharField(default="primary", max_length=20),
        ),
        migrations.AlterField(
            model_name="filecategory",
            name="icon",
            field=models.CharField(default="bi-folder", max_length=50),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("image", "Image"),
                    ("spreadsheet", "Spreadsheet"),
                    ("word", "Word Document"),
                    ("cad", "CAD Drawing"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("status", "Estado"),
                            ("type", "Tipo"),
                            ("priority", "Prioridad"),
                            ("department", "Departamento"),
                            ("custom", "Personalizado"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "#EF4444"),
                            ("orange", "#F97316"),
                            ("yellow", "#EAB308"),
                            ("green", "#22C55E"),
                            ("cyan", "#06B6D4"),
                            ("blue", "#3B82F6"),
                            ("indigo", "#6366F1"),
                            ("purple", "#A855F7"),
                            ("pink", "#EC4899"),
                            ("slate", "#64748B"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="document_tags", to="core.project"
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="filecategory",
            name="default_tags",
            field=models.ManyToManyField(blank=True, related_name="workspaces", to="core.documenttag"),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="document_tags",
            field=models.ManyToManyField(blank=True, related_name="files", to="core.documenttag"),
        ),
    ]
