# Generated by Django 5.2.8 on 2025-12-26 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_document_management_odoo_style"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentWorkflowTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auto_assign_to_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-apply this workflow to files uploaded to this category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_workflow",
                        to="core.filecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_workflow_templates",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Workflow Template",
                "verbose_name_plural": "Document Workflow Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentWorkflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En Progreso"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.PositiveIntegerField(default=0)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("final_comment", models.TextField(blank=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="workflows", to="core.projectfile"
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="core.documentworkflowtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Workflow",
                "verbose_name_plural": "Document Workflows",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("approve", "Aprobación"),
                            ("review", "Revisión"),
                            ("sign", "Firma"),
                            ("notify", "Notificación"),
                        ],
                        default="approve",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "assigned_role",
                    models.CharField(
                        blank=True,
                        help_text="Role name (e.g., 'project_manager', 'client') - all users with this role can approve",
                        max_length=50,
                    ),
                ),
                ("requires_comment", models.BooleanField(default=False)),
                ("requires_signature", models.BooleanField(default=False)),
                (
                    "auto_approve_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Auto-approve after X days if no action (0 = disabled)"
                    ),
                ),
                ("send_email_notification", models.BooleanField(default=True)),
                (
                    "reminder_days",
                    models.PositiveIntegerField(default=3, help_text="Send reminder after X days pending"),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user to handle this step",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_steps_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.documentworkflowtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Step",
                "verbose_name_plural": "Workflow Steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStepAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("signed", "Firmado"),
                            ("commented", "Comentado"),
                            ("delegated", "Delegado"),
                            ("reminder_sent", "Recordatorio Enviado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True)),
                ("signature_image", models.ImageField(blank=True, null=True, upload_to="workflow_signatures/%Y/%m/")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "delegated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="core.workflowstep",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_actions",
                        to="core.documentworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Step Action",
                "verbose_name_plural": "Workflow Step Actions",
                "ordering": ["performed_at"],
            },
        ),
    ]
