# Generated by Django 4.2.26 on 2025-12-28 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0145_document_workflow_approvals"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskChecklistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=500)),
                ("is_completed", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("sop_reference", models.URLField(blank=True, help_text="Link a documento SOP o guía")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "task_checklist_items",
                "ordering": ["task_id", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="scheduleitemv2",
            name="weight_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje que este item representa del stage (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="schedulephasev2",
            name="weight_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje que este stage representa del proyecto total (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="scheduletaskv2",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gantt_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduletaskv2",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduletaskv2",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduletaskv2",
            name="description",
            field=models.TextField(blank=True, help_text="Descripción detallada de la tarea"),
        ),
        migrations.AddField(
            model_name="scheduletaskv2",
            name="weight_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje que esta tarea representa del item (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="scheduleitemv2",
            name="progress",
            field=models.PositiveIntegerField(default=0, help_text="0-100 (manual si no hay tareas)"),
        ),
        migrations.AlterField(
            model_name="schedulephasev2",
            name="color",
            field=models.CharField(default="#1F2937", max_length=32),
        ),
        migrations.AddIndex(
            model_name="scheduletaskv2",
            index=models.Index(fields=["assigned_to", "status"], name="schedule_ta_assigne_ef8bae_idx"),
        ),
        migrations.AddField(
            model_name="taskchecklistitem",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="checklist_items", to="core.scheduletaskv2"
            ),
        ),
    ]
