# Generated by Django 4.2.26 on 2025-12-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0146_add_weight_percent_to_schedule_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulecategory",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedulecategory",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
