# Generated by Django 4.2.26 on 2025-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0147_schedulecategory_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulephasev2",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedulephasev2",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
