# Generated by Django 4.2.26 on 2026-01-01 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0148_schedulephasev2_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="contribution_percent",
            field=models.PositiveIntegerField(
                default=0, help_text="Porcentaje de contribución de esta tarea al item del Gantt (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="schedule_item_v2",
            field=models.ForeignKey(
                blank=True,
                help_text="Item del Gantt V2 al que contribuye esta tarea",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_tasks",
                to="core.scheduleitemv2",
            ),
        ),
    ]
