# Generated by Django 5.2.8 on 2026-01-19 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0149_add_schedule_item_v2_link_to_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MinuteComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(help_text="Contenido del comentario")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minute_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "minute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="core.projectminute"
                    ),
                ),
            ],
            options={
                "verbose_name": "Minute Comment",
                "verbose_name_plural": "Minute Comments",
                "ordering": ["created_at"],
            },
        ),
    ]
