# Generated by Django 5.2.8 on 2026-01-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0150_minute_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changeorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("sent", "Sent"),
                    ("billed", "Billed"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="colorapproval",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scheduletaskv2",
            name="description",
            field=models.TextField(blank=True, help_text="Detailed task description"),
        ),
        migrations.AlterField(
            model_name="scheduletaskv2",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("blocked", "Blocked"),
                    ("done", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scheduletaskv2",
            name="weight_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage this task represents of the item (0-100)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                default="medium",
                help_text="Task priority",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Under Review", "Under Review"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
