# Generated by Django 5.2.8 on 2026-01-22 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0151_add_changeorder_pricing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitephoto",
            name="plan_pin",
            field=models.ForeignKey(
                blank=True,
                help_text="Pin on floor plan showing photo location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_photos",
                to="core.planpin",
            ),
        ),
    ]
