# Generated by Django 4.2.26 on 2026-01-23 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0152_add_plan_pin_to_sitephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailylog",
            name="accomplishments",
            field=models.TextField(blank=True, help_text="Specific accomplishments of the day"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="auto_weather",
            field=models.BooleanField(default=True, help_text="Auto-fill weather (Module 30)"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="completed_tasks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks completed or with progress today",
                related_name="daily_logs",
                to="core.task",
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="crew_count",
            field=models.PositiveIntegerField(default=0, help_text="Number of people working"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="delays",
            field=models.TextField(blank=True, help_text="Delays or problems encountered"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="incomplete_reason",
            field=models.TextField(blank=True, help_text="Reason if plan was incomplete"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="is_complete",
            field=models.BooleanField(default=False, help_text="Daily plan marked as complete"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="is_published",
            field=models.BooleanField(default=False, help_text="Visible to client/owner"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="next_day_plan",
            field=models.TextField(blank=True, help_text="Plan for the next day"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="planned_tasks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks created from templates for this day",
                related_name="planned_in_logs",
                to="core.task",
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="planned_templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Templates planned to instantiate tasks for the day",
                related_name="daily_logs",
                to="core.tasktemplate",
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="progress_notes",
            field=models.TextField(blank=True, help_text="General progress notes"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="safety_incidents",
            field=models.TextField(blank=True, help_text="Safety incidents"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="schedule_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Main schedule activity (e.g.: Cover and Prepare)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_logs",
                to="core.schedule",
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="schedule_progress_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Main activity progress (%)", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="weather",
            field=models.CharField(blank=True, help_text="Weather conditions for the day", max_length=120),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferences", models.JSONField(default=dict, help_text="Notification category preferences (JSON)")),
                ("push_enabled", models.BooleanField(default=True, help_text="Master switch for push notifications")),
                ("email_enabled", models.BooleanField(default=True, help_text="Master switch for email notifications")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns these preferences",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification preferences",
            },
        ),
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of requested document", max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("default_tags", models.ManyToManyField(blank=True, to="core.documenttag")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="document_requests", to="core.project"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_request",
                        to="core.projectfile",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requests",
                        to="core.filecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Request",
                "verbose_name_plural": "Document Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filename", models.CharField(help_text="Original filename", max_length=255)),
                ("file_path", models.CharField(help_text="Storage path", max_length=500)),
                ("file_type", models.CharField(help_text="MIME type", max_length=100)),
                ("file_size", models.IntegerField(help_text="Size in bytes")),
                (
                    "file_category",
                    models.CharField(
                        choices=[("image", "Image"), ("document", "Document"), ("other", "Other")],
                        default="other",
                        help_text="File category",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail_path",
                    models.CharField(blank=True, help_text="Thumbnail path (images only)", max_length=500, null=True),
                ),
                (
                    "upload_session_id",
                    models.CharField(blank=True, help_text="WebSocket upload session ID", max_length=100),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("download_count", models.IntegerField(default=0, help_text="Number of downloads")),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Chat channel where file was shared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachments",
                        to="core.chatchannel",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated chat message (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="core.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(fields=["channel", "-uploaded_at"], name="core_fileat_channel_56b713_idx"),
                    models.Index(fields=["user", "-uploaded_at"], name="core_fileat_user_id_ed6317_idx"),
                    models.Index(fields=["file_category", "-uploaded_at"], name="core_fileat_file_ca_c35d40_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(help_text="FCM device token", max_length=255, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("web", "Web Browser"), ("ios", "iOS"), ("android", "Android")],
                        default="web",
                        help_text="Type of device",
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, help_text="Device identifier (optional)", max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether token is still valid")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(auto_now=True, help_text="Last time token was used")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used"],
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="core_device_user_id_35ee2d_idx"),
                    models.Index(fields=["token"], name="core_device_token_3d6659_idx"),
                ],
            },
        ),
    ]
