# Generated by Django 4.2.26 on 2026-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0154_migrate_task_status_to_english"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Aprobada"),
                    ("converted", "Convertida a CO"),
                    ("rejected", "Rechazada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="colorsample",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Propuesto"),
                    ("review", "Under Review"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                    ("archived", "Archivado"),
                ],
                default="proposed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="status",
            field=models.CharField(
                choices=[("open", "Abierto"), ("in_progress", "In Progress"), ("resolved", "Resuelto")],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("SENT", "Enviada"),
                    ("VIEWED", "Vista por Cliente"),
                    ("APPROVED", "Aprobada"),
                    ("PARTIAL", "Pago Parcial"),
                    ("PAID", "Pagada Completa"),
                    ("OVERDUE", "Vencida"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("pending", "Pending"),
                    ("approved", "Aprobada"),
                    ("submitted", "Enviada"),
                    ("ordered", "Ordenada"),
                    ("partially_received", "Parcialmente recibida"),
                    ("fulfilled", "Entregada"),
                    ("cancelled", "Cancelled"),
                    ("purchased_lead", "Compra directa (líder)"),
                ],
                default="draft",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="touchuppin",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completado"),
                    ("archived", "Archivado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
