# Generated by Django 4.2.26 on 2026-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0155_alter_clientrequest_status_alter_colorsample_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskstatuschange",
            options={
                "ordering": ["-changed_at"],
                "verbose_name": "Task Status Change",
                "verbose_name_plural": "Task Status Changes",
            },
        ),
        migrations.AddField(
            model_name="changeorder",
            name="co_title",
            field=models.CharField(
                blank=True,
                help_text="Short title to identify this CO (e.g., 'Kitchen Cabinets', 'Bathroom Tile')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("task", "Task"),
                    ("invoice", "Invoice"),
                    ("estimate", "Estimate"),
                    ("payment", "Payment"),
                    ("expense", "Expense"),
                    ("inventory", "Inventory"),
                    ("damage", "Damage Report"),
                    ("color", "Color Sample"),
                    ("user", "User"),
                    ("permission", "Permission"),
                    ("document", "Document"),
                    ("system", "System"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="error_message",
            field=models.TextField(blank=True, help_text="Error message if it failed"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes about the action"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="success",
            field=models.BooleanField(default=True, help_text="Whether the action was successful"),
        ),
        migrations.AlterField(
            model_name="colorsample",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed"),
                    ("review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="proposed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT", "Sent"),
                    ("VIEWED", "Viewed by Client"),
                    ("APPROVED", "Approved"),
                    ("PARTIAL", "Partial Payment"),
                    ("PAID", "Paid Complete"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="needed_when",
            field=models.CharField(
                choices=[
                    ("now", "Ahora (emergencia)"),
                    ("tomorrow", "Tomorrow"),
                    ("next_week", "Next Week"),
                    ("date", "Specific Date"),
                ],
                default="now",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="partial_receipt_notes",
            field=models.TextField(blank=True, help_text="Notes about partial receipts"),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("submitted", "Submitted"),
                    ("ordered", "Ordered"),
                    ("partially_received", "Partially Received"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                    ("purchased_lead", "Direct Purchase (Lead)"),
                ],
                default="draft",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_created", "Tarea creada"),
                    ("task_assigned", "Task Assigned"),
                    ("task_completed", "Task Completed"),
                    ("color_review", "Color Under Review"),
                    ("color_approved", "Color Approved"),
                    ("color_rejected", "Color Rejected"),
                    ("damage_reported", "Damage Reported"),
                    ("chat_message", "Chat Message"),
                    ("comment_added", "Comment Added"),
                    ("estimate_approved", "Estimate Approved"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="paintleftover",
            name="condition",
            field=models.CharField(
                choices=[("excellent", "Excellent"), ("good", "Good"), ("fair", "Fair"), ("poor", "Poor - Do Not Use")],
                default="good",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paintleftover",
            name="location_notes",
            field=models.CharField(blank=True, help_text="Specific location notes", max_length=255),
        ),
        migrations.AlterField(
            model_name="permissionmatrix",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("task", "Task"),
                    ("invoice", "Invoice"),
                    ("estimate", "Estimate"),
                    ("payment", "Payment"),
                    ("expense", "Expense"),
                    ("inventory", "Inventory"),
                    ("damage", "Damage Report"),
                    ("color", "Color Sample"),
                    ("document", "Document"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="planpin",
            name="pin_type",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("touchup", "Touch-up"),
                    ("color", "Color"),
                    ("alert", "Alert"),
                    ("damage", "Damage"),
                ],
                default="note",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectminute",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("decision", "Decisión"),
                    ("call", "Llamada"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("approval", "Approval"),
                    ("change", "Change/Modification"),
                    ("issue", "Issue"),
                    ("milestone", "Milestone"),
                    ("note", "Note"),
                ],
                default="note",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskstatuschange",
            name="notes",
            field=models.TextField(blank=True, help_text="Optional notes about the change"),
        ),
        migrations.AlterField(
            model_name="touchuppin",
            name="approval_status",
            field=models.CharField(
                choices=[("pending_review", "Pending Review"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending_review",
                help_text="Estado de aprobación de la completion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="touchuppin",
            name="sheen",
            field=models.CharField(blank=True, help_text="Sheen: Matte, Satin, Semi-gloss, Gloss", max_length=50),
        ),
        migrations.AlterField(
            model_name="touchuppin",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("signed", "Signed"),
                    ("commented", "Commented"),
                    ("delegated", "Delegated"),
                    ("reminder_sent", "Reminder Sent"),
                ],
                max_length=20,
            ),
        ),
    ]
