# Generated by Django 4.2.26 on 2026-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0158_employee_savings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorsample",
            name="version",
            field=models.PositiveIntegerField(default=1, help_text="Increments when a variant is uploaded"),
        ),
        migrations.AlterField(
            model_name="payrollpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Total amount from payroll (amount_taken + amount_saved)", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="planpin",
            name="pin_type",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("touchup", "Touch-up"),
                    ("task", "Task"),
                    ("color", "Color"),
                    ("alert", "Alert"),
                    ("damage", "Damage"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
