# Generated by Django 4.2.26 on 2026-01-31 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0159_add_task_pin_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimateline",
            name="budget_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimate_lines",
                to="core.budgetline",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("BLOCKED", "Blocked"),
                    ("DONE", "Completed"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scheduleitemv2",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("blocked", "Blocked"),
                    ("done", "Completed"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
