# Generated by Django 4.2.26 on 2026-02-01 20:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0160_add_budget_line_to_estimateline"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimateline",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Direct unit price. If 0, uses sum of material+labor+other.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="estimateline",
            name="unit",
            field=models.CharField(blank=True, help_text="Unit of measure: sqft, pcs, hours, etc.", max_length=20),
        ),
    ]
