# Generated by Django 4.2.26 on 2026-02-03 02:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0161_add_unit_price_to_estimateline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, help_text="Auto-generated: {estimate.code}-C", max_length=50, unique=True
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_signature", "Pending Signature"),
                            ("revision_requested", "Revision Requested"),
                            ("signed", "Signed"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_signature",
                        max_length=30,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total contract amount including all markups",
                        max_digits=14,
                    ),
                ),
                (
                    "payment_schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Payment milestones: [{name, percentage, amount, due_trigger}]",
                    ),
                ),
                (
                    "client_signature",
                    models.ImageField(
                        blank=True,
                        help_text="Client's digital signature image",
                        null=True,
                        upload_to="contracts/signatures/%Y/%m/",
                    ),
                ),
                (
                    "client_signed_name",
                    models.CharField(blank=True, help_text="Client's typed name for signature", max_length=200),
                ),
                (
                    "client_signed_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when client signed", null=True),
                ),
                (
                    "client_ip_address",
                    models.GenericIPAddressField(blank=True, help_text="Client's IP address at signing", null=True),
                ),
                (
                    "contractor_signed_at",
                    models.DateTimeField(blank=True, help_text="Timestamp when contractor countersigned", null=True),
                ),
                ("revision_notes", models.TextField(blank=True, help_text="Client's notes when requesting revisions")),
                ("revision_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revision_count",
                    models.PositiveIntegerField(default=0, help_text="Number of times revisions were requested"),
                ),
                (
                    "client_view_token",
                    models.CharField(
                        blank=True, help_text="UUID token for client access without login", max_length=36, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor_signed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who countersigned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estimate",
                    models.OneToOneField(
                        help_text="Source estimate for this contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="core.estimate",
                    ),
                ),
                (
                    "pdf_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Generated contract PDF in project files",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_source",
                        to="core.projectfile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this contract belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="core.project",
                    ),
                ),
                (
                    "signed_pdf_file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Signed contract PDF in project files",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_contract_source",
                        to="core.projectfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-created_at"],
            },
        ),
    ]
