# Generated by Django 4.2.26 on 2026-02-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0162_add_contract_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="completion_date",
            field=models.DateField(blank=True, help_text="Estimated substantial completion date", null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="start_date",
            field=models.DateField(blank=True, help_text="Planned project start date", null=True),
        ),
    ]
