# Generated by Django 4.2.26 on 2026-02-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0163_add_contract_schedule_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="gantt_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Gantt schedule item (e.g.: Cover and Prepare)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_logs",
                to="core.scheduleitem",
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="schedule_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy: Main schedule activity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_logs",
                to="core.schedule",
            ),
        ),
    ]
