# Generated by Django 4.2.26 on 2026-02-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0164_add_gantt_item_to_dailylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprojectaccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("owner", "Project Owner"),
                    ("external_pm", "External PM"),
                    ("viewer", "Viewer"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
