# Generated by Django 4.2.26 on 2026-02-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0165_alter_clientprojectaccess_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="gantt_item_v2",
            field=models.ForeignKey(
                blank=True,
                help_text="Gantt V2 schedule item (e.g.: Cover and Prepare)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_logs",
                to="core.scheduleitemv2",
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="gantt_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Gantt schedule item V1 (legacy)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_logs",
                to="core.scheduleitem",
            ),
        ),
    ]
