# Generated by Django 4.2.26 on 2026-02-05 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0166_add_gantt_item_v2_to_dailylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLogScheduleProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "progress_percent",
                    models.PositiveIntegerField(default=0, help_text="Progress percentage for this activity (0-100)"),
                ),
                ("notes", models.TextField(blank=True, help_text="Notes specific to this activity's progress")),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True, decimal_places=1, help_text="Hours worked on this activity", max_digits=4, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_progress_entries",
                        to="core.dailylog",
                    ),
                ),
                (
                    "schedule_item",
                    models.ForeignKey(
                        help_text="Gantt activity worked on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_log_progress",
                        to="core.scheduleitemv2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Log Schedule Progress",
                "verbose_name_plural": "Daily Log Schedule Progress Entries",
                "ordering": ["schedule_item__order", "schedule_item__name"],
                "unique_together": {("daily_log", "schedule_item")},
            },
        ),
    ]
