# Generated by Django 4.2.26 on 2026-02-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0167_add_dailylog_schedule_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprojectaccess",
            name="can_approve_change_orders",
            field=models.BooleanField(default=False, help_text="Can approve/reject Change Orders"),
        ),
        migrations.AddField(
            model_name="clientprojectaccess",
            name="can_approve_colors",
            field=models.BooleanField(default=False, help_text="Can approve color samples"),
        ),
        migrations.AddField(
            model_name="clientprojectaccess",
            name="can_view_financials",
            field=models.BooleanField(default=False, help_text="Can see budget, costs, invoices"),
        ),
        migrations.AddField(
            model_name="clientprojectaccess",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientprojectaccess",
            name="receive_daily_reports",
            field=models.BooleanField(default=True, help_text="Receives daily progress emails"),
        ),
        migrations.AddField(
            model_name="clientprojectaccess",
            name="receive_notifications",
            field=models.BooleanField(default=True, help_text="Receives in-app notifications"),
        ),
        migrations.AlterField(
            model_name="clientprojectaccess",
            name="can_comment",
            field=models.BooleanField(default=True, help_text="Can add comments to items"),
        ),
        migrations.AlterField(
            model_name="clientprojectaccess",
            name="can_create_tasks",
            field=models.BooleanField(default=True, help_text="Can create tasks/requests"),
        ),
    ]
