# Generated by Django 4.2.26 on 2026-02-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0168_add_granular_permissions_to_clientprojectaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project associated with this notification (for filtering)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_created", "Tarea creada"),
                    ("task_assigned", "Task Assigned"),
                    ("task_completed", "Task Completed"),
                    ("color_review", "Color Under Review"),
                    ("color_approved", "Color Approved"),
                    ("color_rejected", "Color Rejected"),
                    ("damage_reported", "Damage Reported"),
                    ("chat_message", "Chat Message"),
                    ("comment_added", "Comment Added"),
                    ("estimate_approved", "Estimate Approved"),
                    ("change_order", "Change Order"),
                    ("daily_log", "Daily Log"),
                    ("invoice", "Invoice"),
                    ("contract", "Contract"),
                ],
                max_length=30,
            ),
        ),
    ]
