# Generated by Django 4.2.26 on 2026-02-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0169_add_project_to_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("daily_logs", "Daily Logs Photos"),
                    ("documents", "Documents"),
                    ("datasheets", "Datasheets"),
                    ("cos_signed", "Signed Change Orders"),
                    ("colorsamples_signed", "Signed Color Samples"),
                    ("invoices", "Invoices"),
                    ("contracts", "Contracts"),
                    ("permits", "Permits"),
                    ("drawings", "Drawings"),
                    ("photos", "Project Photos"),
                    ("reports", "Reports"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_created", "Task Created"),
                    ("task_assigned", "Task Assigned"),
                    ("task_completed", "Task Completed"),
                    ("task_alert", "Task Alert"),
                    ("color_review", "Color Under Review"),
                    ("color_approved", "Color Approved"),
                    ("color_rejected", "Color Rejected"),
                    ("damage_reported", "Damage Reported"),
                    ("chat_message", "Chat Message"),
                    ("comment_added", "Comment Added"),
                    ("estimate_approved", "Estimate Approved"),
                    ("change_order", "Change Order"),
                    ("daily_log", "Daily Log"),
                    ("invoice", "Invoice"),
                    ("contract", "Contract"),
                    ("alert", "Alert"),
                    ("reminder", "Reminder"),
                    ("system", "System"),
                ],
                max_length=30,
            ),
        ),
    ]
