# Generated by Django 4.2.26 on 2026-02-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0172_fix_colorsample_folder_and_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeorder",
            name="contractor_signature",
            field=models.ImageField(
                blank=True,
                help_text="Firma digital del contratista/admin",
                null=True,
                upload_to="changeorders/contractor_signatures/",
            ),
        ),
        migrations.AddField(
            model_name="changeorder",
            name="contractor_signed_at",
            field=models.DateTimeField(blank=True, help_text="Fecha/hora de firma del contratista", null=True),
        ),
        migrations.AddField(
            model_name="changeorder",
            name="contractor_signed_by",
            field=models.CharField(blank=True, help_text="Nombre del firmante contratista", max_length=255),
        ),
    ]
