# Generated by Django 5.2.8 on 2026-03-24 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0173_add_contractor_signature_to_changeorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorybarcode",
            name="item",
        ),
        migrations.RemoveField(
            model_name="invoiceautomation",
            name="invoice",
        ),
        migrations.DeleteModel(
            name="ExpenseOCRData",
        ),
        migrations.DeleteModel(
            name="InventoryBarcode",
        ),
        migrations.DeleteModel(
            name="InvoiceAutomation",
        ),
    ]
