# Generated by Django 5.2.8 on 2026-03-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0174_remove_inventorybarcode_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("INVOICE_PAYMENT", "Pago de factura"),
                    ("PAYROLL", "Nómina"),
                    ("OTHER", "Otro"),
                ],
                default="MANUAL",
                help_text="Cómo se generó este ingreso: manual, pago de factura, etc.",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
    ]
