# Generated by Django 5.2.8 on 2026-03-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0175_income_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="is_paid",
        ),
    ]
