# Generated by Django 5.2.8 on 2026-03-30 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0176_remove_invoice_is_paid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_created", "Task Created"),
                    ("task_assigned", "Task Assigned"),
                    ("task_completed", "Task Completed"),
                    ("task_alert", "Task Alert"),
                    ("color_review", "Color Under Review"),
                    ("color_approved", "Color Approved"),
                    ("color_rejected", "Color Rejected"),
                    ("damage_reported", "Damage Reported"),
                    ("chat_message", "Chat Message"),
                    ("comment_added", "Comment Added"),
                    ("estimate_approved", "Estimate Approved"),
                    ("change_order", "Change Order"),
                    ("daily_log", "Daily Log"),
                    ("daily_plan", "Daily Plan"),
                    ("invoice", "Invoice"),
                    ("contract", "Contract"),
                    ("alert", "Alert"),
                    ("reminder", "Reminder"),
                    ("system", "System"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ActivityComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(help_text="Comment text")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo attachment (reference, site condition, etc.)",
                        null=True,
                        upload_to="activity_comments/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="core.plannedactivity"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Comment",
                "verbose_name_plural": "Activity Comments",
                "ordering": ["created_at"],
            },
        ),
    ]
