# Generated by Django 5.2.8 on 2026-03-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0177_add_activity_comment_and_daily_plan_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_created", "Task Created"),
                    ("task_assigned", "Task Assigned"),
                    ("task_completed", "Task Completed"),
                    ("task_alert", "Task Alert"),
                    ("color_review", "Color Under Review"),
                    ("color_approved", "Color Approved"),
                    ("color_rejected", "Color Rejected"),
                    ("damage_reported", "Damage Reported"),
                    ("chat_message", "Chat Message"),
                    ("comment_added", "Comment Added"),
                    ("estimate_approved", "Estimate Approved"),
                    ("change_order", "Change Order"),
                    ("daily_log", "Daily Log"),
                    ("daily_plan", "Daily Plan"),
                    ("invoice", "Invoice"),
                    ("contract", "Contract"),
                    ("touchup", "Touch-Up"),
                    ("alert", "Alert"),
                    ("reminder", "Reminder"),
                    ("system", "System"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TouchUp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Short title for the touch-up", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description of what needs correction"),
                ),
                (
                    "goal",
                    models.TextField(
                        blank=True, help_text="Goal or objective: e.g. 'remove this stain', 'repaint this corner'"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Precautions or warnings: e.g. 'be careful with the glass'"),
                ),
                (
                    "color_name",
                    models.CharField(blank=True, help_text="Color name (e.g. SW 7008 Alabaster)", max_length=120),
                ),
                ("color_code", models.CharField(blank=True, help_text="Color code (e.g. SW 7008)", max_length=60)),
                (
                    "color_brand",
                    models.CharField(blank=True, help_text="Paint brand (e.g. Sherwin-Williams)", max_length=120),
                ),
                (
                    "color_hex",
                    models.CharField(blank=True, help_text="Hex color for visual swatch (#RRGGBB)", max_length=7),
                ),
                (
                    "sheen",
                    models.CharField(blank=True, help_text="Sheen: Matte, Satin, Semi-gloss, Gloss", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("review", "Waiting Review"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, help_text="Optional deadline", null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closing_notes", models.TextField(blank=True, help_text="Notes provided when closing")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_touchups_v2",
                        to="core.employee",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_touchups_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "color_sample",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to approved color sample if available",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="touchups_v2",
                        to="core.colorsample",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_touchups_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="touchups_v2", to="core.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Touch-Up",
                "verbose_name_plural": "Touch-Ups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TouchUpPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="touchups_v2/photos/%Y/%m/")),
                (
                    "annotations",
                    models.JSONField(
                        blank=True, default=dict, help_text="Canvas annotation data (JSON) for marks drawn on the image"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "phase",
                    models.CharField(
                        choices=[("before", "Before"), ("progress", "Progress"), ("after", "After")],
                        default="before",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "touchup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="core.touchup"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TouchUpUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(help_text="Follow-up comment")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="touchups_v2/updates/%Y/%m/")),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "touchup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="updates", to="core.touchup"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="touchup",
            index=models.Index(fields=["project", "status"], name="core_touchu_project_893387_idx"),
        ),
        migrations.AddIndex(
            model_name="touchup",
            index=models.Index(fields=["assigned_to", "status"], name="core_touchu_assigne_ec8665_idx"),
        ),
        migrations.AddIndex(
            model_name="touchup",
            index=models.Index(fields=["priority", "status"], name="core_touchu_priorit_0c1736_idx"),
        ),
    ]
