# Generated by Django 5.2.8 on 2026-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0178_add_touchup_v2_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="active_session_key",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Current active session key. Used to enforce one session per user.",
                max_length=40,
                null=True,
            ),
        ),
    ]
