# Generated by Django 5.2.8 on 2026-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0179_add_active_session_key_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitemv2",
            name="is_personal",
            field=models.BooleanField(default=False, help_text="Personal/office event — hidden from client calendars"),
        ),
    ]
