# Generated by Django 5.2.8 on 2026-04-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0180_add_is_personal_to_schedule_item_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleitemv2",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for personal/office events",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.schedulephasev2",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleitemv2",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for personal/office events",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gantt_items",
                to="core.project",
            ),
        ),
    ]
