# Generated by Django 5.2.8 on 2026-04-14 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0182_touchup_floor_plan_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="touchup",
            name="resident_email",
            field=models.EmailField(blank=True, help_text="Contact email from resident portal", max_length=254),
        ),
        migrations.AddField(
            model_name="touchup",
            name="resident_name",
            field=models.CharField(
                blank=True, help_text="Name of the resident who reported this (HOA portal)", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="touchup",
            name="resident_phone",
            field=models.CharField(blank=True, help_text="Contact phone from resident portal", max_length=30),
        ),
        migrations.AddField(
            model_name="touchup",
            name="resident_unit",
            field=models.CharField(blank=True, help_text="Unit/address identifier from resident portal", max_length=60),
        ),
        migrations.CreateModel(
            name="ResidentPortal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for the public portal URL",
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Enable/disable the portal")),
                (
                    "welcome_message",
                    models.TextField(blank=True, help_text="Custom welcome message shown to residents"),
                ),
                ("require_unit", models.BooleanField(default=True, help_text="Require unit/address when identifying")),
                ("require_email", models.BooleanField(default=False, help_text="Require email when identifying")),
                ("require_phone", models.BooleanField(default=False, help_text="Require phone when identifying")),
                (
                    "allow_photo_upload",
                    models.BooleanField(default=True, help_text="Allow residents to upload photos with touch-ups"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_portals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resident_portal", to="core.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resident Portal",
                "verbose_name_plural": "Resident Portals",
            },
        ),
        migrations.CreateModel(
            name="ResidentSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("unit", models.CharField(blank=True, max_length=60)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Django session key or generated token for cookie",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "portal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="core.residentportal"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resident Session",
                "verbose_name_plural": "Resident Sessions",
                "ordering": ["-last_active"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "identifier",
                    models.CharField(
                        help_text="Unit number or address (e.g., 'Unit 101', '1234 Main St')", max_length=60
                    ),
                ),
                (
                    "resident_name",
                    models.CharField(blank=True, help_text="Pre-assigned resident name (optional)", max_length=120),
                ),
                (
                    "floor",
                    models.IntegerField(blank=True, help_text="Floor/level for multi-story buildings", null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="units", to="core.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Unit",
                "verbose_name_plural": "Project Units",
                "ordering": ["identifier"],
                "unique_together": {("project", "identifier")},
            },
        ),
    ]
