# Generated by Django 5.2.13 on 2026-06-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_translate_invoice_line_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description (optional)"),
        ),
        migrations.AlterField(
            model_name="project",
            name="reflection_notes",
            field=models.TextField(
                blank=True, help_text="Notes on learnings, mistakes or improvements for upcoming projects"
            ),
        ),
    ]
