# Generated by Django 5.2.13 on 2026-06-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0187_alter_income_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                    ("employee", "Employee"),
                    ("project_manager", "Project Manager"),
                    ("client", "Client"),
                    ("designer", "Designer"),
                    ("superintendent", "Superintendent"),
                    ("partner", "Partner"),
                ],
                max_length=20,
            ),
        ),
    ]
