# Generated by Django 5.2.13 on 2026-06-20 23:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0188_alter_profile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RateConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "company_overhead_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        help_text="Company overhead % of contract (raise to ~9 if projected sales < $350k).",
                        max_digits=5,
                    ),
                ),
                (
                    "direction_overhead_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        help_text="Direction overhead % of contract (shown neutrally as 'overhead').",
                        max_digits=5,
                    ),
                ),
                (
                    "callback_reserve_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Callback/warranty reserve % of contract.",
                        max_digits=5,
                    ),
                ),
                (
                    "bad_debt_reserve_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Bad-debt reserve % of contract.",
                        max_digits=5,
                    ),
                ),
                (
                    "director_split_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.00"),
                        help_text="Director (owner) share of net. Remainder splits among active socios.",
                        max_digits=5,
                    ),
                ),
                (
                    "direction_overhead_destination",
                    models.CharField(
                        choices=[("DIRECTOR", "Director"), ("BUSINESS", "Business")],
                        default="BUSINESS",
                        help_text="Where the direction overhead accrues: the DIRECTOR account or the BUSINESS account.",
                        max_length=10,
                    ),
                ),
                (
                    "profit_share_start_date",
                    models.DateField(
                        help_text="Cutoff date. Only client payments on/after this date, on included projects, generate accrual. Older payments never accrue."
                    ),
                ),
                (
                    "planning_annual_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional projected annual revenue used for planning (informational).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rate Configuration",
                "verbose_name_plural": "Rate Configuration",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="in_profit_share",
            field=models.BooleanField(
                default=False, help_text="If True, this project participates in the profit-share distribution."
            ),
        ),
        migrations.CreateModel(
            name="PartnerAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_business",
                    models.BooleanField(
                        default=False, help_text="True for the single company 'caja' account (owner is NULL)."
                    ),
                ),
                (
                    "is_active_socio",
                    models.BooleanField(
                        default=True, help_text="True if this partner participates in the current 60% pool split."
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current balance. CAN be negative (advance/loan or real loss).",
                        max_digits=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        help_text="The socio/director user. NULL for the business account.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Account",
                "verbose_name_plural": "Partner Accounts",
                "ordering": ["-is_business", "owner__first_name", "owner__last_name"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("ACCRUAL", "Accrual"), ("ADVANCE", "Advance"), ("ADJUSTMENT", "Adjustment")],
                        max_length=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Signed: + accrues earnings, − advance/adjustment.", max_digits=14
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "running_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Account balance immediately after this entry.",
                        max_digits=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source project for accruals; NULL for advances/adjustments.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="core.project",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="core.partneraccount"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Entry",
                "verbose_name_plural": "Ledger Entries",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["account", "date"], name="core_ledger_account_1c2460_idx"),
                    models.Index(fields=["project", "type"], name="core_ledger_project_5628e1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectAccrualState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "accrued",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cumulative amount already posted to this account for this project.",
                        max_digits=14,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accrual_states",
                        to="core.partneraccount",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="accrual_states", to="core.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Accrual State",
                "verbose_name_plural": "Project Accrual States",
                "indexes": [models.Index(fields=["project", "account"], name="core_projec_project_79396b_idx")],
                "unique_together": {("project", "account")},
            },
        ),
    ]
