# Generated by Django 5.2.13 on 2026-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0189_rateconfig_project_in_profit_share_partneraccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHECK", "Check"),
                    ("ZELLE", "Zelle"),
                    ("TRANSFER", "Bank transfer"),
                    ("CASH", "Cash"),
                    ("OTHER", "Other"),
                ],
                help_text="How an advance/withdrawal was paid (check/Zelle/...). Blank for accruals.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="payment_reference",
            field=models.CharField(
                blank=True, help_text="Check number / Zelle confirmation / transfer reference.", max_length=120
            ),
        ),
    ]
