# Generated by Django 5.2.4 on 2025-11-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signature',
            new_name='signatures__signer__89fc36_idx',
            old_name='signatures_signer_signed_at_idx',
        ),
    ]
