# Generated by Django 5.2.13 on 2026-04-27 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("signatures", "0002_add_project_code_and_manager_assignments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="ContentType of the document being signed (Phase D4 GFK)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="Primary key of the signed document (Phase D4 GFK)", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="signature",
            index=models.Index(fields=["content_type", "object_id"], name="sig_gfk_idx"),
        ),
    ]
